FROM node:24-bookworm-slim

RUN npm install -g bun@1.3.5

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

EXPOSE 3201

CMD ["node", "./node_modules/vite/bin/vite.js", "dev", "--host", "0.0.0.0", "--port", "3201"]
