/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseResponse,
  Conversation,
  ConversationInviteRequest,
  ConversationManagersResponse,
  ConversationManagersUpdateRequest,
  ConversationPostingPolicyResponse,
  ConversationPostingPolicyUpdateRequest,
  ConversationReadUpdateRequest,
  ConversationUpdateRequest,
  ConversationsCollection,
  CreateConversationRequest,
  CreateExternalMemberRequest,
  ExternalMember,
  ExternalMembersCollection,
  ListConversationMembersParams,
  ListConversationsParams,
  NoContentResponse,
  StringsCollection,
  UpdateExternalMemberRequest
} from '../model';

import { orvalFetch } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type listConversationsResponse200 = {
  data: ConversationsCollection
  status: 200
}

export type listConversationsResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type listConversationsResponseSuccess = (listConversationsResponse200) & {
  headers: Headers;
};
export type listConversationsResponseError = (listConversationsResponseDefault) & {
  headers: Headers;
};

export type listConversationsResponse = (listConversationsResponseSuccess | listConversationsResponseError)

export const getListConversationsUrl = (params?: ListConversationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/conversations?${stringifiedParams}` : `/conversations`
}

export const listConversations = async (params?: ListConversationsParams, options?: RequestInit): Promise<listConversationsResponse> => {

  return orvalFetch<listConversationsResponse>(getListConversationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListConversationsQueryKey = (params?: ListConversationsParams,) => {
    return [
    `/conversations`, ...(params ? [params] : [])
    ] as const;
    }


export const getListConversationsQueryOptions = <TData = Awaited<ReturnType<typeof listConversations>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: ListConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversations>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListConversationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listConversations>>> = ({ signal }) => listConversations(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listConversations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListConversationsQueryResult = NonNullable<Awaited<ReturnType<typeof listConversations>>>
export type ListConversationsQueryError = ErrorType<ApiErrorResponseResponse>


export function useListConversations<TData = Awaited<ReturnType<typeof listConversations>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  ListConversationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConversations>>,
          TError,
          Awaited<ReturnType<typeof listConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConversations<TData = Awaited<ReturnType<typeof listConversations>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConversations>>,
          TError,
          Awaited<ReturnType<typeof listConversations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConversations<TData = Awaited<ReturnType<typeof listConversations>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversations>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListConversations<TData = Awaited<ReturnType<typeof listConversations>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversations>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListConversationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type createConversationResponse201 = {
  data: Conversation
  status: 201
}

export type createConversationResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 201>
}

export type createConversationResponseSuccess = (createConversationResponse201) & {
  headers: Headers;
};
export type createConversationResponseError = (createConversationResponseDefault) & {
  headers: Headers;
};

export type createConversationResponse = (createConversationResponseSuccess | createConversationResponseError)

export const getCreateConversationUrl = () => {




  return `/conversations`
}

export const createConversation = async (createConversationRequest: CreateConversationRequest, options?: RequestInit): Promise<createConversationResponse> => {

  return orvalFetch<createConversationResponse>(getCreateConversationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createConversationRequest,)
  }
);}




export const getCreateConversationMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConversation>>, TError,{data: BodyType<CreateConversationRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createConversation>>, TError,{data: BodyType<CreateConversationRequest>}, TContext> => {

const mutationKey = ['createConversation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConversation>>, {data: BodyType<CreateConversationRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createConversation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateConversationMutationResult = NonNullable<Awaited<ReturnType<typeof createConversation>>>
    export type CreateConversationMutationBody = BodyType<CreateConversationRequest>
    export type CreateConversationMutationError = ErrorType<ApiErrorResponseResponse>

    export const useCreateConversation = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConversation>>, TError,{data: BodyType<CreateConversationRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createConversation>>,
        TError,
        {data: BodyType<CreateConversationRequest>},
        TContext
      > => {
      return useMutation(getCreateConversationMutationOptions(options), queryClient);
    }
    export type getConversationResponse200 = {
  data: Conversation
  status: 200
}

export type getConversationResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getConversationResponseSuccess = (getConversationResponse200) & {
  headers: Headers;
};
export type getConversationResponseError = (getConversationResponseDefault) & {
  headers: Headers;
};

export type getConversationResponse = (getConversationResponseSuccess | getConversationResponseError)

export const getGetConversationUrl = (id: string,) => {




  return `/conversations/${id}`
}

export const getConversation = async (id: string, options?: RequestInit): Promise<getConversationResponse> => {

  return orvalFetch<getConversationResponse>(getGetConversationUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConversationQueryKey = (id: string,) => {
    return [
    `/conversations/${id}`
    ] as const;
    }


export const getGetConversationQueryOptions = <TData = Awaited<ReturnType<typeof getConversation>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversation>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConversationQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConversation>>> = ({ signal }) => getConversation(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConversation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConversationQueryResult = NonNullable<Awaited<ReturnType<typeof getConversation>>>
export type GetConversationQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetConversation<TData = Awaited<ReturnType<typeof getConversation>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversation>>,
          TError,
          Awaited<ReturnType<typeof getConversation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversation<TData = Awaited<ReturnType<typeof getConversation>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversation>>,
          TError,
          Awaited<ReturnType<typeof getConversation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversation<TData = Awaited<ReturnType<typeof getConversation>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversation>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetConversation<TData = Awaited<ReturnType<typeof getConversation>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversation>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConversationQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type updateConversationResponse200 = {
  data: Conversation
  status: 200
}

export type updateConversationResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateConversationResponseSuccess = (updateConversationResponse200) & {
  headers: Headers;
};
export type updateConversationResponseError = (updateConversationResponseDefault) & {
  headers: Headers;
};

export type updateConversationResponse = (updateConversationResponseSuccess | updateConversationResponseError)

export const getUpdateConversationUrl = (id: string,) => {




  return `/conversations/${id}`
}

export const updateConversation = async (id: string,
    conversationUpdateRequest: ConversationUpdateRequest, options?: RequestInit): Promise<updateConversationResponse> => {

  return orvalFetch<updateConversationResponse>(getUpdateConversationUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      conversationUpdateRequest,)
  }
);}




export const getUpdateConversationMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversation>>, TError,{id: string;data: BodyType<ConversationUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateConversation>>, TError,{id: string;data: BodyType<ConversationUpdateRequest>}, TContext> => {

const mutationKey = ['updateConversation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateConversation>>, {id: string;data: BodyType<ConversationUpdateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateConversation(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateConversationMutationResult = NonNullable<Awaited<ReturnType<typeof updateConversation>>>
    export type UpdateConversationMutationBody = BodyType<ConversationUpdateRequest>
    export type UpdateConversationMutationError = ErrorType<ApiErrorResponseResponse>

    export const useUpdateConversation = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversation>>, TError,{id: string;data: BodyType<ConversationUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateConversation>>,
        TError,
        {id: string;data: BodyType<ConversationUpdateRequest>},
        TContext
      > => {
      return useMutation(getUpdateConversationMutationOptions(options), queryClient);
    }
    export type listConversationMembersResponse200 = {
  data: StringsCollection
  status: 200
}

export type listConversationMembersResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type listConversationMembersResponseSuccess = (listConversationMembersResponse200) & {
  headers: Headers;
};
export type listConversationMembersResponseError = (listConversationMembersResponseDefault) & {
  headers: Headers;
};

export type listConversationMembersResponse = (listConversationMembersResponseSuccess | listConversationMembersResponseError)

export const getListConversationMembersUrl = (id: string,
    params?: ListConversationMembersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/conversations/${id}/members?${stringifiedParams}` : `/conversations/${id}/members`
}

export const listConversationMembers = async (id: string,
    params?: ListConversationMembersParams, options?: RequestInit): Promise<listConversationMembersResponse> => {

  return orvalFetch<listConversationMembersResponse>(getListConversationMembersUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListConversationMembersQueryKey = (id: string,
    params?: ListConversationMembersParams,) => {
    return [
    `/conversations/${id}/members`, ...(params ? [params] : [])
    ] as const;
    }


export const getListConversationMembersQueryOptions = <TData = Awaited<ReturnType<typeof listConversationMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string,
    params?: ListConversationMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListConversationMembersQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listConversationMembers>>> = ({ signal }) => listConversationMembers(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listConversationMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListConversationMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listConversationMembers>>>
export type ListConversationMembersQueryError = ErrorType<ApiErrorResponseResponse>


export function useListConversationMembers<TData = Awaited<ReturnType<typeof listConversationMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string,
    params: undefined |  ListConversationMembersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConversationMembers>>,
          TError,
          Awaited<ReturnType<typeof listConversationMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConversationMembers<TData = Awaited<ReturnType<typeof listConversationMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string,
    params?: ListConversationMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConversationMembers>>,
          TError,
          Awaited<ReturnType<typeof listConversationMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConversationMembers<TData = Awaited<ReturnType<typeof listConversationMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string,
    params?: ListConversationMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListConversationMembers<TData = Awaited<ReturnType<typeof listConversationMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string,
    params?: ListConversationMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListConversationMembersQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type addConversationMembersResponse200 = {
  data: Conversation
  status: 200
}

export type addConversationMembersResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type addConversationMembersResponseSuccess = (addConversationMembersResponse200) & {
  headers: Headers;
};
export type addConversationMembersResponseError = (addConversationMembersResponseDefault) & {
  headers: Headers;
};

export type addConversationMembersResponse = (addConversationMembersResponseSuccess | addConversationMembersResponseError)

export const getAddConversationMembersUrl = (id: string,) => {




  return `/conversations/${id}/members`
}

export const addConversationMembers = async (id: string,
    conversationInviteRequest: ConversationInviteRequest, options?: RequestInit): Promise<addConversationMembersResponse> => {

  return orvalFetch<addConversationMembersResponse>(getAddConversationMembersUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      conversationInviteRequest,)
  }
);}




export const getAddConversationMembersMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addConversationMembers>>, TError,{id: string;data: BodyType<ConversationInviteRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addConversationMembers>>, TError,{id: string;data: BodyType<ConversationInviteRequest>}, TContext> => {

const mutationKey = ['addConversationMembers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addConversationMembers>>, {id: string;data: BodyType<ConversationInviteRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  addConversationMembers(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddConversationMembersMutationResult = NonNullable<Awaited<ReturnType<typeof addConversationMembers>>>
    export type AddConversationMembersMutationBody = BodyType<ConversationInviteRequest>
    export type AddConversationMembersMutationError = ErrorType<ApiErrorResponseResponse>

    export const useAddConversationMembers = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addConversationMembers>>, TError,{id: string;data: BodyType<ConversationInviteRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addConversationMembers>>,
        TError,
        {id: string;data: BodyType<ConversationInviteRequest>},
        TContext
      > => {
      return useMutation(getAddConversationMembersMutationOptions(options), queryClient);
    }
    export type removeConversationMemberResponse204 = {
  data: NoContentResponse
  status: 204
}

export type removeConversationMemberResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 204>
}

export type removeConversationMemberResponseSuccess = (removeConversationMemberResponse204) & {
  headers: Headers;
};
export type removeConversationMemberResponseError = (removeConversationMemberResponseDefault) & {
  headers: Headers;
};

export type removeConversationMemberResponse = (removeConversationMemberResponseSuccess | removeConversationMemberResponseError)

export const getRemoveConversationMemberUrl = (id: string,
    userId: string,) => {




  return `/conversations/${id}/members/${userId}`
}

export const removeConversationMember = async (id: string,
    userId: string, options?: RequestInit): Promise<removeConversationMemberResponse> => {

  return orvalFetch<removeConversationMemberResponse>(getRemoveConversationMemberUrl(id,userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRemoveConversationMemberMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeConversationMember>>, TError,{id: string;userId: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeConversationMember>>, TError,{id: string;userId: string}, TContext> => {

const mutationKey = ['removeConversationMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeConversationMember>>, {id: string;userId: string}> = (props) => {
          const {id,userId} = props ?? {};

          return  removeConversationMember(id,userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveConversationMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeConversationMember>>>

    export type RemoveConversationMemberMutationError = ErrorType<ApiErrorResponseResponse>

    export const useRemoveConversationMember = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeConversationMember>>, TError,{id: string;userId: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeConversationMember>>,
        TError,
        {id: string;userId: string},
        TContext
      > => {
      return useMutation(getRemoveConversationMemberMutationOptions(options), queryClient);
    }
    export type listConversationExternalMembersResponse200 = {
  data: ExternalMembersCollection
  status: 200
}

export type listConversationExternalMembersResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type listConversationExternalMembersResponseSuccess = (listConversationExternalMembersResponse200) & {
  headers: Headers;
};
export type listConversationExternalMembersResponseError = (listConversationExternalMembersResponseDefault) & {
  headers: Headers;
};

export type listConversationExternalMembersResponse = (listConversationExternalMembersResponseSuccess | listConversationExternalMembersResponseError)

export const getListConversationExternalMembersUrl = (id: string,) => {




  return `/conversations/${id}/external-members`
}

export const listConversationExternalMembers = async (id: string, options?: RequestInit): Promise<listConversationExternalMembersResponse> => {

  return orvalFetch<listConversationExternalMembersResponse>(getListConversationExternalMembersUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListConversationExternalMembersQueryKey = (id: string,) => {
    return [
    `/conversations/${id}/external-members`
    ] as const;
    }


export const getListConversationExternalMembersQueryOptions = <TData = Awaited<ReturnType<typeof listConversationExternalMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationExternalMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListConversationExternalMembersQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listConversationExternalMembers>>> = ({ signal }) => listConversationExternalMembers(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listConversationExternalMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListConversationExternalMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listConversationExternalMembers>>>
export type ListConversationExternalMembersQueryError = ErrorType<ApiErrorResponseResponse>


export function useListConversationExternalMembers<TData = Awaited<ReturnType<typeof listConversationExternalMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationExternalMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConversationExternalMembers>>,
          TError,
          Awaited<ReturnType<typeof listConversationExternalMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConversationExternalMembers<TData = Awaited<ReturnType<typeof listConversationExternalMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationExternalMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConversationExternalMembers>>,
          TError,
          Awaited<ReturnType<typeof listConversationExternalMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConversationExternalMembers<TData = Awaited<ReturnType<typeof listConversationExternalMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationExternalMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListConversationExternalMembers<TData = Awaited<ReturnType<typeof listConversationExternalMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConversationExternalMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListConversationExternalMembersQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type createConversationExternalMemberResponse201 = {
  data: ExternalMember
  status: 201
}

export type createConversationExternalMemberResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 201>
}

export type createConversationExternalMemberResponseSuccess = (createConversationExternalMemberResponse201) & {
  headers: Headers;
};
export type createConversationExternalMemberResponseError = (createConversationExternalMemberResponseDefault) & {
  headers: Headers;
};

export type createConversationExternalMemberResponse = (createConversationExternalMemberResponseSuccess | createConversationExternalMemberResponseError)

export const getCreateConversationExternalMemberUrl = (id: string,) => {




  return `/conversations/${id}/external-members`
}

export const createConversationExternalMember = async (id: string,
    createExternalMemberRequest: CreateExternalMemberRequest, options?: RequestInit): Promise<createConversationExternalMemberResponse> => {

  return orvalFetch<createConversationExternalMemberResponse>(getCreateConversationExternalMemberUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createExternalMemberRequest,)
  }
);}




export const getCreateConversationExternalMemberMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConversationExternalMember>>, TError,{id: string;data: BodyType<CreateExternalMemberRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createConversationExternalMember>>, TError,{id: string;data: BodyType<CreateExternalMemberRequest>}, TContext> => {

const mutationKey = ['createConversationExternalMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConversationExternalMember>>, {id: string;data: BodyType<CreateExternalMemberRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  createConversationExternalMember(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateConversationExternalMemberMutationResult = NonNullable<Awaited<ReturnType<typeof createConversationExternalMember>>>
    export type CreateConversationExternalMemberMutationBody = BodyType<CreateExternalMemberRequest>
    export type CreateConversationExternalMemberMutationError = ErrorType<ApiErrorResponseResponse>

    export const useCreateConversationExternalMember = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConversationExternalMember>>, TError,{id: string;data: BodyType<CreateExternalMemberRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createConversationExternalMember>>,
        TError,
        {id: string;data: BodyType<CreateExternalMemberRequest>},
        TContext
      > => {
      return useMutation(getCreateConversationExternalMemberMutationOptions(options), queryClient);
    }
    export type updateConversationExternalMemberResponse200 = {
  data: ExternalMember
  status: 200
}

export type updateConversationExternalMemberResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateConversationExternalMemberResponseSuccess = (updateConversationExternalMemberResponse200) & {
  headers: Headers;
};
export type updateConversationExternalMemberResponseError = (updateConversationExternalMemberResponseDefault) & {
  headers: Headers;
};

export type updateConversationExternalMemberResponse = (updateConversationExternalMemberResponseSuccess | updateConversationExternalMemberResponseError)

export const getUpdateConversationExternalMemberUrl = (id: string,
    externalMemberId: string,) => {




  return `/conversations/${id}/external-members/${externalMemberId}`
}

export const updateConversationExternalMember = async (id: string,
    externalMemberId: string,
    updateExternalMemberRequest: UpdateExternalMemberRequest, options?: RequestInit): Promise<updateConversationExternalMemberResponse> => {

  return orvalFetch<updateConversationExternalMemberResponse>(getUpdateConversationExternalMemberUrl(id,externalMemberId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateExternalMemberRequest,)
  }
);}




export const getUpdateConversationExternalMemberMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationExternalMember>>, TError,{id: string;externalMemberId: string;data: BodyType<UpdateExternalMemberRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateConversationExternalMember>>, TError,{id: string;externalMemberId: string;data: BodyType<UpdateExternalMemberRequest>}, TContext> => {

const mutationKey = ['updateConversationExternalMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateConversationExternalMember>>, {id: string;externalMemberId: string;data: BodyType<UpdateExternalMemberRequest>}> = (props) => {
          const {id,externalMemberId,data} = props ?? {};

          return  updateConversationExternalMember(id,externalMemberId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateConversationExternalMemberMutationResult = NonNullable<Awaited<ReturnType<typeof updateConversationExternalMember>>>
    export type UpdateConversationExternalMemberMutationBody = BodyType<UpdateExternalMemberRequest>
    export type UpdateConversationExternalMemberMutationError = ErrorType<ApiErrorResponseResponse>

    export const useUpdateConversationExternalMember = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationExternalMember>>, TError,{id: string;externalMemberId: string;data: BodyType<UpdateExternalMemberRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateConversationExternalMember>>,
        TError,
        {id: string;externalMemberId: string;data: BodyType<UpdateExternalMemberRequest>},
        TContext
      > => {
      return useMutation(getUpdateConversationExternalMemberMutationOptions(options), queryClient);
    }
    export type deleteConversationExternalMemberResponse204 = {
  data: NoContentResponse
  status: 204
}

export type deleteConversationExternalMemberResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteConversationExternalMemberResponseSuccess = (deleteConversationExternalMemberResponse204) & {
  headers: Headers;
};
export type deleteConversationExternalMemberResponseError = (deleteConversationExternalMemberResponseDefault) & {
  headers: Headers;
};

export type deleteConversationExternalMemberResponse = (deleteConversationExternalMemberResponseSuccess | deleteConversationExternalMemberResponseError)

export const getDeleteConversationExternalMemberUrl = (id: string,
    externalMemberId: string,) => {




  return `/conversations/${id}/external-members/${externalMemberId}`
}

export const deleteConversationExternalMember = async (id: string,
    externalMemberId: string, options?: RequestInit): Promise<deleteConversationExternalMemberResponse> => {

  return orvalFetch<deleteConversationExternalMemberResponse>(getDeleteConversationExternalMemberUrl(id,externalMemberId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteConversationExternalMemberMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteConversationExternalMember>>, TError,{id: string;externalMemberId: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteConversationExternalMember>>, TError,{id: string;externalMemberId: string}, TContext> => {

const mutationKey = ['deleteConversationExternalMember'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteConversationExternalMember>>, {id: string;externalMemberId: string}> = (props) => {
          const {id,externalMemberId} = props ?? {};

          return  deleteConversationExternalMember(id,externalMemberId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteConversationExternalMemberMutationResult = NonNullable<Awaited<ReturnType<typeof deleteConversationExternalMember>>>

    export type DeleteConversationExternalMemberMutationError = ErrorType<ApiErrorResponseResponse>

    export const useDeleteConversationExternalMember = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteConversationExternalMember>>, TError,{id: string;externalMemberId: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteConversationExternalMember>>,
        TError,
        {id: string;externalMemberId: string},
        TContext
      > => {
      return useMutation(getDeleteConversationExternalMemberMutationOptions(options), queryClient);
    }
    export type getConversationManagersResponse200 = {
  data: ConversationManagersResponse
  status: 200
}

export type getConversationManagersResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getConversationManagersResponseSuccess = (getConversationManagersResponse200) & {
  headers: Headers;
};
export type getConversationManagersResponseError = (getConversationManagersResponseDefault) & {
  headers: Headers;
};

export type getConversationManagersResponse = (getConversationManagersResponseSuccess | getConversationManagersResponseError)

export const getGetConversationManagersUrl = (id: string,) => {




  return `/conversations/${id}/managers`
}

export const getConversationManagers = async (id: string, options?: RequestInit): Promise<getConversationManagersResponse> => {

  return orvalFetch<getConversationManagersResponse>(getGetConversationManagersUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConversationManagersQueryKey = (id: string,) => {
    return [
    `/conversations/${id}/managers`
    ] as const;
    }


export const getGetConversationManagersQueryOptions = <TData = Awaited<ReturnType<typeof getConversationManagers>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationManagers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConversationManagersQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConversationManagers>>> = ({ signal }) => getConversationManagers(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConversationManagers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConversationManagersQueryResult = NonNullable<Awaited<ReturnType<typeof getConversationManagers>>>
export type GetConversationManagersQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetConversationManagers<TData = Awaited<ReturnType<typeof getConversationManagers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationManagers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationManagers>>,
          TError,
          Awaited<ReturnType<typeof getConversationManagers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationManagers<TData = Awaited<ReturnType<typeof getConversationManagers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationManagers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationManagers>>,
          TError,
          Awaited<ReturnType<typeof getConversationManagers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationManagers<TData = Awaited<ReturnType<typeof getConversationManagers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationManagers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetConversationManagers<TData = Awaited<ReturnType<typeof getConversationManagers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationManagers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConversationManagersQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type updateConversationManagersResponse200 = {
  data: ConversationManagersResponse
  status: 200
}

export type updateConversationManagersResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateConversationManagersResponseSuccess = (updateConversationManagersResponse200) & {
  headers: Headers;
};
export type updateConversationManagersResponseError = (updateConversationManagersResponseDefault) & {
  headers: Headers;
};

export type updateConversationManagersResponse = (updateConversationManagersResponseSuccess | updateConversationManagersResponseError)

export const getUpdateConversationManagersUrl = (id: string,) => {




  return `/conversations/${id}/managers`
}

export const updateConversationManagers = async (id: string,
    conversationManagersUpdateRequest: ConversationManagersUpdateRequest, options?: RequestInit): Promise<updateConversationManagersResponse> => {

  return orvalFetch<updateConversationManagersResponse>(getUpdateConversationManagersUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      conversationManagersUpdateRequest,)
  }
);}




export const getUpdateConversationManagersMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationManagers>>, TError,{id: string;data: BodyType<ConversationManagersUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateConversationManagers>>, TError,{id: string;data: BodyType<ConversationManagersUpdateRequest>}, TContext> => {

const mutationKey = ['updateConversationManagers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateConversationManagers>>, {id: string;data: BodyType<ConversationManagersUpdateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateConversationManagers(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateConversationManagersMutationResult = NonNullable<Awaited<ReturnType<typeof updateConversationManagers>>>
    export type UpdateConversationManagersMutationBody = BodyType<ConversationManagersUpdateRequest>
    export type UpdateConversationManagersMutationError = ErrorType<ApiErrorResponseResponse>

    export const useUpdateConversationManagers = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationManagers>>, TError,{id: string;data: BodyType<ConversationManagersUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateConversationManagers>>,
        TError,
        {id: string;data: BodyType<ConversationManagersUpdateRequest>},
        TContext
      > => {
      return useMutation(getUpdateConversationManagersMutationOptions(options), queryClient);
    }
    export type getConversationPostingPolicyResponse200 = {
  data: ConversationPostingPolicyResponse
  status: 200
}

export type getConversationPostingPolicyResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getConversationPostingPolicyResponseSuccess = (getConversationPostingPolicyResponse200) & {
  headers: Headers;
};
export type getConversationPostingPolicyResponseError = (getConversationPostingPolicyResponseDefault) & {
  headers: Headers;
};

export type getConversationPostingPolicyResponse = (getConversationPostingPolicyResponseSuccess | getConversationPostingPolicyResponseError)

export const getGetConversationPostingPolicyUrl = (id: string,) => {




  return `/conversations/${id}/posting-policy`
}

export const getConversationPostingPolicy = async (id: string, options?: RequestInit): Promise<getConversationPostingPolicyResponse> => {

  return orvalFetch<getConversationPostingPolicyResponse>(getGetConversationPostingPolicyUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConversationPostingPolicyQueryKey = (id: string,) => {
    return [
    `/conversations/${id}/posting-policy`
    ] as const;
    }


export const getGetConversationPostingPolicyQueryOptions = <TData = Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConversationPostingPolicyQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConversationPostingPolicy>>> = ({ signal }) => getConversationPostingPolicy(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConversationPostingPolicyQueryResult = NonNullable<Awaited<ReturnType<typeof getConversationPostingPolicy>>>
export type GetConversationPostingPolicyQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetConversationPostingPolicy<TData = Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationPostingPolicy>>,
          TError,
          Awaited<ReturnType<typeof getConversationPostingPolicy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationPostingPolicy<TData = Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationPostingPolicy>>,
          TError,
          Awaited<ReturnType<typeof getConversationPostingPolicy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationPostingPolicy<TData = Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetConversationPostingPolicy<TData = Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationPostingPolicy>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConversationPostingPolicyQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type updateConversationPostingPolicyResponse200 = {
  data: ConversationPostingPolicyResponse
  status: 200
}

export type updateConversationPostingPolicyResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateConversationPostingPolicyResponseSuccess = (updateConversationPostingPolicyResponse200) & {
  headers: Headers;
};
export type updateConversationPostingPolicyResponseError = (updateConversationPostingPolicyResponseDefault) & {
  headers: Headers;
};

export type updateConversationPostingPolicyResponse = (updateConversationPostingPolicyResponseSuccess | updateConversationPostingPolicyResponseError)

export const getUpdateConversationPostingPolicyUrl = (id: string,) => {




  return `/conversations/${id}/posting-policy`
}

export const updateConversationPostingPolicy = async (id: string,
    conversationPostingPolicyUpdateRequest: ConversationPostingPolicyUpdateRequest, options?: RequestInit): Promise<updateConversationPostingPolicyResponse> => {

  return orvalFetch<updateConversationPostingPolicyResponse>(getUpdateConversationPostingPolicyUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      conversationPostingPolicyUpdateRequest,)
  }
);}




export const getUpdateConversationPostingPolicyMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationPostingPolicy>>, TError,{id: string;data: BodyType<ConversationPostingPolicyUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateConversationPostingPolicy>>, TError,{id: string;data: BodyType<ConversationPostingPolicyUpdateRequest>}, TContext> => {

const mutationKey = ['updateConversationPostingPolicy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateConversationPostingPolicy>>, {id: string;data: BodyType<ConversationPostingPolicyUpdateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateConversationPostingPolicy(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateConversationPostingPolicyMutationResult = NonNullable<Awaited<ReturnType<typeof updateConversationPostingPolicy>>>
    export type UpdateConversationPostingPolicyMutationBody = BodyType<ConversationPostingPolicyUpdateRequest>
    export type UpdateConversationPostingPolicyMutationError = ErrorType<ApiErrorResponseResponse>

    export const useUpdateConversationPostingPolicy = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationPostingPolicy>>, TError,{id: string;data: BodyType<ConversationPostingPolicyUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateConversationPostingPolicy>>,
        TError,
        {id: string;data: BodyType<ConversationPostingPolicyUpdateRequest>},
        TContext
      > => {
      return useMutation(getUpdateConversationPostingPolicyMutationOptions(options), queryClient);
    }
    export type updateConversationReadStateResponse204 = {
  data: NoContentResponse
  status: 204
}

export type updateConversationReadStateResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 204>
}

export type updateConversationReadStateResponseSuccess = (updateConversationReadStateResponse204) & {
  headers: Headers;
};
export type updateConversationReadStateResponseError = (updateConversationReadStateResponseDefault) & {
  headers: Headers;
};

export type updateConversationReadStateResponse = (updateConversationReadStateResponseSuccess | updateConversationReadStateResponseError)

export const getUpdateConversationReadStateUrl = (id: string,) => {




  return `/conversations/${id}/read-state`
}

export const updateConversationReadState = async (id: string,
    conversationReadUpdateRequest: ConversationReadUpdateRequest, options?: RequestInit): Promise<updateConversationReadStateResponse> => {

  return orvalFetch<updateConversationReadStateResponse>(getUpdateConversationReadStateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      conversationReadUpdateRequest,)
  }
);}




export const getUpdateConversationReadStateMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationReadState>>, TError,{id: string;data: BodyType<ConversationReadUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateConversationReadState>>, TError,{id: string;data: BodyType<ConversationReadUpdateRequest>}, TContext> => {

const mutationKey = ['updateConversationReadState'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateConversationReadState>>, {id: string;data: BodyType<ConversationReadUpdateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateConversationReadState(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateConversationReadStateMutationResult = NonNullable<Awaited<ReturnType<typeof updateConversationReadState>>>
    export type UpdateConversationReadStateMutationBody = BodyType<ConversationReadUpdateRequest>
    export type UpdateConversationReadStateMutationError = ErrorType<ApiErrorResponseResponse>

    export const useUpdateConversationReadState = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConversationReadState>>, TError,{id: string;data: BodyType<ConversationReadUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateConversationReadState>>,
        TError,
        {id: string;data: BodyType<ConversationReadUpdateRequest>},
        TContext
      > => {
      return useMutation(getUpdateConversationReadStateMutationOptions(options), queryClient);
    }
