/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseResponse,
  CreateUsergroupRequest,
  ListUsergroupsParams,
  NoContentResponse,
  Usergroup,
  UsergroupMembersUpdateRequest,
  UsergroupUpdateRequest,
  UsergroupsCollection,
  UsersCollection
} from '../model';

import { orvalFetch } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type listUsergroupsResponse200 = {
  data: UsergroupsCollection
  status: 200
}

export type listUsergroupsResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type listUsergroupsResponseSuccess = (listUsergroupsResponse200) & {
  headers: Headers;
};
export type listUsergroupsResponseError = (listUsergroupsResponseDefault) & {
  headers: Headers;
};

export type listUsergroupsResponse = (listUsergroupsResponseSuccess | listUsergroupsResponseError)

export const getListUsergroupsUrl = (params?: ListUsergroupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/usergroups?${stringifiedParams}` : `/usergroups`
}

export const listUsergroups = async (params?: ListUsergroupsParams, options?: RequestInit): Promise<listUsergroupsResponse> => {

  return orvalFetch<listUsergroupsResponse>(getListUsergroupsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUsergroupsQueryKey = (params?: ListUsergroupsParams,) => {
    return [
    `/usergroups`, ...(params ? [params] : [])
    ] as const;
    }


export const getListUsergroupsQueryOptions = <TData = Awaited<ReturnType<typeof listUsergroups>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: ListUsergroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroups>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsergroupsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsergroups>>> = ({ signal }) => listUsergroups(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsergroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsergroupsQueryResult = NonNullable<Awaited<ReturnType<typeof listUsergroups>>>
export type ListUsergroupsQueryError = ErrorType<ApiErrorResponseResponse>


export function useListUsergroups<TData = Awaited<ReturnType<typeof listUsergroups>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  ListUsergroupsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsergroups>>,
          TError,
          Awaited<ReturnType<typeof listUsergroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsergroups<TData = Awaited<ReturnType<typeof listUsergroups>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListUsergroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsergroups>>,
          TError,
          Awaited<ReturnType<typeof listUsergroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsergroups<TData = Awaited<ReturnType<typeof listUsergroups>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListUsergroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroups>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListUsergroups<TData = Awaited<ReturnType<typeof listUsergroups>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListUsergroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroups>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsergroupsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type createUsergroupResponse201 = {
  data: Usergroup
  status: 201
}

export type createUsergroupResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 201>
}

export type createUsergroupResponseSuccess = (createUsergroupResponse201) & {
  headers: Headers;
};
export type createUsergroupResponseError = (createUsergroupResponseDefault) & {
  headers: Headers;
};

export type createUsergroupResponse = (createUsergroupResponseSuccess | createUsergroupResponseError)

export const getCreateUsergroupUrl = () => {




  return `/usergroups`
}

export const createUsergroup = async (createUsergroupRequest: CreateUsergroupRequest, options?: RequestInit): Promise<createUsergroupResponse> => {

  return orvalFetch<createUsergroupResponse>(getCreateUsergroupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUsergroupRequest,)
  }
);}




export const getCreateUsergroupMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsergroup>>, TError,{data: BodyType<CreateUsergroupRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createUsergroup>>, TError,{data: BodyType<CreateUsergroupRequest>}, TContext> => {

const mutationKey = ['createUsergroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUsergroup>>, {data: BodyType<CreateUsergroupRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createUsergroup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUsergroupMutationResult = NonNullable<Awaited<ReturnType<typeof createUsergroup>>>
    export type CreateUsergroupMutationBody = BodyType<CreateUsergroupRequest>
    export type CreateUsergroupMutationError = ErrorType<ApiErrorResponseResponse>

    export const useCreateUsergroup = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsergroup>>, TError,{data: BodyType<CreateUsergroupRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUsergroup>>,
        TError,
        {data: BodyType<CreateUsergroupRequest>},
        TContext
      > => {
      return useMutation(getCreateUsergroupMutationOptions(options), queryClient);
    }
    export type getUsergroupResponse200 = {
  data: Usergroup
  status: 200
}

export type getUsergroupResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getUsergroupResponseSuccess = (getUsergroupResponse200) & {
  headers: Headers;
};
export type getUsergroupResponseError = (getUsergroupResponseDefault) & {
  headers: Headers;
};

export type getUsergroupResponse = (getUsergroupResponseSuccess | getUsergroupResponseError)

export const getGetUsergroupUrl = (id: string,) => {




  return `/usergroups/${id}`
}

export const getUsergroup = async (id: string, options?: RequestInit): Promise<getUsergroupResponse> => {

  return orvalFetch<getUsergroupResponse>(getGetUsergroupUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsergroupQueryKey = (id: string,) => {
    return [
    `/usergroups/${id}`
    ] as const;
    }


export const getGetUsergroupQueryOptions = <TData = Awaited<ReturnType<typeof getUsergroup>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsergroup>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsergroupQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsergroup>>> = ({ signal }) => getUsergroup(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsergroup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsergroupQueryResult = NonNullable<Awaited<ReturnType<typeof getUsergroup>>>
export type GetUsergroupQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetUsergroup<TData = Awaited<ReturnType<typeof getUsergroup>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsergroup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsergroup>>,
          TError,
          Awaited<ReturnType<typeof getUsergroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsergroup<TData = Awaited<ReturnType<typeof getUsergroup>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsergroup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsergroup>>,
          TError,
          Awaited<ReturnType<typeof getUsergroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsergroup<TData = Awaited<ReturnType<typeof getUsergroup>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsergroup>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUsergroup<TData = Awaited<ReturnType<typeof getUsergroup>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsergroup>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsergroupQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type updateUsergroupResponse200 = {
  data: Usergroup
  status: 200
}

export type updateUsergroupResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateUsergroupResponseSuccess = (updateUsergroupResponse200) & {
  headers: Headers;
};
export type updateUsergroupResponseError = (updateUsergroupResponseDefault) & {
  headers: Headers;
};

export type updateUsergroupResponse = (updateUsergroupResponseSuccess | updateUsergroupResponseError)

export const getUpdateUsergroupUrl = (id: string,) => {




  return `/usergroups/${id}`
}

export const updateUsergroup = async (id: string,
    usergroupUpdateRequest: UsergroupUpdateRequest, options?: RequestInit): Promise<updateUsergroupResponse> => {

  return orvalFetch<updateUsergroupResponse>(getUpdateUsergroupUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usergroupUpdateRequest,)
  }
);}




export const getUpdateUsergroupMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsergroup>>, TError,{id: string;data: BodyType<UsergroupUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUsergroup>>, TError,{id: string;data: BodyType<UsergroupUpdateRequest>}, TContext> => {

const mutationKey = ['updateUsergroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUsergroup>>, {id: string;data: BodyType<UsergroupUpdateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUsergroup(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateUsergroupMutationResult = NonNullable<Awaited<ReturnType<typeof updateUsergroup>>>
    export type UpdateUsergroupMutationBody = BodyType<UsergroupUpdateRequest>
    export type UpdateUsergroupMutationError = ErrorType<ApiErrorResponseResponse>

    export const useUpdateUsergroup = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsergroup>>, TError,{id: string;data: BodyType<UsergroupUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUsergroup>>,
        TError,
        {id: string;data: BodyType<UsergroupUpdateRequest>},
        TContext
      > => {
      return useMutation(getUpdateUsergroupMutationOptions(options), queryClient);
    }
    export type listUsergroupMembersResponse200 = {
  data: UsersCollection
  status: 200
}

export type listUsergroupMembersResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type listUsergroupMembersResponseSuccess = (listUsergroupMembersResponse200) & {
  headers: Headers;
};
export type listUsergroupMembersResponseError = (listUsergroupMembersResponseDefault) & {
  headers: Headers;
};

export type listUsergroupMembersResponse = (listUsergroupMembersResponseSuccess | listUsergroupMembersResponseError)

export const getListUsergroupMembersUrl = (id: string,) => {




  return `/usergroups/${id}/members`
}

export const listUsergroupMembers = async (id: string, options?: RequestInit): Promise<listUsergroupMembersResponse> => {

  return orvalFetch<listUsergroupMembersResponse>(getListUsergroupMembersUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUsergroupMembersQueryKey = (id: string,) => {
    return [
    `/usergroups/${id}/members`
    ] as const;
    }


export const getListUsergroupMembersQueryOptions = <TData = Awaited<ReturnType<typeof listUsergroupMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroupMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsergroupMembersQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsergroupMembers>>> = ({ signal }) => listUsergroupMembers(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsergroupMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsergroupMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsergroupMembers>>>
export type ListUsergroupMembersQueryError = ErrorType<ApiErrorResponseResponse>


export function useListUsergroupMembers<TData = Awaited<ReturnType<typeof listUsergroupMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroupMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsergroupMembers>>,
          TError,
          Awaited<ReturnType<typeof listUsergroupMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsergroupMembers<TData = Awaited<ReturnType<typeof listUsergroupMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroupMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsergroupMembers>>,
          TError,
          Awaited<ReturnType<typeof listUsergroupMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsergroupMembers<TData = Awaited<ReturnType<typeof listUsergroupMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroupMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListUsergroupMembers<TData = Awaited<ReturnType<typeof listUsergroupMembers>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsergroupMembers>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsergroupMembersQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type replaceUsergroupMembersResponse204 = {
  data: NoContentResponse
  status: 204
}

export type replaceUsergroupMembersResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 204>
}

export type replaceUsergroupMembersResponseSuccess = (replaceUsergroupMembersResponse204) & {
  headers: Headers;
};
export type replaceUsergroupMembersResponseError = (replaceUsergroupMembersResponseDefault) & {
  headers: Headers;
};

export type replaceUsergroupMembersResponse = (replaceUsergroupMembersResponseSuccess | replaceUsergroupMembersResponseError)

export const getReplaceUsergroupMembersUrl = (id: string,) => {




  return `/usergroups/${id}/members`
}

export const replaceUsergroupMembers = async (id: string,
    usergroupMembersUpdateRequest: UsergroupMembersUpdateRequest, options?: RequestInit): Promise<replaceUsergroupMembersResponse> => {

  return orvalFetch<replaceUsergroupMembersResponse>(getReplaceUsergroupMembersUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usergroupMembersUpdateRequest,)
  }
);}




export const getReplaceUsergroupMembersMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceUsergroupMembers>>, TError,{id: string;data: BodyType<UsergroupMembersUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceUsergroupMembers>>, TError,{id: string;data: BodyType<UsergroupMembersUpdateRequest>}, TContext> => {

const mutationKey = ['replaceUsergroupMembers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceUsergroupMembers>>, {id: string;data: BodyType<UsergroupMembersUpdateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  replaceUsergroupMembers(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReplaceUsergroupMembersMutationResult = NonNullable<Awaited<ReturnType<typeof replaceUsergroupMembers>>>
    export type ReplaceUsergroupMembersMutationBody = BodyType<UsergroupMembersUpdateRequest>
    export type ReplaceUsergroupMembersMutationError = ErrorType<ApiErrorResponseResponse>

    export const useReplaceUsergroupMembers = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceUsergroupMembers>>, TError,{id: string;data: BodyType<UsergroupMembersUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof replaceUsergroupMembers>>,
        TError,
        {id: string;data: BodyType<UsergroupMembersUpdateRequest>},
        TContext
      > => {
      return useMutation(getReplaceUsergroupMembersMutationOptions(options), queryClient);
    }
