/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseResponse,
  AuthResponse,
  CompleteGitHubOAuthParams,
  CompleteGoogleOAuthParams,
  GenericStatusResponse,
  OAuthStartRequest,
  OAuthStartResponse,
  StartEmailLoginRequest,
  VerifyEmailLoginRequest
} from '../model';

import { orvalFetch } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


/**
 * Sends a one-time verification code to the supplied email address.
 * @summary Start email sign-in
 */
export type startEmailLoginResponse202 = {
  data: GenericStatusResponse
  status: 202
}

export type startEmailLoginResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 202>
}

export type startEmailLoginResponseSuccess = (startEmailLoginResponse202) & {
  headers: Headers;
};
export type startEmailLoginResponseError = (startEmailLoginResponseDefault) & {
  headers: Headers;
};

export type startEmailLoginResponse = (startEmailLoginResponseSuccess | startEmailLoginResponseError)

export const getStartEmailLoginUrl = () => {




  return `/auth/email/start`
}

export const startEmailLogin = async (startEmailLoginRequest: StartEmailLoginRequest, options?: RequestInit): Promise<startEmailLoginResponse> => {

  return orvalFetch<startEmailLoginResponse>(getStartEmailLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      startEmailLoginRequest,)
  }
);}




export const getStartEmailLoginMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startEmailLogin>>, TError,{data: BodyType<StartEmailLoginRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof startEmailLogin>>, TError,{data: BodyType<StartEmailLoginRequest>}, TContext> => {

const mutationKey = ['startEmailLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startEmailLogin>>, {data: BodyType<StartEmailLoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  startEmailLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartEmailLoginMutationResult = NonNullable<Awaited<ReturnType<typeof startEmailLogin>>>
    export type StartEmailLoginMutationBody = BodyType<StartEmailLoginRequest>
    export type StartEmailLoginMutationError = ErrorType<ApiErrorResponseResponse>

    /**
 * @summary Start email sign-in
 */
export const useStartEmailLogin = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startEmailLogin>>, TError,{data: BodyType<StartEmailLoginRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startEmailLogin>>,
        TError,
        {data: BodyType<StartEmailLoginRequest>},
        TContext
      > => {
      return useMutation(getStartEmailLoginMutationOptions(options), queryClient);
    }
    /**
 * Exchanges an email verification code for a session and authenticated user payload.
 * @summary Complete email sign-in
 */
export type verifyEmailLoginResponse200 = {
  data: AuthResponse
  status: 200
}

export type verifyEmailLoginResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type verifyEmailLoginResponseSuccess = (verifyEmailLoginResponse200) & {
  headers: Headers;
};
export type verifyEmailLoginResponseError = (verifyEmailLoginResponseDefault) & {
  headers: Headers;
};

export type verifyEmailLoginResponse = (verifyEmailLoginResponseSuccess | verifyEmailLoginResponseError)

export const getVerifyEmailLoginUrl = () => {




  return `/auth/email/verify`
}

export const verifyEmailLogin = async (verifyEmailLoginRequest: VerifyEmailLoginRequest, options?: RequestInit): Promise<verifyEmailLoginResponse> => {

  return orvalFetch<verifyEmailLoginResponse>(getVerifyEmailLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailLoginRequest,)
  }
);}




export const getVerifyEmailLoginMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyEmailLogin>>, TError,{data: BodyType<VerifyEmailLoginRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyEmailLogin>>, TError,{data: BodyType<VerifyEmailLoginRequest>}, TContext> => {

const mutationKey = ['verifyEmailLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyEmailLogin>>, {data: BodyType<VerifyEmailLoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  verifyEmailLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VerifyEmailLoginMutationResult = NonNullable<Awaited<ReturnType<typeof verifyEmailLogin>>>
    export type VerifyEmailLoginMutationBody = BodyType<VerifyEmailLoginRequest>
    export type VerifyEmailLoginMutationError = ErrorType<ApiErrorResponseResponse>

    /**
 * @summary Complete email sign-in
 */
export const useVerifyEmailLogin = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyEmailLogin>>, TError,{data: BodyType<VerifyEmailLoginRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyEmailLogin>>,
        TError,
        {data: BodyType<VerifyEmailLoginRequest>},
        TContext
      > => {
      return useMutation(getVerifyEmailLoginMutationOptions(options), queryClient);
    }
    /**
 * Creates an OAuth state record and returns the Google authorization URL to open in the browser.
 * @summary Start Google OAuth
 */
export type startGoogleOAuthResponse200 = {
  data: OAuthStartResponse
  status: 200
}

export type startGoogleOAuthResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type startGoogleOAuthResponseSuccess = (startGoogleOAuthResponse200) & {
  headers: Headers;
};
export type startGoogleOAuthResponseError = (startGoogleOAuthResponseDefault) & {
  headers: Headers;
};

export type startGoogleOAuthResponse = (startGoogleOAuthResponseSuccess | startGoogleOAuthResponseError)

export const getStartGoogleOAuthUrl = () => {




  return `/auth/oauth/google/start`
}

export const startGoogleOAuth = async (oAuthStartRequest: OAuthStartRequest, options?: RequestInit): Promise<startGoogleOAuthResponse> => {

  return orvalFetch<startGoogleOAuthResponse>(getStartGoogleOAuthUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthStartRequest,)
  }
);}




export const getStartGoogleOAuthMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startGoogleOAuth>>, TError,{data: BodyType<OAuthStartRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof startGoogleOAuth>>, TError,{data: BodyType<OAuthStartRequest>}, TContext> => {

const mutationKey = ['startGoogleOAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startGoogleOAuth>>, {data: BodyType<OAuthStartRequest>}> = (props) => {
          const {data} = props ?? {};

          return  startGoogleOAuth(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartGoogleOAuthMutationResult = NonNullable<Awaited<ReturnType<typeof startGoogleOAuth>>>
    export type StartGoogleOAuthMutationBody = BodyType<OAuthStartRequest>
    export type StartGoogleOAuthMutationError = ErrorType<ApiErrorResponseResponse>

    /**
 * @summary Start Google OAuth
 */
export const useStartGoogleOAuth = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startGoogleOAuth>>, TError,{data: BodyType<OAuthStartRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startGoogleOAuth>>,
        TError,
        {data: BodyType<OAuthStartRequest>},
        TContext
      > => {
      return useMutation(getStartGoogleOAuthMutationOptions(options), queryClient);
    }
    /**
 * Completes the Google OAuth flow using the provider callback code and state.
 * @summary Complete Google OAuth
 */
export type completeGoogleOAuthResponse200 = {
  data: AuthResponse
  status: 200
}

export type completeGoogleOAuthResponse302 = {
  data: void
  status: 302
}

export type completeGoogleOAuthResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200 | 302>
}

export type completeGoogleOAuthResponseSuccess = (completeGoogleOAuthResponse200) & {
  headers: Headers;
};
export type completeGoogleOAuthResponseError = (completeGoogleOAuthResponse302 | completeGoogleOAuthResponseDefault) & {
  headers: Headers;
};

export type completeGoogleOAuthResponse = (completeGoogleOAuthResponseSuccess | completeGoogleOAuthResponseError)

export const getCompleteGoogleOAuthUrl = (params: CompleteGoogleOAuthParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/oauth/google/callback?${stringifiedParams}` : `/auth/oauth/google/callback`
}

export const completeGoogleOAuth = async (params: CompleteGoogleOAuthParams, options?: RequestInit): Promise<completeGoogleOAuthResponse> => {

  return orvalFetch<completeGoogleOAuthResponse>(getCompleteGoogleOAuthUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCompleteGoogleOAuthQueryKey = (params?: CompleteGoogleOAuthParams,) => {
    return [
    `/auth/oauth/google/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getCompleteGoogleOAuthQueryOptions = <TData = Awaited<ReturnType<typeof completeGoogleOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(params: CompleteGoogleOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGoogleOAuth>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompleteGoogleOAuthQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof completeGoogleOAuth>>> = ({ signal }) => completeGoogleOAuth(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof completeGoogleOAuth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompleteGoogleOAuthQueryResult = NonNullable<Awaited<ReturnType<typeof completeGoogleOAuth>>>
export type CompleteGoogleOAuthQueryError = ErrorType<void | ApiErrorResponseResponse>


export function useCompleteGoogleOAuth<TData = Awaited<ReturnType<typeof completeGoogleOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGoogleOAuthParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGoogleOAuth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof completeGoogleOAuth>>,
          TError,
          Awaited<ReturnType<typeof completeGoogleOAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompleteGoogleOAuth<TData = Awaited<ReturnType<typeof completeGoogleOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGoogleOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGoogleOAuth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof completeGoogleOAuth>>,
          TError,
          Awaited<ReturnType<typeof completeGoogleOAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompleteGoogleOAuth<TData = Awaited<ReturnType<typeof completeGoogleOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGoogleOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGoogleOAuth>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Complete Google OAuth
 */

export function useCompleteGoogleOAuth<TData = Awaited<ReturnType<typeof completeGoogleOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGoogleOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGoogleOAuth>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompleteGoogleOAuthQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Creates an OAuth state record and returns the GitHub authorization URL to open in the browser.
 * @summary Start GitHub OAuth
 */
export type startGitHubOAuthResponse200 = {
  data: OAuthStartResponse
  status: 200
}

export type startGitHubOAuthResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type startGitHubOAuthResponseSuccess = (startGitHubOAuthResponse200) & {
  headers: Headers;
};
export type startGitHubOAuthResponseError = (startGitHubOAuthResponseDefault) & {
  headers: Headers;
};

export type startGitHubOAuthResponse = (startGitHubOAuthResponseSuccess | startGitHubOAuthResponseError)

export const getStartGitHubOAuthUrl = () => {




  return `/auth/oauth/github/start`
}

export const startGitHubOAuth = async (oAuthStartRequest: OAuthStartRequest, options?: RequestInit): Promise<startGitHubOAuthResponse> => {

  return orvalFetch<startGitHubOAuthResponse>(getStartGitHubOAuthUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthStartRequest,)
  }
);}




export const getStartGitHubOAuthMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startGitHubOAuth>>, TError,{data: BodyType<OAuthStartRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof startGitHubOAuth>>, TError,{data: BodyType<OAuthStartRequest>}, TContext> => {

const mutationKey = ['startGitHubOAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startGitHubOAuth>>, {data: BodyType<OAuthStartRequest>}> = (props) => {
          const {data} = props ?? {};

          return  startGitHubOAuth(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartGitHubOAuthMutationResult = NonNullable<Awaited<ReturnType<typeof startGitHubOAuth>>>
    export type StartGitHubOAuthMutationBody = BodyType<OAuthStartRequest>
    export type StartGitHubOAuthMutationError = ErrorType<ApiErrorResponseResponse>

    /**
 * @summary Start GitHub OAuth
 */
export const useStartGitHubOAuth = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startGitHubOAuth>>, TError,{data: BodyType<OAuthStartRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startGitHubOAuth>>,
        TError,
        {data: BodyType<OAuthStartRequest>},
        TContext
      > => {
      return useMutation(getStartGitHubOAuthMutationOptions(options), queryClient);
    }
    /**
 * Completes the GitHub OAuth flow using the provider callback code and state.
 * @summary Complete GitHub OAuth
 */
export type completeGitHubOAuthResponse200 = {
  data: AuthResponse
  status: 200
}

export type completeGitHubOAuthResponse302 = {
  data: void
  status: 302
}

export type completeGitHubOAuthResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200 | 302>
}

export type completeGitHubOAuthResponseSuccess = (completeGitHubOAuthResponse200) & {
  headers: Headers;
};
export type completeGitHubOAuthResponseError = (completeGitHubOAuthResponse302 | completeGitHubOAuthResponseDefault) & {
  headers: Headers;
};

export type completeGitHubOAuthResponse = (completeGitHubOAuthResponseSuccess | completeGitHubOAuthResponseError)

export const getCompleteGitHubOAuthUrl = (params: CompleteGitHubOAuthParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/oauth/github/callback?${stringifiedParams}` : `/auth/oauth/github/callback`
}

export const completeGitHubOAuth = async (params: CompleteGitHubOAuthParams, options?: RequestInit): Promise<completeGitHubOAuthResponse> => {

  return orvalFetch<completeGitHubOAuthResponse>(getCompleteGitHubOAuthUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCompleteGitHubOAuthQueryKey = (params?: CompleteGitHubOAuthParams,) => {
    return [
    `/auth/oauth/github/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getCompleteGitHubOAuthQueryOptions = <TData = Awaited<ReturnType<typeof completeGitHubOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(params: CompleteGitHubOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGitHubOAuth>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompleteGitHubOAuthQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof completeGitHubOAuth>>> = ({ signal }) => completeGitHubOAuth(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof completeGitHubOAuth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompleteGitHubOAuthQueryResult = NonNullable<Awaited<ReturnType<typeof completeGitHubOAuth>>>
export type CompleteGitHubOAuthQueryError = ErrorType<void | ApiErrorResponseResponse>


export function useCompleteGitHubOAuth<TData = Awaited<ReturnType<typeof completeGitHubOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGitHubOAuthParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGitHubOAuth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof completeGitHubOAuth>>,
          TError,
          Awaited<ReturnType<typeof completeGitHubOAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompleteGitHubOAuth<TData = Awaited<ReturnType<typeof completeGitHubOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGitHubOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGitHubOAuth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof completeGitHubOAuth>>,
          TError,
          Awaited<ReturnType<typeof completeGitHubOAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompleteGitHubOAuth<TData = Awaited<ReturnType<typeof completeGitHubOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGitHubOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGitHubOAuth>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Complete GitHub OAuth
 */

export function useCompleteGitHubOAuth<TData = Awaited<ReturnType<typeof completeGitHubOAuth>>, TError = ErrorType<void | ApiErrorResponseResponse>>(
 params: CompleteGitHubOAuthParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completeGitHubOAuth>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompleteGitHubOAuthQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Revokes the authenticated browser or bearer session. This endpoint requires a session credential rather than an API key.
 * @summary Revoke current session
 */
export type revokeCurrentSessionResponse204 = {
  data: void
  status: 204
}

export type revokeCurrentSessionResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 204>
}

export type revokeCurrentSessionResponseSuccess = (revokeCurrentSessionResponse204) & {
  headers: Headers;
};
export type revokeCurrentSessionResponseError = (revokeCurrentSessionResponseDefault) & {
  headers: Headers;
};

export type revokeCurrentSessionResponse = (revokeCurrentSessionResponseSuccess | revokeCurrentSessionResponseError)

export const getRevokeCurrentSessionUrl = () => {




  return `/auth/sessions/current`
}

export const revokeCurrentSession = async ( options?: RequestInit): Promise<revokeCurrentSessionResponse> => {

  return orvalFetch<revokeCurrentSessionResponse>(getRevokeCurrentSessionUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRevokeCurrentSessionMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeCurrentSession>>, TError,void, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeCurrentSession>>, TError,void, TContext> => {

const mutationKey = ['revokeCurrentSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeCurrentSession>>, void> = () => {


          return  revokeCurrentSession(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeCurrentSessionMutationResult = NonNullable<Awaited<ReturnType<typeof revokeCurrentSession>>>

    export type RevokeCurrentSessionMutationError = ErrorType<ApiErrorResponseResponse>

    /**
 * @summary Revoke current session
 */
export const useRevokeCurrentSession = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeCurrentSession>>, TError,void, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeCurrentSession>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRevokeCurrentSessionMutationOptions(options), queryClient);
    }
