// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of, type, environment, permissions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
          type, environment, permissions, expires_at, last_used_at, request_count,
          revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
`

type CreateAPIKeyParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	KeyHint     string             `json:"key_hint"`
	TeamID      string             `json:"team_id"`
	PrincipalID string             `json:"principal_id"`
	CreatedBy   string             `json:"created_by"`
	OnBehalfOf  string             `json:"on_behalf_of"`
	Type        string             `json:"type"`
	Environment string             `json:"environment"`
	Permissions []string           `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.KeyHint,
		arg.TeamID,
		arg.PrincipalID,
		arg.CreatedBy,
		arg.OnBehalfOf,
		arg.Type,
		arg.Environment,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeyHint,
		&i.TeamID,
		&i.PrincipalID,
		&i.CreatedBy,
		&i.OnBehalfOf,
		&i.Type,
		&i.Environment,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RequestCount,
		&i.Revoked,
		&i.RevokedAt,
		&i.RotatedToID,
		&i.GracePeriodEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
       type, environment, permissions, expires_at, last_used_at, request_count,
       revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeyHint,
		&i.TeamID,
		&i.PrincipalID,
		&i.CreatedBy,
		&i.OnBehalfOf,
		&i.Type,
		&i.Environment,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RequestCount,
		&i.Revoked,
		&i.RevokedAt,
		&i.RotatedToID,
		&i.GracePeriodEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
       type, environment, permissions, expires_at, last_used_at, request_count,
       revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeyHint,
		&i.TeamID,
		&i.PrincipalID,
		&i.CreatedBy,
		&i.OnBehalfOf,
		&i.Type,
		&i.Environment,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RequestCount,
		&i.Revoked,
		&i.RevokedAt,
		&i.RotatedToID,
		&i.GracePeriodEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
       type, environment, permissions, expires_at, last_used_at, request_count,
       revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
FROM api_keys
WHERE team_id = $1 AND id >= $2 AND revoked = FALSE
ORDER BY id ASC
LIMIT $3
`

type ListAPIKeysParams struct {
	TeamID string `json:"team_id"`
	ID     string `json:"id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.TeamID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.KeyHint,
			&i.TeamID,
			&i.PrincipalID,
			&i.CreatedBy,
			&i.OnBehalfOf,
			&i.Type,
			&i.Environment,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RequestCount,
			&i.Revoked,
			&i.RevokedAt,
			&i.RotatedToID,
			&i.GracePeriodEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByPrincipal = `-- name: ListAPIKeysByPrincipal :many
SELECT id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
       type, environment, permissions, expires_at, last_used_at, request_count,
       revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
FROM api_keys
WHERE team_id = $1 AND principal_id = $2 AND id >= $3 AND revoked = FALSE
ORDER BY id ASC
LIMIT $4
`

type ListAPIKeysByPrincipalParams struct {
	TeamID      string `json:"team_id"`
	PrincipalID string `json:"principal_id"`
	ID          string `json:"id"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) ListAPIKeysByPrincipal(ctx context.Context, arg ListAPIKeysByPrincipalParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByPrincipal,
		arg.TeamID,
		arg.PrincipalID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.KeyHint,
			&i.TeamID,
			&i.PrincipalID,
			&i.CreatedBy,
			&i.OnBehalfOf,
			&i.Type,
			&i.Environment,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RequestCount,
			&i.Revoked,
			&i.RevokedAt,
			&i.RotatedToID,
			&i.GracePeriodEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByPrincipalIncludeRevoked = `-- name: ListAPIKeysByPrincipalIncludeRevoked :many
SELECT id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
       type, environment, permissions, expires_at, last_used_at, request_count,
       revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
FROM api_keys
WHERE team_id = $1 AND principal_id = $2 AND id >= $3
ORDER BY id ASC
LIMIT $4
`

type ListAPIKeysByPrincipalIncludeRevokedParams struct {
	TeamID      string `json:"team_id"`
	PrincipalID string `json:"principal_id"`
	ID          string `json:"id"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) ListAPIKeysByPrincipalIncludeRevoked(ctx context.Context, arg ListAPIKeysByPrincipalIncludeRevokedParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByPrincipalIncludeRevoked,
		arg.TeamID,
		arg.PrincipalID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.KeyHint,
			&i.TeamID,
			&i.PrincipalID,
			&i.CreatedBy,
			&i.OnBehalfOf,
			&i.Type,
			&i.Environment,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RequestCount,
			&i.Revoked,
			&i.RevokedAt,
			&i.RotatedToID,
			&i.GracePeriodEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysIncludeRevoked = `-- name: ListAPIKeysIncludeRevoked :many
SELECT id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
       type, environment, permissions, expires_at, last_used_at, request_count,
       revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
FROM api_keys
WHERE team_id = $1 AND id >= $2
ORDER BY id ASC
LIMIT $3
`

type ListAPIKeysIncludeRevokedParams struct {
	TeamID string `json:"team_id"`
	ID     string `json:"id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListAPIKeysIncludeRevoked(ctx context.Context, arg ListAPIKeysIncludeRevokedParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysIncludeRevoked, arg.TeamID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.KeyHint,
			&i.TeamID,
			&i.PrincipalID,
			&i.CreatedBy,
			&i.OnBehalfOf,
			&i.Type,
			&i.Environment,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RequestCount,
			&i.Revoked,
			&i.RevokedAt,
			&i.RotatedToID,
			&i.GracePeriodEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked = TRUE, revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const setAPIKeyRotated = `-- name: SetAPIKeyRotated :exec
UPDATE api_keys SET rotated_to_id = $2, grace_period_ends_at = $3, revoked = TRUE, revoked_at = NOW() WHERE id = $1
`

type SetAPIKeyRotatedParams struct {
	ID                string             `json:"id"`
	RotatedToID       string             `json:"rotated_to_id"`
	GracePeriodEndsAt pgtype.Timestamptz `json:"grace_period_ends_at"`
}

func (q *Queries) SetAPIKeyRotated(ctx context.Context, arg SetAPIKeyRotatedParams) error {
	_, err := q.db.Exec(ctx, setAPIKeyRotated, arg.ID, arg.RotatedToID, arg.GracePeriodEndsAt)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys
SET name = $2, description = $3, permissions = $4
WHERE id = $1
RETURNING id, name, description, key_hash, key_prefix, key_hint, team_id, principal_id, created_by, on_behalf_of,
          type, environment, permissions, expires_at, last_used_at, request_count,
          revoked, revoked_at, rotated_to_id, grace_period_ends_at, created_at, updated_at
`

type UpdateAPIKeyParams struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKey,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Permissions,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeyHint,
		&i.TeamID,
		&i.PrincipalID,
		&i.CreatedBy,
		&i.OnBehalfOf,
		&i.Type,
		&i.Environment,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RequestCount,
		&i.Revoked,
		&i.RevokedAt,
		&i.RotatedToID,
		&i.GracePeriodEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIKeyUsage = `-- name: UpdateAPIKeyUsage :exec
UPDATE api_keys SET last_used_at = NOW(), request_count = request_count + 1 WHERE id = $1
`

func (q *Queries) UpdateAPIKeyUsage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyUsage, id)
	return err
}
