// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarks.sql

package sqlcgen

import (
	"context"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (id, channel_id, title, type, link, emoji, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, channel_id, title, type, link, emoji, created_by, updated_by, created_at, updated_at
`

type CreateBookmarkParams struct {
	ID        string `json:"id"`
	ChannelID string `json:"channel_id"`
	Title     string `json:"title"`
	Type      string `json:"type"`
	Link      string `json:"link"`
	Emoji     string `json:"emoji"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, createBookmark,
		arg.ID,
		arg.ChannelID,
		arg.Title,
		arg.Type,
		arg.Link,
		arg.Emoji,
		arg.CreatedBy,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Type,
		&i.Link,
		&i.Emoji,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE id = $1
`

func (q *Queries) DeleteBookmark(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBookmark, id)
	return err
}

const getBookmark = `-- name: GetBookmark :one
SELECT id, channel_id, title, type, link, emoji, created_by, updated_by, created_at, updated_at
FROM bookmarks WHERE id = $1
`

func (q *Queries) GetBookmark(ctx context.Context, id string) (Bookmark, error) {
	row := q.db.QueryRow(ctx, getBookmark, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Type,
		&i.Link,
		&i.Emoji,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT id, channel_id, title, type, link, emoji, created_by, updated_by, created_at, updated_at
FROM bookmarks WHERE channel_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBookmarks(ctx context.Context, channelID string) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, listBookmarks, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Type,
			&i.Link,
			&i.Emoji,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookmark = `-- name: UpdateBookmark :one
UPDATE bookmarks SET title = $2, link = $3, emoji = $4, updated_by = $5
WHERE id = $1
RETURNING id, channel_id, title, type, link, emoji, created_by, updated_by, created_at, updated_at
`

type UpdateBookmarkParams struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Link      string `json:"link"`
	Emoji     string `json:"emoji"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, updateBookmark,
		arg.ID,
		arg.Title,
		arg.Link,
		arg.Emoji,
		arg.UpdatedBy,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Type,
		&i.Link,
		&i.Emoji,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
