// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_log.sql

package sqlcgen

import (
	"context"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO event_log (aggregate_type, aggregate_id, event_type, event_data, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING sequence_id, aggregate_type, aggregate_id, event_type, event_data, metadata, created_at
`

type AppendEventParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	EventType     string `json:"event_type"`
	EventData     []byte `json:"event_data"`
	Metadata      []byte `json:"metadata"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.EventData,
		arg.Metadata,
	)
	var i EventLog
	err := row.Scan(
		&i.SequenceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventData,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAllEventsSince = `-- name: GetAllEventsSince :many
SELECT sequence_id, aggregate_type, aggregate_id, event_type, event_data, metadata, created_at
FROM event_log
WHERE sequence_id > $1
ORDER BY sequence_id ASC
LIMIT $2
`

type GetAllEventsSinceParams struct {
	SequenceID int64 `json:"sequence_id"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) GetAllEventsSince(ctx context.Context, arg GetAllEventsSinceParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, getAllEventsSince, arg.SequenceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.SequenceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.EventData,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByAggregate = `-- name: GetEventsByAggregate :many
SELECT sequence_id, aggregate_type, aggregate_id, event_type, event_data, metadata, created_at
FROM event_log
WHERE aggregate_type = $1 AND aggregate_id = $2
ORDER BY sequence_id ASC
`

type GetEventsByAggregateParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
}

func (q *Queries) GetEventsByAggregate(ctx context.Context, arg GetEventsByAggregateParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, getEventsByAggregate, arg.AggregateType, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.SequenceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.EventData,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByAggregateSince = `-- name: GetEventsByAggregateSince :many
SELECT sequence_id, aggregate_type, aggregate_id, event_type, event_data, metadata, created_at
FROM event_log
WHERE aggregate_type = $1 AND aggregate_id = $2 AND sequence_id > $3
ORDER BY sequence_id ASC
`

type GetEventsByAggregateSinceParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	SequenceID    int64  `json:"sequence_id"`
}

func (q *Queries) GetEventsByAggregateSince(ctx context.Context, arg GetEventsByAggregateSinceParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, getEventsByAggregateSince, arg.AggregateType, arg.AggregateID, arg.SequenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.SequenceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.EventData,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByType = `-- name: GetEventsByType :many
SELECT sequence_id, aggregate_type, aggregate_id, event_type, event_data, metadata, created_at
FROM event_log
WHERE event_type = $1
ORDER BY sequence_id DESC
LIMIT $2
`

type GetEventsByTypeParams struct {
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, getEventsByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.SequenceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.EventData,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
