// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, name, title, mimetype, filetype, size, user_id, s3_key,
                   url_private, url_private_download, permalink, is_external, external_url, upload_complete)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateFileParams struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	Title              string `json:"title"`
	Mimetype           string `json:"mimetype"`
	Filetype           string `json:"filetype"`
	Size               int64  `json:"size"`
	UserID             string `json:"user_id"`
	S3Key              string `json:"s3_key"`
	UrlPrivate         string `json:"url_private"`
	UrlPrivateDownload string `json:"url_private_download"`
	Permalink          string `json:"permalink"`
	IsExternal         bool   `json:"is_external"`
	ExternalUrl        string `json:"external_url"`
	UploadComplete     bool   `json:"upload_complete"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Mimetype,
		arg.Filetype,
		arg.Size,
		arg.UserID,
		arg.S3Key,
		arg.UrlPrivate,
		arg.UrlPrivateDownload,
		arg.Permalink,
		arg.IsExternal,
		arg.ExternalUrl,
		arg.UploadComplete,
	)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, name, title, mimetype, filetype, size, user_id,
       url_private, url_private_download, permalink, is_external, external_url,
       created_at, updated_at
FROM files WHERE id = $1
`

type GetFileRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Title              string             `json:"title"`
	Mimetype           string             `json:"mimetype"`
	Filetype           string             `json:"filetype"`
	Size               int64              `json:"size"`
	UserID             string             `json:"user_id"`
	UrlPrivate         string             `json:"url_private"`
	UrlPrivateDownload string             `json:"url_private_download"`
	Permalink          string             `json:"permalink"`
	IsExternal         bool               `json:"is_external"`
	ExternalUrl        string             `json:"external_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFile(ctx context.Context, id string) (GetFileRow, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i GetFileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Mimetype,
		&i.Filetype,
		&i.Size,
		&i.UserID,
		&i.UrlPrivate,
		&i.UrlPrivateDownload,
		&i.Permalink,
		&i.IsExternal,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileChannels = `-- name: GetFileChannels :many
SELECT channel_id FROM file_channels WHERE file_id = $1 ORDER BY shared_at ASC
`

func (q *Queries) GetFileChannels(ctx context.Context, fileID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getFileChannels, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT id, name, title, mimetype, filetype, size, user_id,
       url_private, url_private_download, permalink, is_external, external_url,
       created_at, updated_at
FROM files
WHERE id > $1
ORDER BY id ASC
LIMIT $2
`

type ListFilesParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

type ListFilesRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Title              string             `json:"title"`
	Mimetype           string             `json:"mimetype"`
	Filetype           string             `json:"filetype"`
	Size               int64              `json:"size"`
	UserID             string             `json:"user_id"`
	UrlPrivate         string             `json:"url_private"`
	UrlPrivateDownload string             `json:"url_private_download"`
	Permalink          string             `json:"permalink"`
	IsExternal         bool               `json:"is_external"`
	ExternalUrl        string             `json:"external_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]ListFilesRow, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesRow{}
	for rows.Next() {
		var i ListFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Mimetype,
			&i.Filetype,
			&i.Size,
			&i.UserID,
			&i.UrlPrivate,
			&i.UrlPrivateDownload,
			&i.Permalink,
			&i.IsExternal,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByChannel = `-- name: ListFilesByChannel :many
SELECT f.id, f.name, f.title, f.mimetype, f.filetype, f.size, f.user_id,
       f.url_private, f.url_private_download, f.permalink, f.is_external, f.external_url,
       f.created_at, f.updated_at
FROM files f
INNER JOIN file_channels fc ON f.id = fc.file_id
WHERE fc.channel_id = $1 AND f.id > $2
ORDER BY f.id ASC
LIMIT $3
`

type ListFilesByChannelParams struct {
	ChannelID string `json:"channel_id"`
	ID        string `json:"id"`
	Limit     int32  `json:"limit"`
}

type ListFilesByChannelRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Title              string             `json:"title"`
	Mimetype           string             `json:"mimetype"`
	Filetype           string             `json:"filetype"`
	Size               int64              `json:"size"`
	UserID             string             `json:"user_id"`
	UrlPrivate         string             `json:"url_private"`
	UrlPrivateDownload string             `json:"url_private_download"`
	Permalink          string             `json:"permalink"`
	IsExternal         bool               `json:"is_external"`
	ExternalUrl        string             `json:"external_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFilesByChannel(ctx context.Context, arg ListFilesByChannelParams) ([]ListFilesByChannelRow, error) {
	rows, err := q.db.Query(ctx, listFilesByChannel, arg.ChannelID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesByChannelRow{}
	for rows.Next() {
		var i ListFilesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Mimetype,
			&i.Filetype,
			&i.Size,
			&i.UserID,
			&i.UrlPrivate,
			&i.UrlPrivateDownload,
			&i.Permalink,
			&i.IsExternal,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByChannelAndUser = `-- name: ListFilesByChannelAndUser :many
SELECT f.id, f.name, f.title, f.mimetype, f.filetype, f.size, f.user_id,
       f.url_private, f.url_private_download, f.permalink, f.is_external, f.external_url,
       f.created_at, f.updated_at
FROM files f
INNER JOIN file_channels fc ON f.id = fc.file_id
WHERE fc.channel_id = $1 AND f.user_id = $2 AND f.id > $3
ORDER BY f.id ASC
LIMIT $4
`

type ListFilesByChannelAndUserParams struct {
	ChannelID string `json:"channel_id"`
	UserID    string `json:"user_id"`
	ID        string `json:"id"`
	Limit     int32  `json:"limit"`
}

type ListFilesByChannelAndUserRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Title              string             `json:"title"`
	Mimetype           string             `json:"mimetype"`
	Filetype           string             `json:"filetype"`
	Size               int64              `json:"size"`
	UserID             string             `json:"user_id"`
	UrlPrivate         string             `json:"url_private"`
	UrlPrivateDownload string             `json:"url_private_download"`
	Permalink          string             `json:"permalink"`
	IsExternal         bool               `json:"is_external"`
	ExternalUrl        string             `json:"external_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFilesByChannelAndUser(ctx context.Context, arg ListFilesByChannelAndUserParams) ([]ListFilesByChannelAndUserRow, error) {
	rows, err := q.db.Query(ctx, listFilesByChannelAndUser,
		arg.ChannelID,
		arg.UserID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesByChannelAndUserRow{}
	for rows.Next() {
		var i ListFilesByChannelAndUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Mimetype,
			&i.Filetype,
			&i.Size,
			&i.UserID,
			&i.UrlPrivate,
			&i.UrlPrivateDownload,
			&i.Permalink,
			&i.IsExternal,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByUser = `-- name: ListFilesByUser :many
SELECT id, name, title, mimetype, filetype, size, user_id,
       url_private, url_private_download, permalink, is_external, external_url,
       created_at, updated_at
FROM files
WHERE user_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListFilesByUserParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
	Limit  int32  `json:"limit"`
}

type ListFilesByUserRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Title              string             `json:"title"`
	Mimetype           string             `json:"mimetype"`
	Filetype           string             `json:"filetype"`
	Size               int64              `json:"size"`
	UserID             string             `json:"user_id"`
	UrlPrivate         string             `json:"url_private"`
	UrlPrivateDownload string             `json:"url_private_download"`
	Permalink          string             `json:"permalink"`
	IsExternal         bool               `json:"is_external"`
	ExternalUrl        string             `json:"external_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFilesByUser(ctx context.Context, arg ListFilesByUserParams) ([]ListFilesByUserRow, error) {
	rows, err := q.db.Query(ctx, listFilesByUser, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesByUserRow{}
	for rows.Next() {
		var i ListFilesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Mimetype,
			&i.Filetype,
			&i.Size,
			&i.UserID,
			&i.UrlPrivate,
			&i.UrlPrivateDownload,
			&i.Permalink,
			&i.IsExternal,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareFileToChannel = `-- name: ShareFileToChannel :exec
INSERT INTO file_channels (file_id, channel_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type ShareFileToChannelParams struct {
	FileID    string `json:"file_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) ShareFileToChannel(ctx context.Context, arg ShareFileToChannelParams) error {
	_, err := q.db.Exec(ctx, shareFileToChannel, arg.FileID, arg.ChannelID)
	return err
}

const updateFileComplete = `-- name: UpdateFileComplete :exec
UPDATE files SET title = $2, url_private = $3, url_private_download = $4,
                 permalink = $5, upload_complete = TRUE
WHERE id = $1
`

type UpdateFileCompleteParams struct {
	ID                 string `json:"id"`
	Title              string `json:"title"`
	UrlPrivate         string `json:"url_private"`
	UrlPrivateDownload string `json:"url_private_download"`
	Permalink          string `json:"permalink"`
}

func (q *Queries) UpdateFileComplete(ctx context.Context, arg UpdateFileCompleteParams) error {
	_, err := q.db.Exec(ctx, updateFileComplete,
		arg.ID,
		arg.Title,
		arg.UrlPrivate,
		arg.UrlPrivateDownload,
		arg.Permalink,
	)
	return err
}
