// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: internal_events.sql

package sqlcgen

import (
	"context"
)

const getInternalEventsByAggregate = `-- name: GetInternalEventsByAggregate :many
SELECT id, event_type, aggregate_type, aggregate_id, team_id, actor_id, payload, metadata, created_at
FROM internal_events
WHERE aggregate_type = $1 AND aggregate_id = $2
ORDER BY id ASC
`

type GetInternalEventsByAggregateParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
}

func (q *Queries) GetInternalEventsByAggregate(ctx context.Context, arg GetInternalEventsByAggregateParams) ([]InternalEvent, error) {
	rows, err := q.db.Query(ctx, getInternalEventsByAggregate, arg.AggregateType, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InternalEvent{}
	for rows.Next() {
		var i InternalEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.TeamID,
			&i.ActorID,
			&i.Payload,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInternalEventsByAggregateType = `-- name: GetInternalEventsByAggregateType :many
SELECT id, event_type, aggregate_type, aggregate_id, team_id, actor_id, payload, metadata, created_at
FROM internal_events
WHERE aggregate_type = $1
ORDER BY id ASC
`

func (q *Queries) GetInternalEventsByAggregateType(ctx context.Context, aggregateType string) ([]InternalEvent, error) {
	rows, err := q.db.Query(ctx, getInternalEventsByAggregateType, aggregateType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InternalEvent{}
	for rows.Next() {
		var i InternalEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.TeamID,
			&i.ActorID,
			&i.Payload,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInternalEventsSince = `-- name: GetInternalEventsSince :many
SELECT id, event_type, aggregate_type, aggregate_id, team_id, actor_id, payload, metadata, created_at
FROM internal_events
WHERE id > $1
ORDER BY id ASC
LIMIT $2
`

type GetInternalEventsSinceParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

func (q *Queries) GetInternalEventsSince(ctx context.Context, arg GetInternalEventsSinceParams) ([]InternalEvent, error) {
	rows, err := q.db.Query(ctx, getInternalEventsSince, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InternalEvent{}
	for rows.Next() {
		var i InternalEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.TeamID,
			&i.ActorID,
			&i.Payload,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInternalEvent = `-- name: InsertInternalEvent :one
INSERT INTO internal_events (event_type, aggregate_type, aggregate_id, team_id, actor_id, payload, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_type, aggregate_type, aggregate_id, team_id, actor_id, payload, metadata, created_at
`

type InsertInternalEventParams struct {
	EventType     string `json:"event_type"`
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	TeamID        string `json:"team_id"`
	ActorID       string `json:"actor_id"`
	Payload       []byte `json:"payload"`
	Metadata      []byte `json:"metadata"`
}

func (q *Queries) InsertInternalEvent(ctx context.Context, arg InsertInternalEventParams) (InternalEvent, error) {
	row := q.db.QueryRow(ctx, insertInternalEvent,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.TeamID,
		arg.ActorID,
		arg.Payload,
		arg.Metadata,
	)
	var i InternalEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.TeamID,
		&i.ActorID,
		&i.Payload,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
