// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, event_id, subscription_id, url, payload, secret, status, attempts, max_attempts, next_attempt_at, last_error, delivered_at, created_at
FROM outbox
WHERE status = 'pending' AND next_attempt_at <= NOW()
ORDER BY next_attempt_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Url,
			&i.Payload,
			&i.Secret,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupDeliveredOutbox = `-- name: CleanupDeliveredOutbox :execresult
DELETE FROM outbox
WHERE status = 'delivered' AND created_at < $1
`

func (q *Queries) CleanupDeliveredOutbox(ctx context.Context, createdAt pgtype.Timestamptz) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cleanupDeliveredOutbox, createdAt)
}

const getMatchingSubscriptions = `-- name: GetMatchingSubscriptions :many
SELECT id, team_id, url, event_types, secret, encrypted_secret, enabled, created_at, updated_at
FROM event_subscriptions
WHERE team_id = $1 AND enabled = TRUE AND $2::TEXT = ANY(event_types)
`

type GetMatchingSubscriptionsParams struct {
	TeamID  string `json:"team_id"`
	Column2 string `json:"column_2"`
}

type GetMatchingSubscriptionsRow struct {
	ID              string             `json:"id"`
	TeamID          string             `json:"team_id"`
	Url             string             `json:"url"`
	EventTypes      []string           `json:"event_types"`
	Secret          string             `json:"secret"`
	EncryptedSecret string             `json:"encrypted_secret"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMatchingSubscriptions(ctx context.Context, arg GetMatchingSubscriptionsParams) ([]GetMatchingSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getMatchingSubscriptions, arg.TeamID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchingSubscriptionsRow{}
	for rows.Next() {
		var i GetMatchingSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Url,
			&i.EventTypes,
			&i.Secret,
			&i.EncryptedSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEntry = `-- name: InsertOutboxEntry :exec
INSERT INTO outbox (event_id, subscription_id, url, payload, secret, status, max_attempts, next_attempt_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, NOW())
`

type InsertOutboxEntryParams struct {
	EventID        int64  `json:"event_id"`
	SubscriptionID string `json:"subscription_id"`
	Url            string `json:"url"`
	Payload        []byte `json:"payload"`
	Secret         string `json:"secret"`
	MaxAttempts    int32  `json:"max_attempts"`
}

func (q *Queries) InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEntry,
		arg.EventID,
		arg.SubscriptionID,
		arg.Url,
		arg.Payload,
		arg.Secret,
		arg.MaxAttempts,
	)
	return err
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE outbox
SET status = 'delivered', delivered_at = NOW(), attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) MarkOutboxDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxDelivered, id)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET status = 'failed', last_error = $2, attempts = attempts + 1
WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        int64  `json:"id"`
	LastError string `json:"last_error"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const scheduleOutboxRetry = `-- name: ScheduleOutboxRetry :exec
UPDATE outbox
SET next_attempt_at = $2, last_error = $3, attempts = attempts + 1
WHERE id = $1
`

type ScheduleOutboxRetryParams struct {
	ID            int64              `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     string             `json:"last_error"`
}

func (q *Queries) ScheduleOutboxRetry(ctx context.Context, arg ScheduleOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, scheduleOutboxRetry, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}
