package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	sourcePath := flag.String("source", "", "path to Go source file containing permission constants")
	outPath := flag.String("out", "", "path to generated TypeScript file")
	flag.Parse()

	if *sourcePath == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "usage: generate-permissions-ts -source <go-file> -out <ts-file>")
		os.Exit(2)
	}

	values, err := extractPermissionValues(*sourcePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "extract permissions: %v\n", err)
		os.Exit(1)
	}
	if len(values) == 0 {
		fmt.Fprintln(os.Stderr, "no permissions found")
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir output dir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outPath, []byte(renderTS(values)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
}

func extractPermissionValues(sourcePath string) ([]string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, sourcePath, nil, 0)
	if err != nil {
		return nil, err
	}

	values := make([]string, 0)
	seen := make(map[string]struct{})

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Values) != 1 {
				continue
			}
			lit, ok := valueSpec.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				continue
			}
			value, err := strconv.Unquote(lit.Value)
			if err != nil {
				return nil, err
			}
			for _, name := range valueSpec.Names {
				if !strings.HasPrefix(name.Name, "Permission") {
					continue
				}
				if _, ok := seen[value]; ok {
					continue
				}
				seen[value] = struct{}{}
				values = append(values, value)
			}
		}
	}

	return values, nil
}

func renderTS(values []string) string {
	var b strings.Builder

	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	b.WriteString("// Source: server/internal/domain/permissions.go\n\n")
	b.WriteString("export const permissionOptions = [\n")
	for _, value := range values {
		quoted := strconv.Quote(value)
		b.WriteString("  { value: ")
		b.WriteString(quoted)
		b.WriteString(", label: ")
		b.WriteString(quoted)
		b.WriteString(" },\n")
	}
	b.WriteString("] as const\n\n")
	b.WriteString("export type PermissionValue = (typeof permissionOptions)[number]['value']\n")

	return b.String()
}
