/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

export interface AddParticipantsRequest {
  /** Users to add to the conversation. */
  user_ids: string[];
}
