/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { AgentAPIKeyScopeType } from './agentAPIKeyScopeType';

export interface AgentAPIKey {
  /** Agent API key identifier. */
  id: string;
  /** Raw bearer token for the agent. It is returned because agent keys are treated as one rotatable current credential. */
  token: string;
  /** Whether the agent key is user-scoped or workspace-scoped. */
  scope_type: AgentAPIKeyScopeType;
  /**
     * Workspace bound to the key when scope_type is workspace.
     * @nullable
     */
  scope_workspace_id?: string | null;
  /** Creation time. */
  created_at: string;
}
