/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Whether the agent key is user-scoped or workspace-scoped.
 */
export type AgentAPIKeyScopeType = typeof AgentAPIKeyScopeType[keyof typeof AgentAPIKeyScopeType];


export const AgentAPIKeyScopeType = {
  user: 'user',
  workspace: 'workspace',
} as const;
