/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * An API key used to authenticate requests. Keys are either account-scoped or workspace-system-scoped.
 */
export interface APIKey {
  /** Unique API key identifier. */
  id: string;
  /** Human-readable name for this key. */
  name: string;
  /** Optional longer description of the key's purpose. */
  description?: string;
  /** SHA-256 hash of the secret (never returned in list responses). */
  key_hash?: string;
  /** First characters of the key for identification (e.g. "tsk_abc"). */
  key_prefix: string;
  /** Masked version of the key shown in the UI (e.g. "tsk_abc...xyz"). */
  key_hint: string;
  scope: 'account' | 'workspace_system';
  /** Workspace this key is pinned to when `scope` is `workspace_system`. */
  workspace_id?: string;
  /** Account that owns this key when `scope` is `account`. */
  account_id?: string;
  /** Optional workspace allowlist for account-scoped keys. Empty means all workspaces where the account has a user. */
  workspace_ids?: string[];
  /** Workspace user who created this key. */
  created_by: string;
  /** List of permission strings granted to this key. */
  permissions: string[];
  /** When this key expires. Null means no expiration. */
  expires_at?: string;
  /** Timestamp of the most recent authenticated request using this key. */
  last_used_at?: string;
  /** Total number of requests made with this key. */
  request_count: number;
  /** Whether this key has been revoked. */
  revoked: boolean;
  /** When this key was revoked. */
  revoked_at?: string;
  /** If this key was rotated, the ID of the replacement key. */
  rotated_to_id?: string;
  /** During rotation, the old key remains valid until this time. */
  grace_period_ends_at?: string;
  created_at: string;
  updated_at: string;
}
