/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { AccountType } from './accountType';
import type { PrincipalType } from './principalType';
import type { User } from './user';

/**
 * The authenticated identity of the current request.
 */
export interface AuthMeResponse {
  /** Workspace the caller is authenticated in. */
  workspace_id: string;
  /** Canonical account identity of the caller. */
  account_id?: string;
  /** Workspace membership identity of the caller when the caller is a member. */
  membership_id?: string;
  /** Compatibility workspace-local user identity of the caller when materialized. */
  user_id?: string;
  principal_type: PrincipalType;
  account_type?: AccountType;
  /** Whether the caller is a bot/agent. */
  is_bot: boolean;
  /** Effective permissions granted to the caller for this request context. */
  permissions?: string[];
  /** OAuth scopes associated with the current request when applicable. */
  scopes?: string[];
  user?: User;
}
