/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { SessionEnvelope } from './sessionEnvelope';
import type { User } from './user';

export interface AuthResponse {
  session: SessionEnvelope;
  user: User;
}
