/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A saved link in a conversation's bookmark bar.
 */
export interface Bookmark {
  /** Unique bookmark identifier. */
  id: string;
  /** Conversation this bookmark belongs to. */
  channel_id: string;
  /** Display title for the bookmark. */
  title: string;
  /** Bookmark type (e.g. "link"). */
  type: string;
  /** URL the bookmark points to. */
  link: string;
  /** Optional emoji icon displayed next to the title. */
  emoji?: string;
  /** User who created the bookmark. */
  created_by: string;
  /** User who last updated the bookmark. */
  updated_by: string;
  created_at: string;
  updated_at: string;
}
