/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface CompleteUploadRequest {
  /** File identifier returned from the upload URL request. */
  file_id?: string;
  /** Display title for the file. */
  title?: string;
  /** Conversation to share the file in after upload. */
  channel_id?: string;
  /** Thread to share the file in (if sharing in a thread). */
  thread_ts?: string;
}
