/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Who is allowed to post messages in a conversation.
 */
export type ConversationPostingPolicyType = typeof ConversationPostingPolicyType[keyof typeof ConversationPostingPolicyType];


export const ConversationPostingPolicyType = {
  everyone: 'everyone',
  admins_only: 'admins_only',
  members_with_permission: 'members_with_permission',
  custom: 'custom',
} as const;
