/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface ConversationManagersResponse {
  /** Conversation identifier. */
  conversation_id: string;
  /** Account IDs who are managers of this conversation. Canonical for account-owned conversations. */
  account_ids?: string[];
}
