/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface ConversationInviteRequest {
  /** User IDs to add as members. */
  user_ids: string[];
}
