/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface ConversationManagersUpdateRequest {
  /** Complete list of manager account IDs (replaces existing managers). Canonical for account-owned conversations. */
  account_ids?: string[];
}
