/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { FreeFormObject } from './freeFormObject';
import type { WorkspaceBilling } from './workspaceBilling';
import type { WorkspaceDiscoverability } from './workspaceDiscoverability';
import type { WorkspaceIcon } from './workspaceIcon';
import type { WorkspaceProfileField } from './workspaceProfileField';

export interface CreateWorkspaceRequest {
  /** Display name of the workspace. */
  name: string;
  /** Unique URL-safe slug (e.g. "acme-corp"). */
  domain: string;
  /** Email domain for auto-joining (e.g. "acme.com"). */
  email_domain: string;
  /** Short description of the workspace. */
  description: string;
  icon: WorkspaceIcon;
  discoverability: WorkspaceDiscoverability;
  /** Conversation IDs new members are automatically added to. */
  default_channels: string[];
  preferences: FreeFormObject;
  /** Custom profile fields for workspace members. */
  profile_fields: WorkspaceProfileField[];
  billing: WorkspaceBilling;
}
