/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { AccountType } from './accountType';
import type { PrincipalType } from './principalType';
import type { UserProfile } from './userProfile';

export interface CreateUserRequest {
  /** Workspace to create the user in. */
  workspace_id: string;
  /** Unique username within the workspace. */
  name: string;
  /** Full name. */
  real_name: string;
  /** Name shown in the UI. */
  display_name: string;
  /** Email address. */
  email: string;
  principal_type: PrincipalType;
  account_type?: AccountType;
  /** For agent users, the human user who owns this agent. */
  owner_id?: string;
  /** Set to true for bot/agent identities. */
  is_bot: boolean;
  profile: UserProfile;
}
