/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { EventResourceType } from './eventResourceType';

export interface CreateEventSubscriptionRequest {
  /**
     * Workspace scope for the subscription. Omit for globally visible events.
     * @nullable
     */
  workspace_id?: string | null;
  /** Webhook delivery URL. */
  url: string;
  /**
     * Optional event type filter.
     * @nullable
     */
  event_type?: string | null;
  /** Optional resource type filter. */
  resource_type?: EventResourceType | null;
  /**
     * Optional resource id filter. Requires resource_type.
     * @nullable
     */
  resource_id?: string | null;
  /** Shared signing secret used for webhook signatures. Must not be blank. */
  secret: string;
}
