/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateConversationInviteRequestMode } from './createConversationInviteRequestMode';

export interface CreateConversationInviteRequest {
  /**
     * Optional invite expiration time.
     * @nullable
     */
  expires_at?: string | null;
  /** Link invites can be accepted by any eligible caller; restricted invites require allowed users or emails. */
  mode: CreateConversationInviteRequestMode;
  /** Allowed user ids for restricted invites. */
  allowed_user_ids?: string[];
  /** Allowed email addresses for restricted invites. */
  allowed_emails?: string[];
}
