/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceInvite } from './workspaceInvite';

export interface CreateWorkspaceInviteResponse {
  invite: WorkspaceInvite;
  /** Raw invite code that can be accepted through the API. */
  code: string;
  /** Login URL carrying the invite code. */
  invite_url: string;
}
