/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter events to a specific resource type.
 */
export type CreateEventSubscriptionRequestResourceType = typeof CreateEventSubscriptionRequestResourceType[keyof typeof CreateEventSubscriptionRequestResourceType];


export const CreateEventSubscriptionRequestResourceType = {
  workspace: 'workspace',
  user: 'user',
  conversation: 'conversation',
  file: 'file',
} as const;
