/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Visibility policy for the conversation. Defaults to members when omitted.
 */
export type CreateConversationRequestAccessPolicy = typeof CreateConversationRequestAccessPolicy[keyof typeof CreateConversationRequestAccessPolicy];


export const CreateConversationRequestAccessPolicy = {
  members: 'members',
  workspace: 'workspace',
} as const;
