/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { APIKey } from './aPIKey';

export interface CreateAPIKeyResponse {
  api_key: APIKey;
  /** Plaintext API key secret. It is returned only once. */
  secret: string;
}
