/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Initial write mode for the agent. Defaults to safe_write when omitted.
 */
export type CreateAgentRequestMode = typeof CreateAgentRequestMode[keyof typeof CreateAgentRequestMode];


export const CreateAgentRequestMode = {
  read_only: 'read_only',
  safe_write: 'safe_write',
} as const;
