/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Opaque pagination cursor returned as next_cursor by a previous page.
 */
export type CursorQueryParameter = string;
