/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardEndpointStat {
  method: string;
  path: string;
  requests: number;
  success_rate: number;
  avg_duration_ms: number;
  p95_duration_ms: number;
  /** @nullable */
  last_seen_at?: string | null;
}
