/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardAPIKeySummary {
  total: number;
  active: number;
  revoked: number;
  expiring_soon: number;
  stale: number;
  /** @nullable */
  last_used_at?: string | null;
}
