/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardScope } from './dashboardScope';
import type { DashboardWebhookDelivery } from './dashboardWebhookDelivery';
import type { DashboardWebhookSubscription } from './dashboardWebhookSubscription';
import type { DashboardWebhookSummary } from './dashboardWebhookSummary';

export interface DashboardWebhooksResponse {
  scope: DashboardScope;
  summary: DashboardWebhookSummary;
  subscriptions: DashboardWebhookSubscription[];
  recent_deliveries: DashboardWebhookDelivery[];
}
