/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Fine-grained administrative role that can be granted to a user.
 */
export type DelegatedRole = typeof DelegatedRole[keyof typeof DelegatedRole];


export const DelegatedRole = {
  channels_admin: 'channels_admin',
  roles_admin: 'roles_admin',
  security_admin: 'security_admin',
  integrations_admin: 'integrations_admin',
  support_readonly: 'support_readonly',
} as const;
