/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationDetail } from './validationDetail';

export interface ErrorResponse {
  /** Stable machine-readable error code. */
  code: string;
  /** Human-readable error message. */
  message: string;
  /** Request identifier for server-side troubleshooting. */
  request_id?: string;
  /** Field-level validation details when request validation fails. */
  errors?: ValidationDetail[];
}
