/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * New resource type filter.
 */
export type EventSubscriptionUpdateRequestResourceType = typeof EventSubscriptionUpdateRequestResourceType[keyof typeof EventSubscriptionUpdateRequestResourceType];


export const EventSubscriptionUpdateRequestResourceType = {
  workspace: 'workspace',
  user: 'user',
  conversation: 'conversation',
  file: 'file',
  usergroup: 'usergroup',
} as const;
