/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { ExternalEvent } from './externalEvent';

export interface ExternalEventsCollection {
  items: ExternalEvent[];
  /** Pagination cursor when additional results are available. */
  next_cursor?: string;
}
