/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalEvent } from './externalEvent';

export interface ExternalEventsCollection {
  items: ExternalEvent[];
  next_cursor?: string;
  has_more: boolean;
}
