/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { Account } from './account';
import type { ExternalPrincipalAccessMode } from './externalPrincipalAccessMode';

export interface ExternalMember {
  id: string;
  conversation_id: string;
  host_workspace_id: string;
  external_workspace_id: string;
  account_id: string;
  access_mode: ExternalPrincipalAccessMode;
  allowed_capabilities?: string[];
  invited_by: string;
  created_at: string;
  expires_at?: string;
  revoked_at?: string;
  account?: Account;
}
