/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalMember } from './externalMember';

export interface ExternalMembersCollection {
  items: ExternalMember[];
  next_cursor?: string;
}
