/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of resource that produced the event.
 */
export type ExternalEventResourceType = typeof ExternalEventResourceType[keyof typeof ExternalEventResourceType];


export const ExternalEventResourceType = {
  workspace: 'workspace',
  user: 'user',
  conversation: 'conversation',
  file: 'file',
  usergroup: 'usergroup',
} as const;
