/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Level of access granted to an external principal.
 */
export type ExternalPrincipalAccessMode = typeof ExternalPrincipalAccessMode[keyof typeof ExternalPrincipalAccessMode];


export const ExternalPrincipalAccessMode = {
  external_shared: 'external_shared',
  external_shared_readonly: 'external_shared_readonly',
} as const;
