/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalPrincipalAccessMode } from './externalPrincipalAccessMode';
import type { PrincipalType } from './principalType';

/**
 * An access grant allowing an external principal to participate in a host workspace.
 */
export interface ExternalPrincipalAccess {
  /** Unique access grant identifier. */
  id: string;
  /** Workspace granting access. */
  host_workspace_id: string;
  /** External user or agent being granted access. */
  principal_id: string;
  principal_type: PrincipalType;
  /** Workspace the principal belongs to. */
  home_workspace_id: string;
  access_mode: ExternalPrincipalAccessMode;
  /** Specific capabilities granted (e.g. "read", "write"). */
  allowed_capabilities?: string[];
  /** Conversations the principal can access. Empty means all conversations. */
  conversation_ids?: string[];
  /** User who granted the access. */
  granted_by: string;
  created_at: string;
  /** When the access grant expires. */
  expires_at?: string;
  /** When the access was revoked. */
  revoked_at?: string;
}
