/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A single field-level validation error.
 */
export interface FieldError {
  /** JSON path of the invalid field (e.g. "name"). */
  field: string;
  /** Machine-readable validation code (e.g. "required", "too_long"). */
  code: string;
  /** Human-readable explanation of the validation failure. */
  message: string;
}
