/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { LimitQueryParameter } from './limitQueryParameter';
import type { WorkspaceIDQueryParameter } from './workspaceIDQueryParameter';

export type GetDashboardAuditParams = {
/**
 * Restrict the request to one workspace.
 */
workspace_id?: WorkspaceIDQueryParameter;
/**
 * Maximum number of items to return. Use the next_cursor from the response to continue paging.
 * @minimum 1
 * @maximum 200
 */
limit?: LimitQueryParameter;
};
