/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Service health status.
 */
export type HealthStatusResponseStatus = typeof HealthStatusResponseStatus[keyof typeof HealthStatusResponseStatus];


export const HealthStatusResponseStatus = {
  ok: 'ok',
} as const;
