/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { CursorQueryParameter } from './cursorQueryParameter';
import type { LimitQueryParameter } from './limitQueryParameter';

export type ListConversationMembersParams = {
/**
 * Opaque pagination cursor returned by a previous request.
 */
cursor?: CursorQueryParameter;
/**
 * Maximum number of items to return per page.
 * @minimum 0
 */
limit?: LimitQueryParameter;
};
