/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { CursorQueryParameter } from './cursorQueryParameter';
import type { LimitQueryParameter } from './limitQueryParameter';
import type { WorkspaceIDQueryParameter } from './workspaceIDQueryParameter';

export type ListApiKeysParams = {
/**
 * Filter results by workspace identifier.
 */
workspace_id?: WorkspaceIDQueryParameter;
/**
 * Filter account-scoped API keys owned by this account.
 */
account_id?: string;
/**
 * Filter keys to a single scope.
 */
scope?: 'account' | 'workspace_system';
/**
 * When true, include revoked API keys in results.
 */
include_revoked?: boolean;
/**
 * Opaque pagination cursor returned by a previous request.
 */
cursor?: CursorQueryParameter;
/**
 * Maximum number of items to return per page.
 * @minimum 0
 */
limit?: LimitQueryParameter;
};
