/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { BeforeMessageIDQueryParameter } from './beforeMessageIDQueryParameter';
import type { CursorQueryParameter } from './cursorQueryParameter';
import type { LimitQueryParameter } from './limitQueryParameter';

export type ListMessagesParams = {
/**
 * Maximum number of items to return per page.
 * @minimum 1
 * @maximum 200
 */
limit?: LimitQueryParameter;
/**
 * Pagination cursor from a previous response.
 */
cursor?: CursorQueryParameter;
/**
 * Only return messages created before the referenced message.
 */
before_message_id?: BeforeMessageIDQueryParameter;
};
