/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { CursorQueryParameter } from './cursorQueryParameter';
import type { EventResourceIDQueryParameter } from './eventResourceIDQueryParameter';
import type { EventResourceType } from './eventResourceType';
import type { EventResourceTypeQueryParameter } from './eventResourceTypeQueryParameter';
import type { EventTypeQueryParameter } from './eventTypeQueryParameter';
import type { LimitQueryParameter } from './limitQueryParameter';
import type { WorkspaceIDQueryParameter } from './workspaceIDQueryParameter';

export type ListEventsParams = {
/**
 * Maximum number of items to return per page.
 * @minimum 1
 * @maximum 200
 */
limit?: LimitQueryParameter;
/**
 * Pagination cursor from a previous response.
 */
cursor?: CursorQueryParameter;
/**
 * Only include one event type.
 */
type?: EventTypeQueryParameter;
/**
 * Public resource scope for external events. Message events are conversation-scoped.
 */
resource_type?: EventResourceTypeQueryParameter;
/**
 * Only include one resource id. Requires resource_type.
 */
resource_id?: EventResourceIDQueryParameter;
/**
 * Only include results from one workspace.
 */
workspace_id?: WorkspaceIDQueryParameter;
};
