/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { AccessPolicyQueryParameter } from './accessPolicyQueryParameter';
import type { CursorQueryParameter } from './cursorQueryParameter';
import type { LimitQueryParameter } from './limitQueryParameter';
import type { WorkspaceIDQueryParameter } from './workspaceIDQueryParameter';

export type ListConversationsParams = {
/**
 * Only include results from one workspace.
 */
workspace_id?: WorkspaceIDQueryParameter;
/**
 * Maximum number of items to return per page.
 * @minimum 1
 * @maximum 200
 */
limit?: LimitQueryParameter;
/**
 * Pagination cursor from a previous response.
 */
cursor?: CursorQueryParameter;
/**
 * Only include conversations with one access policy.
 */
access_policy?: AccessPolicyQueryParameter;
};
