/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { User } from './user';
import type { WorkspaceMembershipSummary } from './workspaceMembershipSummary';

export interface MeResponse {
  user: User;
  /** Workspace memberships visible to the caller. */
  workspaces: WorkspaceMembershipSummary[];
}
