/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { FreeFormJSON } from './freeFormJSON';
import type { Reaction } from './reaction';

/**
 * A single message within a conversation.
 */
export interface Message {
  /** Message timestamp — the unique identifier for this message within its conversation. */
  ts: string;
  /** Conversation this message belongs to. */
  channel_id: string;
  /** User who sent the message. */
  user_id: string;
  /** Canonical account that authored the message. */
  author_account_id: string;
  /** Workspace membership used for workspace-local rendering, when applicable. */
  author_workspace_membership_id?: string;
  /** Plain-text content of the message. */
  text: string;
  /** If this message is a reply, the timestamp of the parent message. */
  thread_ts?: string;
  /** Message type (typically "message"). */
  type: string;
  /** Message subtype for system messages (e.g. "channel_join", "channel_topic"). */
  subtype?: string;
  /** Rich-text block layout (Block Kit format). */
  blocks?: FreeFormJSON;
  /** Arbitrary key-value metadata attached to the message. */
  metadata?: FreeFormJSON;
  /** User who last edited the message. */
  edited_by?: string;
  /** Timestamp of the last edit. */
  edited_at?: string;
  /** Emoji reactions on this message. */
  reactions?: Reaction[];
  /** Total number of replies in the thread (0 if not a thread parent). */
  reply_count: number;
  /** Number of distinct users who have replied in the thread. */
  reply_users_count: number;
  /** Timestamp of the most recent reply in the thread. */
  latest_reply?: string;
  /** Whether this message has been soft-deleted. */
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
}
