/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

export interface OAuthStartResponse {
  /** Provider authorization URL to open in the browser. */
  auth_url: string;
  /** OAuth state value associated with the authorization request. */
  state: string;
}
