/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { FreeFormJSON } from './freeFormJSON';

export interface PostMessageRequest {
  /** Conversation to post the message in. */
  channel_id: string;
  /** User sending the message. */
  user_id: string;
  /** Canonical author account. Defaults to the authenticated account. */
  author_account_id?: string;
  /** Plain-text content of the message. */
  text: string;
  /** Parent message timestamp to reply in a thread. */
  thread_ts?: string;
  /** Rich-text block layout (Block Kit format). */
  blocks?: FreeFormJSON;
  /** Arbitrary key-value metadata to attach to the message. */
  metadata?: FreeFormJSON;
  /** When true, also post the reply to the channel (not just the thread). */
  reply_broadcast?: boolean;
}
