/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The kind of identity: human user, AI agent, or system service.
 */
export type PrincipalType = typeof PrincipalType[keyof typeof PrincipalType];


export const PrincipalType = {
  human: 'human',
  agent: 'agent',
  system: 'system',
} as const;
