/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * An emoji reaction on a message.
 */
export interface Reaction {
  /** Emoji name (e.g. "thumbsup", "heart"). */
  name: string;
  /** User IDs who added this reaction. */
  users: string[];
  /** Total number of users who added this reaction. */
  count: number;
}
