/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface SearchRequest {
  /** Workspace to search within. */
  workspace_id: string;
  /** Free-text search query. */
  query: string;
  /** Restrict results to specific resource types (e.g. ["message", "user"]). */
  types?: string[];
  /** Maximum number of results to return. */
  limit?: number;
  /** Pagination cursor from a previous search response. */
  cursor?: string;
}
