/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

export type SearchRequestKindsItem = typeof SearchRequestKindsItem[keyof typeof SearchRequestKindsItem];


export const SearchRequestKindsItem = {
  message: 'message',
  conversation: 'conversation',
  workspace: 'workspace',
  user: 'user',
  event: 'event',
} as const;
