/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface ShareRemoteFileRequest {
  /** File identifier to share. */
  file_id?: string;
  /** Conversation IDs to share the file in. */
  channels: string[];
}
