/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * User identifier whose API keys should be listed. Defaults to the current user.
 */
export type SubjectUserIDQueryParameter = string;
