/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Fields to update on the authenticated caller's profile.
 */
export interface UpdateProfileRequest {
  /** New public handle. Empty values are rejected. */
  handle?: string;
  /** New display name. Blank values clear the field server-side only when supported. */
  display_name?: string;
  /**
     * New avatar URL or null to clear it.
     * @nullable
     */
  avatar_url?: string | null;
  /**
     * New bio or null to clear it.
     * @nullable
     */
  bio?: string | null;
}
