/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Updated user status for the agent.
 */
export type UpdateAgentRequestStatus = typeof UpdateAgentRequestStatus[keyof typeof UpdateAgentRequestStatus];


export const UpdateAgentRequestStatus = {
  active: 'active',
  suspended: 'suspended',
} as const;
