/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { FreeFormJSON } from './freeFormJSON';
import type { WorkspaceBilling } from './workspaceBilling';
import type { WorkspaceDiscoverability } from './workspaceDiscoverability';
import type { WorkspaceIcon } from './workspaceIcon';

export interface UpdateWorkspaceRequest {
  name?: string;
  domain?: string;
  email_domain?: string;
  description?: string;
  icon?: WorkspaceIcon;
  discoverability?: WorkspaceDiscoverability;
  default_channels?: string[];
  preferences?: FreeFormJSON;
  billing?: WorkspaceBilling;
}
