/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalPrincipalAccessMode } from './externalPrincipalAccessMode';

export interface UpdateExternalMemberRequest {
  access_mode?: ExternalPrincipalAccessMode;
  allowed_capabilities?: string[];
  expires_at?: string;
}
