/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAPIKeyRequest {
  /** New name. */
  name?: string;
  /** New description. */
  description?: string;
  /** New permission set (replaces existing permissions entirely). */
  permissions?: string[];
  /** Optional replacement allowlist for account-scoped keys. Empty means all eligible workspaces. */
  workspace_ids?: string[];
}
