/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import type { FreeFormJSON } from './freeFormJSON';

export interface UpdateMessageRequest {
  /** New plain-text content. */
  text?: string;
  /** New rich-text block layout. */
  blocks?: FreeFormJSON;
  /** New metadata (replaces existing metadata entirely). */
  metadata?: FreeFormJSON;
}
