/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateConversationRequest {
  /**
     * New conversation title.
     * @nullable
     */
  title?: string | null;
  /**
     * New conversation description.
     * @nullable
     */
  description?: string | null;
  /**
     * Whether to archive or unarchive the conversation.
     * @nullable
     */
  archived?: boolean | null;
}
