/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateReadStateRequest {
  /** Message id to mark as the caller's last read message. */
  last_read_message_id: string;
}
