/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * New workspace role.
 */
export type UpdateWorkspaceMemberRequestRole = typeof UpdateWorkspaceMemberRequestRole[keyof typeof UpdateWorkspaceMemberRequestRole];


export const UpdateWorkspaceMemberRequestRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;
