/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { UserMetadata } from './userMetadata';
import type { UserProfile } from './userProfile';

export interface User {
  /** User identifier. */
  id: string;
  /** Principal type for the user record. */
  principal_type: string;
  /** User status. */
  status: string;
  /**
     * Primary email address when available.
     * @nullable
     */
  email?: string | null;
  /**
     * Optional agent metadata when the user record is backed by an agent principal.
     * @nullable
     */
  metadata?: UserMetadata;
  profile: UserProfile;
}
