/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A named group of users that can be @-mentioned together.
 */
export interface Usergroup {
  /** Unique usergroup identifier. */
  id: string;
  /** Workspace this usergroup belongs to. */
  workspace_id: string;
  /** Display name of the usergroup. */
  name: string;
  /** Short handle used for @-mentions (e.g. "engineering"). */
  handle: string;
  /** Description of the usergroup's purpose. */
  description: string;
  /** Whether this usergroup includes external members. */
  is_external: boolean;
  /** Whether this usergroup is active. */
  enabled: boolean;
  /** Number of members in the usergroup. */
  user_count: number;
  /** User who created the usergroup. */
  created_by: string;
  /** User who last updated the usergroup. */
  updated_by: string;
  created_at: string;
  updated_at: string;
}
