/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

export interface UsergroupUpdateRequest {
  /** New display name. */
  name?: string;
  /** New @-mention handle. */
  handle?: string;
  /** New description. */
  description?: string;
  /** Set to false to disable the usergroup. */
  enabled?: boolean;
  /** User making the update. */
  updated_by?: string;
}
