/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Whether the workspace can be discovered and joined without an invite.
 */
export type WorkspaceDiscoverability = typeof WorkspaceDiscoverability[keyof typeof WorkspaceDiscoverability];


export const WorkspaceDiscoverability = {
  open: 'open',
  invite_only: 'invite_only',
} as const;
