/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import type { User } from './user';
import type { WorkspaceMemberRole } from './workspaceMemberRole';
import type { WorkspaceMemberStatus } from './workspaceMemberStatus';

export interface WorkspaceMember {
  /** Workspace identifier. */
  workspace_id: string;
  /** User identifier. */
  user_id: string;
  /** Role held in the workspace. */
  role: WorkspaceMemberRole;
  /** Membership status. */
  status: WorkspaceMemberStatus;
  user: User;
}
