/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Role held in the workspace.
 */
export type WorkspaceMemberRole = typeof WorkspaceMemberRole[keyof typeof WorkspaceMemberRole];


export const WorkspaceMemberRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;
