/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseResponse
} from '../model';

import { orvalFetch } from '../../orval-mutator';
import type { ErrorType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Placeholder endpoint. Search is currently disabled and always returns not implemented.
 * @summary Search is not implemented
 */
export type runSearchResponse501 = {
  data: ApiErrorResponseResponse
  status: 501
}

;
export type runSearchResponseError = (runSearchResponse501) & {
  headers: Headers;
};

export type runSearchResponse = (runSearchResponseError)

export const getRunSearchUrl = () => {




  return `/search`
}

export const runSearch = async ( options?: RequestInit): Promise<runSearchResponse> => {

  return orvalFetch<runSearchResponse>(getRunSearchUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getRunSearchMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSearch>>, TError,void, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof runSearch>>, TError,void, TContext> => {

const mutationKey = ['runSearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runSearch>>, void> = () => {


          return  runSearch(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RunSearchMutationResult = NonNullable<Awaited<ReturnType<typeof runSearch>>>

    export type RunSearchMutationError = ErrorType<ApiErrorResponseResponse>

    /**
 * @summary Search is not implemented
 */
export const useRunSearch = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSearch>>, TError,void, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runSearch>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRunSearchMutationOptions(options), queryClient);
    }
