// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertInternalEvent = `-- name: InsertInternalEvent :one
insert into internal_events (
  event_type,
  aggregate_type,
  aggregate_id,
  workspace_id,
  actor_user_id,
  shard_id,
  payload,
  created_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
returning id
`

type InsertInternalEventParams struct {
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	WorkspaceID   *uuid.UUID         `json:"workspace_id"`
	ActorUserID   *uuid.UUID         `json:"actor_user_id"`
	ShardID       int32              `json:"shard_id"`
	Payload       json.RawMessage    `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertInternalEvent(ctx context.Context, arg InsertInternalEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertInternalEvent,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.ShardID,
		arg.Payload,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
