// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messaging_handlers.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationParticipants = `-- name: CountConversationParticipants :one
select count(*)::int as count
from conversation_participants
where conversation_id = $1
`

func (q *Queries) CountConversationParticipants(ctx context.Context, conversationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countConversationParticipants, conversationID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :exec
insert into conversations (
  id,
  workspace_id,
  access_policy,
  title,
  description,
  created_by_user_id,
  created_at,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
`

type CreateConversationParams struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     *uuid.UUID         `json:"workspace_id"`
	AccessPolicy    string             `json:"access_policy"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.Exec(ctx, createConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.AccessPolicy,
		arg.Title,
		arg.Description,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createConversationInvite = `-- name: CreateConversationInvite :exec
insert into conversation_invites (
  id,
  conversation_id,
  created_by_user_id,
  token_hash,
  encrypted_token,
  expires_at,
  mode,
  allowed_user_ids,
  allowed_emails,
  created_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
`

type CreateConversationInviteParams struct {
	ID              uuid.UUID          `json:"id"`
	ConversationID  uuid.UUID          `json:"conversation_id"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	TokenHash       string             `json:"token_hash"`
	EncryptedToken  *string            `json:"encrypted_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Mode            string             `json:"mode"`
	AllowedUserIds  *json.RawMessage   `json:"allowed_user_ids"`
	AllowedEmails   *json.RawMessage   `json:"allowed_emails"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateConversationInvite(ctx context.Context, arg CreateConversationInviteParams) error {
	_, err := q.db.Exec(ctx, createConversationInvite,
		arg.ID,
		arg.ConversationID,
		arg.CreatedByUserID,
		arg.TokenHash,
		arg.EncryptedToken,
		arg.ExpiresAt,
		arg.Mode,
		arg.AllowedUserIds,
		arg.AllowedEmails,
		arg.CreatedAt,
	)
	return err
}

const createConversationPair = `-- name: CreateConversationPair :exec
insert into conversation_pairs (conversation_id, first_user_id, second_user_id)
values (
  $1,
  $2,
  $3
)
`

type CreateConversationPairParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	FirstUserID    uuid.UUID `json:"first_user_id"`
	SecondUserID   uuid.UUID `json:"second_user_id"`
}

func (q *Queries) CreateConversationPair(ctx context.Context, arg CreateConversationPairParams) error {
	_, err := q.db.Exec(ctx, createConversationPair, arg.ConversationID, arg.FirstUserID, arg.SecondUserID)
	return err
}

const createConversationParticipant = `-- name: CreateConversationParticipant :exec
insert into conversation_participants (conversation_id, user_id, added_by_user_id, joined_at)
values (
  $1,
  $2,
  $3,
  $4
)
`

type CreateConversationParticipantParams struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	UserID         uuid.UUID          `json:"user_id"`
	AddedByUserID  *uuid.UUID         `json:"added_by_user_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateConversationParticipant(ctx context.Context, arg CreateConversationParticipantParams) error {
	_, err := q.db.Exec(ctx, createConversationParticipant,
		arg.ConversationID,
		arg.UserID,
		arg.AddedByUserID,
		arg.JoinedAt,
	)
	return err
}

const createConversationParticipantIfMissing = `-- name: CreateConversationParticipantIfMissing :execrows
insert into conversation_participants (conversation_id, user_id, added_by_user_id, joined_at)
values (
  $1,
  $2,
  $3,
  $4
)
on conflict do nothing
`

type CreateConversationParticipantIfMissingParams struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	UserID         uuid.UUID          `json:"user_id"`
	AddedByUserID  *uuid.UUID         `json:"added_by_user_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateConversationParticipantIfMissing(ctx context.Context, arg CreateConversationParticipantIfMissingParams) (int64, error) {
	result, err := q.db.Exec(ctx, createConversationParticipantIfMissing,
		arg.ConversationID,
		arg.UserID,
		arg.AddedByUserID,
		arg.JoinedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEventSubscription = `-- name: CreateEventSubscription :exec
insert into event_subscriptions (
  id,
  owner_user_id,
  workspace_id,
  url,
  enabled,
  encrypted_secret,
  event_type,
  resource_type,
  resource_id,
  created_at,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  true,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
`

type CreateEventSubscriptionParams struct {
	ID              uuid.UUID          `json:"id"`
	OwnerUserID     uuid.UUID          `json:"owner_user_id"`
	WorkspaceID     *uuid.UUID         `json:"workspace_id"`
	Url             string             `json:"url"`
	EncryptedSecret string             `json:"encrypted_secret"`
	EventType       *string            `json:"event_type"`
	ResourceType    *string            `json:"resource_type"`
	ResourceID      *uuid.UUID         `json:"resource_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEventSubscription(ctx context.Context, arg CreateEventSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createEventSubscription,
		arg.ID,
		arg.OwnerUserID,
		arg.WorkspaceID,
		arg.Url,
		arg.EncryptedSecret,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
insert into messages (id, conversation_id, author_user_id, body_text, body_rich, metadata, created_at)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreateMessageParams struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	AuthorUserID   uuid.UUID          `json:"author_user_id"`
	BodyText       string             `json:"body_text"`
	BodyRich       *json.RawMessage   `json:"body_rich"`
	Metadata       *json.RawMessage   `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.AuthorUserID,
		arg.BodyText,
		arg.BodyRich,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const deleteConversationParticipant = `-- name: DeleteConversationParticipant :execrows
delete from conversation_participants
where conversation_id = $1
  and user_id = $2
`

type DeleteConversationParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteConversationParticipant(ctx context.Context, arg DeleteConversationParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversationParticipant, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventSubscriptionByOwner = `-- name: DeleteEventSubscriptionByOwner :execrows
delete from event_subscriptions
where id = $1
  and owner_user_id = $2
`

type DeleteEventSubscriptionByOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteEventSubscriptionByOwner(ctx context.Context, arg DeleteEventSubscriptionByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventSubscriptionByOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveConversationInvite = `-- name: GetActiveConversationInvite :one
select id, conversation_id, encrypted_token, created_at
from conversation_invites
where conversation_id = $1
  and revoked_at is null
`

type GetActiveConversationInviteRow struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	EncryptedToken *string            `json:"encrypted_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveConversationInvite(ctx context.Context, conversationID uuid.UUID) (GetActiveConversationInviteRow, error) {
	row := q.db.QueryRow(ctx, getActiveConversationInvite, conversationID)
	var i GetActiveConversationInviteRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EncryptedToken,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveConversationInviteForUpdate = `-- name: GetActiveConversationInviteForUpdate :one
select id, conversation_id, encrypted_token, created_at
from conversation_invites
where conversation_id = $1
  and revoked_at is null
for update
`

type GetActiveConversationInviteForUpdateRow struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	EncryptedToken *string            `json:"encrypted_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveConversationInviteForUpdate(ctx context.Context, conversationID uuid.UUID) (GetActiveConversationInviteForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getActiveConversationInviteForUpdate, conversationID)
	var i GetActiveConversationInviteForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EncryptedToken,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationInviteByTokenHashForUpdate = `-- name: GetConversationInviteByTokenHashForUpdate :one
select id, conversation_id, mode, allowed_user_ids, allowed_emails, expires_at, revoked_at
from conversation_invites
where token_hash = $1
for update
`

type GetConversationInviteByTokenHashForUpdateRow struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	Mode           string             `json:"mode"`
	AllowedUserIds *json.RawMessage   `json:"allowed_user_ids"`
	AllowedEmails  *json.RawMessage   `json:"allowed_emails"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetConversationInviteByTokenHashForUpdate(ctx context.Context, tokenHash string) (GetConversationInviteByTokenHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getConversationInviteByTokenHashForUpdate, tokenHash)
	var i GetConversationInviteByTokenHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Mode,
		&i.AllowedUserIds,
		&i.AllowedEmails,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getConversationPair = `-- name: GetConversationPair :one
select conversation_id
from conversation_pairs
where first_user_id = $1
  and second_user_id = $2
`

type GetConversationPairParams struct {
	FirstUserID  uuid.UUID `json:"first_user_id"`
	SecondUserID uuid.UUID `json:"second_user_id"`
}

func (q *Queries) GetConversationPair(ctx context.Context, arg GetConversationPairParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getConversationPair, arg.FirstUserID, arg.SecondUserID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getEventSubscriptionByIDAndOwner = `-- name: GetEventSubscriptionByIDAndOwner :one
select id, workspace_id, url, enabled, event_type, resource_type, resource_id, created_at, updated_at
from event_subscriptions
where id = $1
  and owner_user_id = $2
  and ($3::uuid is null or workspace_id = $3)
`

type GetEventSubscriptionByIDAndOwnerParams struct {
	ID          uuid.UUID  `json:"id"`
	OwnerUserID uuid.UUID  `json:"owner_user_id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type GetEventSubscriptionByIDAndOwnerRow struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  *uuid.UUID         `json:"workspace_id"`
	Url          string             `json:"url"`
	Enabled      bool               `json:"enabled"`
	EventType    *string            `json:"event_type"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *uuid.UUID         `json:"resource_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventSubscriptionByIDAndOwner(ctx context.Context, arg GetEventSubscriptionByIDAndOwnerParams) (GetEventSubscriptionByIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getEventSubscriptionByIDAndOwner, arg.ID, arg.OwnerUserID, arg.WorkspaceID)
	var i GetEventSubscriptionByIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Enabled,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventSubscriptionWorkspaceForOwnerForUpdate = `-- name: GetEventSubscriptionWorkspaceForOwnerForUpdate :one
select workspace_id
from event_subscriptions
where id = $1
  and owner_user_id = $2
for update
`

type GetEventSubscriptionWorkspaceForOwnerForUpdateParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetEventSubscriptionWorkspaceForOwnerForUpdate(ctx context.Context, arg GetEventSubscriptionWorkspaceForOwnerForUpdateParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEventSubscriptionWorkspaceForOwnerForUpdate, arg.ID, arg.OwnerUserID)
	var workspace_id *uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listConversationParticipants = `-- name: ListConversationParticipants :many
select u.id, u.principal_type, u.status, u.email, p.handle, p.display_name, p.avatar_url, p.bio, a.metadata
from conversation_participants cp
join users u on u.id = cp.user_id
join user_profiles p on p.user_id = u.id
left join agents a on a.user_id = u.id
where cp.conversation_id = $1
order by p.display_name asc
`

type ListConversationParticipantsRow struct {
	ID            uuid.UUID        `json:"id"`
	PrincipalType string           `json:"principal_type"`
	Status        string           `json:"status"`
	Email         *string          `json:"email"`
	Handle        string           `json:"handle"`
	DisplayName   string           `json:"display_name"`
	AvatarUrl     *string          `json:"avatar_url"`
	Bio           *string          `json:"bio"`
	Metadata      *json.RawMessage `json:"metadata"`
}

func (q *Queries) ListConversationParticipants(ctx context.Context, conversationID uuid.UUID) ([]ListConversationParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationParticipantsRow{}
	for rows.Next() {
		var i ListConversationParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalType,
			&i.Status,
			&i.Email,
			&i.Handle,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSubscriptionsByOwner = `-- name: ListEventSubscriptionsByOwner :many
select id, workspace_id, url, enabled, event_type, resource_type, resource_id, created_at, updated_at
from event_subscriptions
where owner_user_id = $1
  and ($2::uuid is null or workspace_id = $2)
order by created_at desc
`

type ListEventSubscriptionsByOwnerParams struct {
	OwnerUserID uuid.UUID  `json:"owner_user_id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type ListEventSubscriptionsByOwnerRow struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  *uuid.UUID         `json:"workspace_id"`
	Url          string             `json:"url"`
	Enabled      bool               `json:"enabled"`
	EventType    *string            `json:"event_type"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *uuid.UUID         `json:"resource_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEventSubscriptionsByOwner(ctx context.Context, arg ListEventSubscriptionsByOwnerParams) ([]ListEventSubscriptionsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listEventSubscriptionsByOwner, arg.OwnerUserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventSubscriptionsByOwnerRow{}
	for rows.Next() {
		var i ListEventSubscriptionsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.Enabled,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageExistsInConversation = `-- name: MessageExistsInConversation :one
select exists(
  select 1
  from messages
  where id = $1
    and conversation_id = $2
)
`

type MessageExistsInConversationParams struct {
	MessageID      uuid.UUID `json:"message_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

func (q *Queries) MessageExistsInConversation(ctx context.Context, arg MessageExistsInConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, messageExistsInConversation, arg.MessageID, arg.ConversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeActiveConversationInvite = `-- name: RevokeActiveConversationInvite :execrows
update conversation_invites
set revoked_at = $1
where conversation_id = $2
  and revoked_at is null
`

type RevokeActiveConversationInviteParams struct {
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ConversationID uuid.UUID          `json:"conversation_id"`
}

func (q *Queries) RevokeActiveConversationInvite(ctx context.Context, arg RevokeActiveConversationInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveConversationInvite, arg.RevokedAt, arg.ConversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
update messages
set deleted_at = $1
where id = $2
`

type SoftDeleteMessageParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, arg.DeletedAt, arg.ID)
	return err
}

const touchConversationLastMessage = `-- name: TouchConversationLastMessage :exec
update conversations
set last_message_at = $1,
    updated_at = $1
where id = $2
`

type TouchConversationLastMessageParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) TouchConversationLastMessage(ctx context.Context, arg TouchConversationLastMessageParams) error {
	_, err := q.db.Exec(ctx, touchConversationLastMessage, arg.UpdatedAt, arg.ID)
	return err
}

const updateConversationDetails = `-- name: UpdateConversationDetails :exec
update conversations
set title = coalesce($1, title),
    description = coalesce($2, description),
    archived_at = $3,
    updated_at = $4
where id = $5
`

type UpdateConversationDetailsParams struct {
	Title       *string            `json:"title"`
	Description *string            `json:"description"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateConversationDetails(ctx context.Context, arg UpdateConversationDetailsParams) error {
	_, err := q.db.Exec(ctx, updateConversationDetails,
		arg.Title,
		arg.Description,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateEventSubscriptionEnabledByOwner = `-- name: UpdateEventSubscriptionEnabledByOwner :execrows
update event_subscriptions
set enabled = $1,
    updated_at = $2
where id = $3
  and owner_user_id = $4
`

type UpdateEventSubscriptionEnabledByOwnerParams struct {
	Enabled     bool               `json:"enabled"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          uuid.UUID          `json:"id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
}

func (q *Queries) UpdateEventSubscriptionEnabledByOwner(ctx context.Context, arg UpdateEventSubscriptionEnabledByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventSubscriptionEnabledByOwner,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
update messages
set body_text = $1,
    body_rich = $2,
    metadata = $3,
    edited_at = $4
where id = $5
`

type UpdateMessageContentParams struct {
	BodyText string             `json:"body_text"`
	BodyRich *json.RawMessage   `json:"body_rich"`
	Metadata *json.RawMessage   `json:"metadata"`
	EditedAt pgtype.Timestamptz `json:"edited_at"`
	ID       uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.Exec(ctx, updateMessageContent,
		arg.BodyText,
		arg.BodyRich,
		arg.Metadata,
		arg.EditedAt,
		arg.ID,
	)
	return err
}

const upsertConversationRead = `-- name: UpsertConversationRead :exec
insert into conversation_reads (conversation_id, user_id, last_read_message_id, last_read_at, updated_at)
values (
  $1,
  $2,
  $3,
  $4,
  $5
)
on conflict (conversation_id, user_id)
do update set
  last_read_message_id = excluded.last_read_message_id,
  last_read_at = excluded.last_read_at,
  updated_at = excluded.updated_at
`

type UpsertConversationReadParams struct {
	ConversationID    uuid.UUID          `json:"conversation_id"`
	UserID            uuid.UUID          `json:"user_id"`
	LastReadMessageID *uuid.UUID         `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertConversationRead(ctx context.Context, arg UpsertConversationReadParams) error {
	_, err := q.db.Exec(ctx, upsertConversationRead,
		arg.ConversationID,
		arg.UserID,
		arg.LastReadMessageID,
		arg.LastReadAt,
		arg.UpdatedAt,
	)
	return err
}
