// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	UserID           uuid.UUID          `json:"user_id"`
	OwnerUserID      *uuid.UUID         `json:"owner_user_id"`
	OwnerWorkspaceID *uuid.UUID         `json:"owner_workspace_id"`
	Mode             string             `json:"mode"`
	CreatedByUserID  uuid.UUID          `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AgentApiKey struct {
	ID               uuid.UUID          `json:"id"`
	AgentUserID      uuid.UUID          `json:"agent_user_id"`
	CreatedByUserID  uuid.UUID          `json:"created_by_user_id"`
	TokenHash        string             `json:"token_hash"`
	EncryptedToken   string             `json:"encrypted_token"`
	ScopeType        string             `json:"scope_type"`
	ScopeWorkspaceID *uuid.UUID         `json:"scope_workspace_id"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Label            string             `json:"label"`
	SecretHash       string             `json:"secret_hash"`
	ScopeType        string             `json:"scope_type"`
	ScopeWorkspaceID *uuid.UUID         `json:"scope_workspace_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AuthSession struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     *uuid.UUID         `json:"workspace_id"`
	AccessPolicy    string             `json:"access_policy"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	LastMessageAt   pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ConversationEventFeed struct {
	ConversationID  uuid.UUID `json:"conversation_id"`
	ExternalEventID uuid.UUID `json:"external_event_id"`
}

type ConversationInvite struct {
	ID              uuid.UUID          `json:"id"`
	ConversationID  uuid.UUID          `json:"conversation_id"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	TokenHash       string             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Mode            string             `json:"mode"`
	AllowedUserIds  *json.RawMessage   `json:"allowed_user_ids"`
	AllowedEmails   *json.RawMessage   `json:"allowed_emails"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EncryptedToken  *string            `json:"encrypted_token"`
}

type ConversationPair struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	FirstUserID    uuid.UUID `json:"first_user_id"`
	SecondUserID   uuid.UUID `json:"second_user_id"`
}

type ConversationParticipant struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	UserID         uuid.UUID          `json:"user_id"`
	AddedByUserID  *uuid.UUID         `json:"added_by_user_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type ConversationRead struct {
	ConversationID    uuid.UUID          `json:"conversation_id"`
	UserID            uuid.UUID          `json:"user_id"`
	LastReadMessageID *uuid.UUID         `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EmailLoginChallenge struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	CodeHash   string             `json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EventSubscription struct {
	ID              uuid.UUID          `json:"id"`
	OwnerUserID     uuid.UUID          `json:"owner_user_id"`
	WorkspaceID     *uuid.UUID         `json:"workspace_id"`
	Url             string             `json:"url"`
	Enabled         bool               `json:"enabled"`
	EncryptedSecret string             `json:"encrypted_secret"`
	EventType       *string            `json:"event_type"`
	ResourceType    *string            `json:"resource_type"`
	ResourceID      *uuid.UUID         `json:"resource_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ExternalEvent struct {
	ID                    uuid.UUID          `json:"id"`
	SequenceID            int64              `json:"sequence_id"`
	WorkspaceID           *uuid.UUID         `json:"workspace_id"`
	Type                  string             `json:"type"`
	ResourceType          string             `json:"resource_type"`
	ResourceID            uuid.UUID          `json:"resource_id"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	Payload               json.RawMessage    `json:"payload"`
	SourceInternalEventID *uuid.UUID         `json:"source_internal_event_id"`
	DedupeKey             string             `json:"dedupe_key"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ExternalEventProjectionFailure struct {
	ID              uuid.UUID          `json:"id"`
	InternalEventID uuid.UUID          `json:"internal_event_id"`
	Error           string             `json:"error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InternalEvent struct {
	ID            uuid.UUID          `json:"id"`
	SequenceID    int64              `json:"sequence_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	WorkspaceID   *uuid.UUID         `json:"workspace_id"`
	ActorUserID   *uuid.UUID         `json:"actor_user_id"`
	ShardID       int32              `json:"shard_id"`
	Payload       json.RawMessage    `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	AuthorUserID   uuid.UUID          `json:"author_user_id"`
	BodyText       string             `json:"body_text"`
	BodyRich       *json.RawMessage   `json:"body_rich"`
	Metadata       *json.RawMessage   `json:"metadata"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OauthAccount struct {
	ID             uuid.UUID          `json:"id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Email          *string            `json:"email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OauthState struct {
	ID          uuid.UUID          `json:"id"`
	Provider    string             `json:"provider"`
	StateHash   string             `json:"state_hash"`
	RedirectUri *string            `json:"redirect_uri"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProjectorCheckpoint struct {
	Name           string             `json:"name"`
	LastSequenceID int64              `json:"last_sequence_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProjectorLease struct {
	Name       string             `json:"name"`
	ShardID    int32              `json:"shard_id"`
	Owner      string             `json:"owner"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	PrincipalType string             `json:"principal_type"`
	Email         *string            `json:"email"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserEventFeed struct {
	UserID          uuid.UUID `json:"user_id"`
	ExternalEventID uuid.UUID `json:"external_event_id"`
}

type UserProfile struct {
	UserID      uuid.UUID          `json:"user_id"`
	Handle      string             `json:"handle"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	Bio         *string            `json:"bio"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID              uuid.UUID          `json:"id"`
	SubscriptionID  uuid.UUID          `json:"subscription_id"`
	ExternalEventID uuid.UUID          `json:"external_event_id"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	LastError       *string            `json:"last_error"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceEventFeed struct {
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	ExternalEventID uuid.UUID `json:"external_event_id"`
}

type WorkspaceInvite struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	Email            *string            `json:"email"`
	InvitedByUserID  uuid.UUID          `json:"invited_by_user_id"`
	TokenHash        string             `json:"token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedByUserID *uuid.UUID         `json:"accepted_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	InvitedUserID    *uuid.UUID         `json:"invited_user_id"`
}

type WorkspaceMembership struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	InvitedByUserID *uuid.UUID         `json:"invited_by_user_id"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
