// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: oauth.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthState = `-- name: CreateOAuthState :exec
insert into oauth_states (id, provider, state_hash, redirect_uri, expires_at, created_at)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
`

type CreateOAuthStateParams struct {
	ID          uuid.UUID          `json:"id"`
	Provider    string             `json:"provider"`
	StateHash   string             `json:"state_hash"`
	RedirectUri *string            `json:"redirect_uri"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.ID,
		arg.Provider,
		arg.StateHash,
		arg.RedirectUri,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteOAuthState = `-- name: DeleteOAuthState :exec
delete from oauth_states
where id = $1
`

func (q *Queries) DeleteOAuthState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthState, id)
	return err
}

const getOAuthStateByHash = `-- name: GetOAuthStateByHash :one
select id, redirect_uri
from oauth_states
where provider = $1
  and state_hash = $2
  and expires_at > $3
`

type GetOAuthStateByHashParams struct {
	Provider  string             `json:"provider"`
	StateHash string             `json:"state_hash"`
	NowAt     pgtype.Timestamptz `json:"now_at"`
}

type GetOAuthStateByHashRow struct {
	ID          uuid.UUID `json:"id"`
	RedirectUri *string   `json:"redirect_uri"`
}

func (q *Queries) GetOAuthStateByHash(ctx context.Context, arg GetOAuthStateByHashParams) (GetOAuthStateByHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthStateByHash, arg.Provider, arg.StateHash, arg.NowAt)
	var i GetOAuthStateByHashRow
	err := row.Scan(&i.ID, &i.RedirectUri)
	return i, err
}

const getUserByOAuthAccount = `-- name: GetUserByOAuthAccount :one
select u.id, u.principal_type, u.status, u.email, p.handle, p.display_name, p.avatar_url, p.bio
from oauth_accounts oa
join users u on u.id = oa.user_id
join user_profiles p on p.user_id = u.id
where oa.provider = $1
  and oa.provider_user_id = $2
`

type GetUserByOAuthAccountParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

type GetUserByOAuthAccountRow struct {
	ID            uuid.UUID `json:"id"`
	PrincipalType string    `json:"principal_type"`
	Status        string    `json:"status"`
	Email         *string   `json:"email"`
	Handle        string    `json:"handle"`
	DisplayName   string    `json:"display_name"`
	AvatarUrl     *string   `json:"avatar_url"`
	Bio           *string   `json:"bio"`
}

func (q *Queries) GetUserByOAuthAccount(ctx context.Context, arg GetUserByOAuthAccountParams) (GetUserByOAuthAccountRow, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthAccount, arg.Provider, arg.ProviderUserID)
	var i GetUserByOAuthAccountRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.Status,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const upsertOAuthAccount = `-- name: UpsertOAuthAccount :exec
insert into oauth_accounts (
  id,
  provider,
  provider_user_id,
  user_id,
  email,
  created_at,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
on conflict (provider, provider_user_id)
do update set
  user_id = excluded.user_id,
  email = excluded.email,
  updated_at = excluded.updated_at
`

type UpsertOAuthAccountParams struct {
	ID             uuid.UUID          `json:"id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Email          *string            `json:"email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertOAuthAccount(ctx context.Context, arg UpsertOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, upsertOAuthAccount,
		arg.ID,
		arg.Provider,
		arg.ProviderUserID,
		arg.UserID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
