// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x93XIbN7Lwq6D4fVW5oSTvZi/2+Fw5spN41451JDu+SLlU4AxIIhoCEwAjhevSu59C",
	"A5gBZoD5ITmyvWdvUrGIARroRqP/+/Mi47uSM8KUXDz/vCixwDuiiIB/vcgyIuUVL2i2/5+KiL3+Y05k",
	"JmipKGeL54t3rNgjyrKiygnKOLsnQmL9m0QPVG0RZwRhmAaVMM/5Yrmg+ss/YMLlguEdWTxfmEG3ZtBi",
	"uZDZluywXpCward4/ttiR3YrDdhy8cDFnSxxRhaflgu1L/X3UgnKNovHx+XixYYw9frlFVbbLsDwI6ok",
	"EYjmhCm6pkTUQJX6mwYmPfaW5ovlQpA/KipIvniuREV88NZc7LBaPF9UFYzswvMDWXNB3hIp8Ya8ftl3",
	"koKoSjC0M2MlygTBiuRoBVMgtSVIkDURhGUkd8NSR2o+urWjzD6mwH3poTN1nP6Y4QP1CeT4c72shOQi",
	"cZxXeEOZASuDcWgt+A5hVApyT3klkSCy5Ewmj898FpxZF4ZX94SpayJ5JbIB3Lpboq+EsF8gmp+ja3MG",
	"sv7rrV4nBVY9aDI+A1jf70syBlqiP5JozUUI+CgQAQYfyP8vyHrxfPH/Lhq2c2F+lRcd8BqgxwKrIQSA",
	"e8HrQNU9qn+SfZKBXL1Gd2Q/TOx3ZH88jb+hO6oSW3+L/6S7aodYpRkj4mtEFdlJpLjjIyURqOzhEIWe",
	"PTiKnZlz8fyvz54tFzvKzL/+UsNGmSIbIgC4mqXFT8r+PHxSAYc65rTevajU9pLnKWLRP3NB/2X5As+J",
	"PSnNYvfAXmEKVAp+T3MP4DZv4DnphTUB243CKknJsLLUI9A9LqpDYYMZJgJ3U61+J5n6IIlIMrEP4ZuJ",
	"HrZcEmSvg0Ryy6tCv1SooFKR/By9JGtcFQoIUoOfVUK4xzcJvAHkVo+ZzuFuqlUNcYoqgaEg6Y0cJlB/",
	"9PFUak45Dt2HUYJJczrHwPHRiVEpYOoBwxDVItlJwRrD8wWRQGTwvOsHoAYlRWMtWA+Djd1TRd7zO8IG",
	"zw6GIqXHJk4Pfpt0ZR/1YCO/GFG9pK+E4OLa/lH/LeNMEab0/+KyLGgGbO/id6kB/Dz2VQ5mhYVb90kP",
	"8IQpPcJ+DIBdvf4nARyWgpdEKGoAtpLtLVYRoVL/pi+mojvAYo2YHCtypv/axc5yQf4stRgVnfId/A8u",
	"HL9CMHjEKqwqCrwqiENJZ1Waj5URBshruSjwihTd2X6udpidCYJzDUi9Axh9Hp9HAgeNn+4bLBXiK0nE",
	"Pck1Mz7yAAS553eJta7JPc+aU0YPW8LgLdAb2GKJVoQwZGc4HASZ8dJKm92LuCVqS0S9KpXwAJ3BNzni",
	"omEY9m8aDqd06qEDGqdbPmArPfxgxSuWuzdRQwSH0mxBQxjwsDbdDB9H6xGNvzKloCyjJS4QrtRWE2pm",
	"dE0tbFDp6GwE5T76nOu3heGqnYfcUHeArKXPBpqT5fCp3onhHvKSFwXJDPBtRgIyb/A/fezMsqPHei0s",
	"BIZ/M/KnurU63whtEpCG85xavuKeISwIwveYAobOh88KgI5uPc+vsFBUo4gpqZVEIlV3//aAZRzLIHzh",
	"vKY3XwOHx8gd2iBzCs+rtY0aiOhONvYVmv0FcFOu9gO0/7DltW1FHwtYekbx6J2W/LtC5Xqt6fOeoAeh",
	"H3s9CnTmF1evz+7I/iy8YrAcwkDR0mc3msnfclaABQyvyS1MF2U6/IERMYLnmbWoRDkVJFPFHukv4Zpj",
	"YwfjQv+jIzpNYoEGmuShv4S1YWV7dRrwHUc+iNWZafpZ77sHRtmm2VwMgOMYblXmSVKG53ZHFM6xwsiM",
	"nEjWgIEBxqbJOnotFwGpWAKOXpWAGwebSt7qU3Jm4BLfAmOu1NYXs8NNSyKlPY2+3d6YYa/YPSl4SY7C",
	"slvSThGD2TfTdmEObe/9Nt57KumKFlTtPYP+NBP9coFFtqX3JO/nXFlgW9YYNF95yFtxXhDMfN7/xM8J",
	"TM1FzKMw+JYEM/WeuvfT+aFKSY+pfoRmIlXtSIid8Hu6I1LhXYn4GpC341IhQTL9+Hh+isPk+7IRhG4z",
	"XrEIAL/URlBvsHQ2J7AXRAWgtllzuZBbLMhtQdkd3I2ieLdePP+t/176Z3ujv3+jP3/81FaWL60JDNZA",
	"eo3GyKeffWPFCAg/c7SrxQlS0A3VSmAp6L1+SAKXW5c0NDulqiAD1ABjzk/y0h30wI1Vnbh5ydt4XGoR",
	"RoMOZ7Qp+AoX3ZOZ+KrHlJq2k7JLl4mHtWZ4097YOFl1+LcxH3WVb/zgE1ptgOoiVUSsDj8I/qB52u+c",
	"MvTh+g2crT752JTN2Qo6+LQ6a5dedmjXJxQwgjfwG5Az4GUhRmFNan+jbF7XP15+//33/9W2edUYbWv5",
	"k3jzqYxWo2w4TmtDGJVESNidnpYLhDt2HLevk9tyrMM277fcoLeVVGhFEN9RpbW+tRUTPPDkPPadGvN2",
	"pJFOFA8sPQjLfh8NwixHO7xHuJC8iTsATXGHGd4QQG1Sd57GYCPmoeFbkZLCcUlv74zZeZw1SJJMkMgd",
	"uiqwFg3+VDUFm5Hn6DUo1eHrzVk24so74OpVe/a5AZ944vLje6ywuI2y75oEzCBEd3hDNB+PsOtBgltR",
	"3rNCKfiaFgStKB8lQ+RUlgXe3xrnR2ra7v3R8s+uVPtz9F4/Q0TcE4E2hBGBFZEII4FZzndoG7IeuxzS",
	"y0U5zxazvCB9G6xWBc2QGXeOPoL5wAC1NE+igSUngt4TCRcEBDn9mwPQWX0cGIPH1Fia4Irq3xqLUFuw",
	"fM2oorhom58a21Zw05uJrC3EbGYGS9Q7/Zvc0hJgKmqgGHloGMcBlqYpDDpl6UkzaGMhA/hOIDp655O+",
	"6b50kr7wXUXd0UajeodH8WtbX69REGhCAXnYuZK0MVbN79Vv69uVHaPo+hJ42hLuGdKdom5CmsxOzoB5",
	"hwoDerejCsY0dsOOSnGo9XyKVoZqYh4AZvCsxmpZjZTVtcIw72BOp2gl7gSEavgxHWkxWI9MsSBHaE1k",
	"GFrTQhnTxwj3ZhNvl57bC+hzk/fE9U2W+MKIutFmiUhIXcck0d1C7wn1yEqgoeZI0g1o6WaYvm+WdMlq",
	"y/kd/I5VJYi0HJhx4MKrArO78frpRztdTgp6T8Q+IdscfAtADm2UXo8KO1eg2BuzaOHCJY9/M/SWR8iH",
	"NsTOuxfhdlY839+C+MoFgn8Imm3Rzj58NpQMmHt4oeqx44ntR0HIj1zs3lkYO5R2o0SVacTnCKDQa6AS",
	"7wuO8yih1dD3yeXWuAizRanH+V5OuBMX2Vi7ddK7SHO3VixRmrftMO0T8OF3hPNcECmR2mJl8LvDKtsa",
	"CTDLSKn0nax9/gGFmhXGWP8GFc6WGfwgcI59NjoHm9ISTWTWbY/57CEZxdU1uZvJorzqBew4sKK155tk",
	"QQsAD5b+NHwqSUKL62MNRxxUpGRRbXpZalFtAuWN6U0X9F9EIqq03FHwByIyLEdo0QCtXTO26044XCv6",
	"IOrHv1GgMu5wtqWMNDokgSA3/U104/BzRO78kZIiPyvIPSnQPS5o7oRchWlh5Wth0OH/vta/BvJlH7f6",
	"tf7wJcwbEzctkxw005l9ev6aiCQC4CbVLr0V7/5rcjfIPpM0J0gJXq0KIrecaw4wjGYbae02EMV0R8rp",
	"PhdGg69FnOZxJ38qImrpUIsklrfbxAcsQhE4EiPm/+ycsEOqUUe0fZoISaax3ON2tcIUJWbjdnzc4Tqj",
	"zB0jrsG47UEd7GBJ/puX2Ofx2n1lYrn1yJhIZ+t7OYHPz0ji7uZM8991bvkJ3VldDvIN+LReWW4LwEdO",
	"IHnvJ151noEjI07xZkY7hGVTyd7K+kP4aSsRA/znumE79eNpZfomAQi46TRe59jPRKbjpoyfnbNjHG5i",
	"0mqBdYPVG5vpAtu4t3ZSYphH6RNMg+JBEj7lfQ6uxjdwl1sErp+4erUr7yAMolqCsSDkTOMW/ePm3S/I",
	"TOoB06zyE2FE0OxGYVXJnrA7+D0i0NNdWRBkfkZmj8ObtrPFdv0PTtkoW/1xQRnRkIkYPG979NvxEYXe",
	"zZV999Za/re0lLXJy3mOcVHY9LAx5F7P+bae8qba7bDYjwo2XwQQxw+mVnlaThRIAk07z02S6EEBff9G",
	"VrN2qv5JwwlnUG1yUpDUlDd8rZAZcGSuE8lpapFab8ypmiGlLJ5MPZyu8KWNn53nuFsDonUhfQoeTBCy",
	"wJzwHXZ84xt4gV1KuUiHiAhi0j5utdrVvWsF1XLXh+vXpmiAGQuBQmtFhE0414ek745EsgIH9Loqiv1k",
	"o2UAytB2koE9ldrGbaxXNi0e4SDJ/8P1G70fXhLmQoBXJrJxjFZqculHpOpjKXlGIcwD6t6AnTsAxBrO",
	"RoQHuS265WNndUOwyLY/01heVSvWf0pM5DSuH+riW3oKCd7alSZLy3eU5WG1IHONl23zXGOXq011ZsVP",
	"UfZZCxEjeUavkneJGWc0C61MPj+PhSOKCAH+CF5VgdkdeFr1oPC5AStrM6EpEQITMlqWce8tF8pUxyEP",
	"SHPfUaa6RCDDNfC6KYHlh8iqo4XMwy1Mp6Hq1hUHYl12SvloVKcve5LHD17aeKiN3efhJs7US/iuxH9U",
	"BJWTKjB1ZtdnJMfYaWEgRLXBMQUayGm5QVseMOVzRtTlcS9/XZknnnnyR7zchUE/gl/riznR9FIf20Ob",
	"zg/Ff4ukDex91Jv0wk4Sz5qH7xsQ0NpZfpPC9+3HoytVdMk1boH4gWBBBLJZg9MsEEGRjeiOtfj2aodp",
	"8YZvKJsa1PAqjGXgkEFG7wnC6J4IurY1TGpPbCeEoX8TZlQM7g9gyD883Np8n7toay11upwkxVFWECwQ",
	"VSeLvXbLrShPrXNkGLZb4eDoaTdBGDw9PqXefd9ENB8YnpwyDboFwNBjDYRhzLS3HobsfqhrIUvCcpLH",
	"a08mCGtcdO9wVix3SbAa6xVz/4glNibw7zlwe8NzfyEPx0XmJgTDzrxjRcT04U4IEx3yf3d8ik1Vsx5f",
	"eJvL2FXSfOabCtu7JmWBM7ID9/sJjZH+vOUXDefzITkwpM/g9cpkwiTxCvFA8K5ZhztntaWgqQ5iLOnf",
	"SZdY00Vz30ukL9gTvUJ6qfleID178PqgHwrM7ozBRdqV9Omt9akGUUYQz2+S86qy5EIF93b47dJLt5J+",
	"Xu1KtXdrawFREI376MRpArkmOIcakEkWBZn28Lp5VTF7rMGQr4HFHcLSc8N8J5GeCOmJoun3owo5RWFJ",
	"c7WWSyd5C14oVBAoQsYc8iCTzizcpXbBUzhqlBk9xn+vIedmsVzgfEcZxI+BAWSKfBAu0Hi+rKzgr2YC",
	"ME2GeEdO0Ge64/cTJYZDwzVDqA8M2QwngbDNkVRurTijhP0rQXdY7FsBzEYp87Wv6XHKybpPE70ndXxy",
	"Isztqi6hZiKwrPQIEqUgGRdxtmP5+hhzl31ReuXYRn49H1ebrbWteuoGsk8J3F41kI9/kV58YxmoJiZ2",
	"LShhebE/XAOyQadADUn1p4UfO1cLxBQ6Tuj2crbVr92k0ol2PjKy2wu7HgjyhpcqHfRsHjIIbFpjWpDc",
	"mzohyI6LyfYgTAdmt87PwLocEz39KxF0vR9hsomf669ts4yL/DRRa8Cy4zHzYyxA4OZQXLM3oSBz7Iyy",
	"gw0/9jxip/DRdyl8FXUKjyks1e/gmDjZ06SFLJ6o2FC0VqkGcOkySo6ujNeSgyNO+ahAe80LgrYgDRut",
	"MFqN8QSC7dtZRNlpLrz+8pwTKXSsZ2/StC1CaRUN9yqw8yIQoZI1+NoRb6d7u9sE9w084z3hf6fPS/va",
	"7lvvgkdcwC9wD9rUnxRX69XnoPuvn+JN2nwlqNrfaOituRZccS8q00AAtmUaN+k/N2ttlSpN6X3K1rwv",
	"rOTn9++voFJRxpkSOFO1TvqeCCwLnN1ZQxlsxZjoF81vxq5E2UZPslgu7okw1UwXz87/cv4MUitKwnBJ",
	"F88X358/O/8eouXVFrZzYSqm6P/dkKjFV1WCSVtYxdYhrssS2xyHoAKVKU3cRPpqNNk+WME4KhG2hV6g",
	"Fpi+rHqHmrZM/6pcywxUKlO2dtFqn/DXZ89O1jGhUxg30jThbat8ljw3DhlbzSW+QA3xRafbA9CX45+w",
	"z06FLr1nhTdSU6k9hE+Py0XJZUquhZpKayqkOssKLC3eLGIAd4SC1ySNuaCodKTAmMYTlYoI2cWWVwFr",
	"Ueed/sDz/ckwFamx9RheaOvFaNHKX05LKzECMW3qrNR5UuK4tAX0mEFnjCoel+4qX3x2PfAeB291rCyc",
	"pgGqZEyJCZH9E1EO034PwoRnpxly4Tf7e/w097VOo8rmdJ8UVTdb/tCLKOC92Tbl29b3t42Rxq20BKc6",
	"1E5t1IAQK15UxAkQc/oLHInaGHWBn4Aq6oAQE0lwQqowMw9f4JKe3ZH98Gtcd/Cq+wL0MPNO3Uf0sV11",
	"s54vw4xx5dp/Qk8RWzLKhFxUYm1l38gzXdJ/auCnUl2kkdm8XKHToCTGIaInLEkBDsSgSOfp5YA9r0SN",
	"E59Yrl4jOOIxUkBdbDXSLqeujFkXlmuRTvRhwCy3sZDSngZUi3IVNKOiANDEvLJAUG33iYWBaGnTNDnN",
	"LB3YVeIU4zOYi8+m0+WjIaCCKBJvBHVnS2M6+Hv5TarIbEgYL2G5mjCm8YqmyWeERfwt3dWrbld1wnM3",
	"5zPu3Cu1vQCD9gWYxUGLjt7fG8JyfXs5M9bQbgylS94MXbB7XrkYo+6RtyI8Z7qOiTjSUTfyryeDIp58",
	"HLmSgRfEHOYfFalOQyTWbrB4/tunQDokLNcEY5azvhFkPT417VRq26UboIN9mnBe/ZltMdsQ2czvaEPz",
	"7S4ZraEAtwsp1mPCkCa41V5EVUhSbRfUTDSV8nQ9tcjo94+J0JKL+z4he09REN1AUhxkrNWYHqAgDv/d",
	"ULWtVhcZLooVzu6SQuZlnTuo2cxPVP1crWxa4brgD6iSrqGDa2uL3JyGsjQtQRpcRCqwc5tZYdLJb0Cr",
	"Y/DjctwXXh/fecXLabRirJjMS+X8cP0aPWAJcXAFJTnKK6FPvM5gFEY5+d5wzfaj3SSEwhsN6aJnLvw0",
	"XMVkjDYZoo23djb6/ZEyKreOqux6Y0l34O2sZV+G/GxPE9XTkV4tCFNSTyOvakjIc7DAbsbwEzO/SI5v",
	"hKzNiXdOc05WCAEGUymJ801BJjNB+OrkTBBm/Q8T/D/LBA1VTSTd0zJBA8KxTDAg5P8wwadngmMpyYr7",
	"8sLq7mP0f1/Vt3QA1sUgJ/Ecvd9SiQjLS06ZcqHh0lMxMkHAm4ALJLBN3cHM05+71GVAsB3YbuqeicN6",
	"v+Mvc+j9IILzSgUH0zR0jBx9UG5/0LgbjE6UbEI/Gausc3m7zvqQRdGpcB7M+N9+CH7r83BpymxmRivs",
	"oWv6Ddp/TX7LmuLPL0e/Zm/ojqrRoy8hYGD08BfwFlxB740neCxTzdNiRosYRk9vgM5a+HQ0HeJ5jBU6",
	"7FjyY9OCQj3wM2OituEELlJWmv485E8qoeB4VkdKtJuL1o2cKJOK4BzxtW29yDYIo7wyCEkapy/DugLz",
	"mahjqaRP/H6FVWO6hPWqe9whWurTBmo7qQ19ALTLTmvNmQzoqFVoIkX1HZZ+8TunLC2SmVLy7dvQKSnY",
	"VMilG0byM8rqHtsh9bbrGc5Eu6myiV8Z5TqvbXC2RqjXaNE0vdp7h31S0tFn1MarLZnSrDiJlD63SsOM",
	"C+LIOv2eY1UeO/EbLSqa9mz7Hz9FNMckPjFfbMdYLjEi0KObVL/0c/YhzsNVGLDGBGjFYDBa55bjouAP",
	"xKaVMs2rY8UFYmEi8+B/rqCRb5QZzRJJcvhb1WEwF07wGuQ0biCirMt1KGhbREiCsq3gjBd8A3IEF3mM",
	"/WhB05WCPAntfWGl4Qey5sKViXiSQJZIIc0htugwOEPsaoNKR4s1dtOKwhWXIBg5IVPxNlsc+ZgFvbW+",
	"ZlYWbQL2xFErde3DSJSzRcQccrbxfqOmsFuEUMbwK6+B5DDP8gdbn3eqg+Q5+oWzM/NryxRilB/jcC3V",
	"HhVUqmFTyJUP6NcuXrWTk4dYiX+w81oggqUOsEa8yHMTziwNf0nj/zKh/NaBkSv9uGG2IZGQiBd5Pj/y",
	"T8+QXuS5D+oXEqxGUF9dnczrDGvu4QmJ70WeH0R7U/nWxWebjjgQgrfjrju1v22rYs5EyGbVBC0/kahm",
	"ooEnRPr5/YJtwt2Jo/30nG3ppAwO5hjiEATnZ3Xt6rKKFikVdx21EcoFqa3g1WZrIjBdnSFmKhv064F6",
	"zlCvwvnXrwl2ajKN4lZ/i10wbDVrm5h+WqJ5C1WeWqYpCTg7klzAunQG1qUhCShwUzU2x7WL2PWYCOPs",
	"7OXbFi95vdZ/txZ5ifZELeFDKhspccC2BG2G3xhT2LdjZGqgjslC9kQTJt3TG558NCYWPRlNXQhec6Ko",
	"SBXzDU+nrSAcASPR1PSLPEoA0b85UflVDZ+CsMyhdnvGjyYpKLx95pffHNbI6qbi/letzALr5U4nKhn4",
	"dlQZu6faEirQilcsH/JVdxv8zZlZ3NtOMOaH67TMnEG5imLAw7QBIjyjMc5e47iKTm8at5r+rJNMOt2e",
	"iXPaZZJ1aZ/YQhPpFDmGVuZ1j8bwOkg1CS5x8dn/55AeZHKGZAKGKO9I5B3FyGlyumL98SQNJYIu2wHr",
	"pOgy+zwUXUmv1SuokCwRFyin0vz/MehI1IE+HTrm0j2OYxHPnpZFOJsJ6dDePF6p41jEsOzQav2dio67",
	"9irB2J4mhiJt5Rgtd2aYoZVrpmF+rSWHpdcEG7ywrnNJj0gx3cg3qzsKYHq/L8m0L/yWsod9OSGIrxv4",
	"N6cUnuwCGw2HClvMn1wEaxFy+464a7EluFDbfw2X50HSdE0t6D1hRDaNejop3qaWEMTM4Wjm9k9E/QzL",
	"zikXj07TvDHgmoOoq17MFk99uSXZHXrwegtolYNKVJUejuz5GByZSmeDJpgwqgtYUFBQDEbtgS1ZVBV7",
	"W4ghiiNX13dWB3MfZmoLiIlGWXGupBK4dGkvpzaAQFUEnGW8srUIvG6yDWrcsTjcXHiVmwcCcrpY+k7a",
	"KsDLoGLd0qvWD8+DLWIck3B8NM0lkrR6GHwB102f7GESiV1fhNNLHUAXZX3MKUIw/o+Lz01d/F6V44av",
	"1Vle6x3Oqm5yO7yKIAOxmkYaPzQuoY4mmaBmOA/+rLpFrw9/TImjA48z6MVykuOc604eEuHx7CkiPNy1",
	"rAtTz6EHDMZ4mMZ/PQbmiknbHRDhTHBp2HOTIxAYs5feW7A0rv4lPBHTLE7XFTO96uaqkBE0hXxikmj1",
	"9IuKWnDcNinoxKE/MLU+fKdKmZolWtwxQo5HKxYJhlKa2kWmzKq8+Azh8o8XGOLqx8TdNxlPZo7egHuI",
	"uoWCR3XThUiwB8zdKDAw7RGZT/D9ew3V/O6ITu3hSL0i2B7Jo91U5oigb9YxsQ3MYsqjiqYcbZsyRvgc",
	"Gik7YTJIuxps7Bc4sSb4GT760un8uByqZwZ3DDbenMVMlcuicnmAvWFXgmeK2eHa02g0DWoL0QrD4yGt",
	"G7JaYZDdD9poDbOVNZZyMnz0WsrO51zo9Ad6YqeCV3u5SyBNqel5fQjeSY+42Bef/eLV43JhGlYyPhHG",
	"J4CDk1efkHP3Y3DG5JdB/I0Q/hsEaWUaipkW1Sae2uINHioV3WrCdSJMzqUfHMYMnoiU6kauzRM3i7fg",
	"KGZwYeXBEbUwUgKgCZDDDHHblqrYa6oTRCpBMxtbALFPQUE1G91SpyjHddUW0z9aRHyKvIQWtF+0qmYH",
	"lrTm8rGN3qd5wybJqG3qtfL0iKQrGIf4Olh65NsWSKK2q8U38sZ1e670Yt6e0wzRMu0ljsJ3GPg94a00",
	"338noW+mVwH8xM+m1QmPJpEDQrxnf2rDJqdf6sFNa92dZ9cifebX166SJOvQXRa2QPntk8ad8SkaQoF+",
	"ktD/5PnFRcEzXGy5VM///uzvzwDPdo3OW51yvJmN5ZRBwzHTWMg54DSVdXoGCmjBndkia3WV1XXBH0wt",
	"VD9JOizf460A2+vO/yslD9DI3bYxi7mMnI+qFsPrSZvWoHFRxQevZYLyIiRxbaYKTBAOcFNRPrXEEnJm",
	"ljb0FioYRyuF1/YPf2pX1Thy7sbAd6B9NrQEeitaS2DyvPxp7blZPmvmN947+077E3sUnpy8tQU7v5/F",
	"EyzSBM36C4VRs7GDY/kSkZwqHzPGeeOl69bz1Xb07lQ/QHEuWz3HDy9Aa0LypiVSV2awc9vQg+7MpvdN",
	"X3ynya0k7bCJcOpW5M/jp8f/DQAA//8Af2QczdQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
