// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9X3PcNpL4V0Hx96val5HkbLau9rRPjuMkvrVjnWTHDymXCkNiNFiRAAOAI09c+u5X",
	"aAAkSAIkZ4aU7bt9ScUaEGh0Nxr9H5+TlBclZ4QpmVx+TkoscEEUEfCv52lKpLziOU33/10Rsdd/zIhM",
	"BS0V5Sy5TH6iuSICpZztiJBY/1Wi9R5h+BSV8O15skqoHv0HTLJKGC5IcpmYQbdmULJKZLolBdaLEFYV",
	"yeXvSUGKtQZmlTxwcS9LnJJkleBKbQlTNMWKZMnHVaL2pZ5PKkHZXfL4uEp+IBsuyBsiJb4jr36MQH9N",
	"VCUYKswwiVJB9JRoDV8jtSVIkA0RhKUkc8NiuzEf3dpRtzRr7WjDRYFVcplUFfzSB/mFh8NXP15hte0D",
	"7I9BNNNI2FAiapBK/VUNkU8VA48gf1RUkCy5VKIiJ8DHdlSRd/yesCmAwmik9PAIqPDbIIABgCohuYiQ",
	"9m2J/6gIKvEdZQaKFIYjATQnGcISMfJJ3dq/a6ZFpSA7yiupv4sS2nyQDAP3ckeYuiaSVyIdYkD9SaqA",
	"1Yj+BG0IyZDiiDPNfOZ7RLNzdG1QI+u/3upVY0DWgw7mwxbk7/YlORH2SVACGD6c/1+QTXKZ/L+LRkBd",
	"mF/lRQ/CBu7j4TV/GQK2B2Mfd/8k+9jRfX71Ct2T/fipvSf70w/ra1pQFUHEG/yJFlWBWKWFK+IbRBUp",
	"pEaEORzn6L000s8/IBvBCysSZcmZHsG14FeUuYN2F0NdrsFp4a4wQCSXf332bJUUlJl/fVdvhjJF7oiA",
	"3dRyPIxa+/M4aluy+RT0vn1eqe0LnsV4Tf/MBf3TSh6ekUburPeARZgClYLvaOYB3JU1PCMHikWY+EZh",
	"FQPOrCz1CLTDeXUsbDDDgcDdVOsalBg54SAj6Y0cp6w/+nTyvpdExKDTv43DU0kiTofjg1N6YsDUA8Yh",
	"qhWoWcGaImv1UkQqJ2hrQGJ81YH0OMjGFBQPc0toJ496sBGTRpUu6UshuLi2f9R/07KTMKX/F5dlrtVZ",
	"ytnFv6QG8PPUu7A1KyzcOU16QC2zzwFN9mMA7OrVPwlQsBS8JEJRA7BVhW+xCih3+jd9LBUtgIo1YTKs",
	"yJn+a586q4R8KrX+EpzyLfwPzpG7JmHwhFVYled4nRNHkt6qNJt6F4+w1yrJ8Zrk/dl+qQrMzgTBmQak",
	"3gGMPg/PI9VtJSPYfY2lQnwtidiRDFX6nj0JAYLs+H1krWuy42mDZfSwJQzOrN7AFku0JoQhO8PxIMiU",
	"l1bH6x/ELVFbIupVqdR7FmfwTYa4aASG/ZuGwxmIemjLOvwYXb4lVgbkwZpXDLRCBxEgpdmChrAlw7p8",
	"M4KOR1+O/J7AJ4azWoha+Uew2RVf/4ukSu/KnFz5guc5Sc0uuocY9LrW/wyJEisKHuu1sBAY/u2pgX3M",
	"XfVMLEAYzjJqz7QgssqVRFgQhHeYAnbOk1HMANDBrWfZFRaKprTETMlrc8H0929vYRm+xUHjxVlNa99c",
	"hovAIW1UMLTx1dlGDURwJ5Xa+ndCG35JpLSEHSLcjRn2ku1IzrU1tDLnYuQzjYMetG5JO0UIZt+278Pc",
	"duoMOwZ2VNI1zanae56i03w/qwSLdEt3JBsWNWnLQaF503zlseWa85xgpudc4DZ0U673t05ZDE/NBQjE",
	"Qy+r1kyDVPB+Oj/2Rh1wTE24VqWq3WYhDL+jBZEKF6W2VTXxCi4VEiTVdoLnlTvuciobSXKb8ooFAPi1",
	"tpS9wVKLO0GYyveIsqAE6Zqyq0RRlZMR9MGYSZSoyizKlqBGmAEHcubUi5I/MMruehtf6Ttbg442XKC7",
	"nK9x3nYQz3Rpdt3HfUIGT5knIVoHu4XOMbk347XbEqffwOULQokYZSF6807S9a9/evH999//Z1fXB76x",
	"ytfxx3ouZX2S7spt6ABhVBIhYXd6Wi4Q7umvbl+z67DWQ5wNa6zoTSUVWhPEC6oUyQDdvsp9T/YzHNGA",
	"SjvOTTFFCJf09t6YqdM0WElSQQK8d5VjLY0/qZryZuQ5eqU0mmpPGGf5HnGWTjgqDrh61fg++zGU6AnC",
	"ec4fSHZLCkzzgAb73PyO4Hd94AWRkkigprDuF5JZ74YM67Pw7bhCu6qBiSvUDhyrqhwGxzS9eqIHwfpz",
	"ZnMgFDwLHP3XlN27TaEUM32g9IVUKuNGxWyPSE7vqJYyKc5zIv4RwAeyjISwhz+p5Yahuy8ncsruwQnl",
	"JgmHPn3WBNgPY8fYETQA3xpXWF/04IeOSt3xqvW1SDNfJQJC+jkgEr2/fl3fBd35Gt4RdPwy82FvLT0N",
	"N/FDOmzs/Na1b+rtdDXFU42eQW2/PhrpKWq/r17F5YBnl7dlgdnZGcjVtjaI3hZUwZiHRrcUqLXpvgJ5",
	"vBSZroOj+kbV0DHOzswu+tCMYm+qUt2oEn0rlXmoWkavbvNz/HBAiMaP5cQVQT0yoj7VfNnEXtEGEkrO",
	"pzk2mxB3fG4vhu4mHwilH4i+VSeCbe7tt5vk8veDQ9gfV6NbGMTQgNZzs8WaiSW9A4vNDNPH0zD2A1lv",
	"Ob+H37GqBJFWSWQcFMV1jtl9UIgHpfcHO11GcrojYq/l+LjInn5EQKOsJakf+eudj3xvfEy5je/PcET0",
	"lidoejYm7Z2L9nbWPNvfgiLKBYJ/CJpuUWF1cxt7BXdU+0DVY6cz20+CkJ+4KN5aGHucdqNElWrCZwig",
	"0GugEu9zjrMgo9XQD2nY1jMDswW5pyAKZ1jhGXfiUgHc1AO7eIzSrhNFjMs2UJ8HxJqvmiO1xcrQt8Aq",
	"3QLzGo1Rn0l9V7aY0+nm49w5dRfHa3YP0WDpN6fW1ViJUtXEfOPiJ6OyzPEe6XFhj0Fe3Q3Kr7y6O0fv",
	"tOwiYke0YiEKnNM/iUQUwuTaFBAplhOMT4DWrhnadS/q3AnzBo2bGwXOkQKnW8pI4y0hEEvW3wQ3Dj/L",
	"UJIoybOznOxIjnY4p5lTQJU2cYy3wiUJeL9vnAE0yY32W/3hjzBvSPOzEmnUK2T26XmWA9c+gBt1w+it",
	"NG5wYHdD7DNJM4KU4NU6J3LLubJpU8NktnlAbgNBSvdUir5srtY5TRt9orlJySdFRK2K6fvfClLzb/Ae",
	"+rpmIBTr/+zCR2NerZ4e+TSJCExTeSBAZDUXSszG7fhwaGhBBTfEXKPJUaPm0NFq8zevHi8TLvnKdGAb",
	"ADAJRdbVP0Owxai97uQcFjjpnfIZoyd9CfINhFBeWmkLwAcwECD9G8644oymVpZEDj1l6j/+Fow88hTC",
	"lWHuN1LFDmHpoUfAKtljtOpq7yOy6LoRQfVF6vzcdaoqYOMwuedE0YECyE0Zxp1zIBzv+NHmgY3ANBnq",
	"yxxmm2DUzb5v1wz4DNOQeJSd5zzbrWPyDZzrDoPr665e7cpDhCFUR0kWhJxp2qL/unn7KzKTesA0q/xM",
	"GBE0vVFYVXIgeQh+Dyj3tChzgszPyOxxfNN2ttCu3wzYltPzkLyTIofOifWQb2kpa9+OS+CCMMtki6Ge",
	"80095U1VFFjsJ+V0JS2Iw4ipzY1O2ADKA+J5P6Z84Ki0n/9F7qFu+dqsSUcLmBUZyUlsyhu+UcgMODEc",
	"STIaW6S22TKqFsiaDpfZjGL6i3v5etdfvy6ycyB9Dh7Nw7XAzHjvObnxDdx4rthIqKg/TZCMCpKqW23y",
	"9M9aTrWe8/76lak/M2MhM3ejiLClSBpJ+uxIJCsIUW2qPN8f7DBsgTK2nWguSqW2Yf/mlS2YQrhV/vX+",
	"+jXUvpSEuUTBteAPXYdvxCI0VVYTiriwlDylECx9oMr6l1uAWKfVhIwWt0W3fAhXNwSLdPtKkSLgGWeK",
	"qn3EK/IGq3RLMmQGxTXnoAxqf9sWRX3cVetIsPeGpJxlWOxrd25UEYoGjK8ELSbOcJxZb07r/DaAT52V",
	"tQhgi8NknlHCebzzDQg5A21UwMUgnakEfVwjaMgZ0JxfNqcMCh4oS/MqIzZUqjiSsDuTeLRqQj1yhTAb",
	"yruIpi+2L9ig37dLcVMfPKFS2dG2qVVOVk0t8XfdWuII7jy3yB/hAkZDcqQ1gCMOdF3+aHHr1TmEiiBP",
	"O81mB2G+bdeFHJSlaz+enEfXp3E4nvgDwYIIZOtMopHEziZdjM+DOLhjfXW/LDDNX/M7yg6N3L5sB2w5",
	"1BjQHUEY7YigG1uiWUfAxhIpu3IXRoXgfg8O1GkpZ+PlLdxVsyBtRDL3j1DeWYTVvPjGYGbZr+ThtKSy",
	"yNXam3dqTcRjFLkHpCyNhYd6Lne55VWeofVgqKh3CZtV4uzwTaWQXJMyxykpIDo1o7/An7f8oqklPiRH",
	"ppcYul4JvqF5nK4QLgfxY+NRnNXKvJcQCc6uv0hNZz1dn8x4hxUWYVNFHzDzO5gnrmJHcZTmBAtEVcA2",
	"GT3Na8rDS60pj60xOqlVr2/DeRl69lZGBvohx+ze2ETSrqSxt9FYbQXhIRXVlEpUZcmFap3bBoAtZllM",
	"SJUmom6GnKOXRan2bm2tfwqiaR+cOM4g1wRn0MAjKqKgZE4QnPntpgYcNhrpBRb3WuNsPKV/kUhPhPRE",
	"wTq6aJ+FdqFHAJa4VOt4XaOn4LlCOYFSeOaIR+t0+YBQEzxGoyZ7SY/xUxb4AwPdFWcFZZBeoUEK199E",
	"vOntBRrntPWv+6uZ/CRTuaboDtJ2KlkSlhHTkaPgu1hS/xgyD8xmakN9ZEZTexLIaprI5TYoMEknc1Z2",
	"O5nO2Hy+cXdo4lzYv/D+CJd7KShLaYnziL/jyv1uExSsdQ/efUFSLsJix8r1KdETe6MM8SlsrOHJCUHC",
	"zrbqqRvIPkZoe9VAPv1Gem5uI1poiRXOljju/qnzRCzY+jKa4eIxKWMbQQnL8v34GYrdIjYnC7jBXiOj",
	"9LFzdUCMkWNGv40L1X3tHpteMuCJiY9eVuJIDiTcVPGcQHORQax/g2lOMm/qiCI7LWXRgzCet9jBn4F1",
	"NSW58Ddt/u4nWNZhvP7WtZ5dYpRJ5ACRHU4pnWKoQyGD4lq8CQVVDGeUHW2fW3yEsFBft0+Sprh0h4hh",
	"V/SBkz1N1nTyRE0QQvchALhyCdfBxgKHJMV19OBA3Cyo0F7znKAtaMPGKmx5EmdUbN8sosquDsoIibL9",
	"MWra1BjMQdN2GKXTus7rAsjzlgoVba7TTUqZ7+7uMtw3cI0PZOjMX7bxtZ23wQVPOIBf4Bx0uT+qrtar",
	"L8H3Xz/HmxLOSlC1v9HQW3ctREyeV6aNJWzL9BvXf27W2ipVmgaQlG0CdtALzDijKc7RL+/eXUH/i5Qz",
	"JXCqapv0HRFY5ji9t46y8zo0fJk0vxm/EmV3epJkleyIMG3Kkmfn350/g2zjkjBc0uQy+f782fn3kECq",
	"trCdC1zSs3uyh3/chcpVX1OpOn4q261DnqMP3W4q7ieUYsa4cq3n1ZZKVyUN2pGsxMaeIs1MpulBZpd7",
	"XtJ/apA6bTv/+uzZbJ06+/36At06681oiVInObc9v6ZUED7d4CpXsYXrnVz0uo8CpzlJCgio0agpju+k",
	"ZlP9J8DKx8dVUnIZU22JRBgx8tD0vgl0bawbrmCW2ditobGtRna9Vtq0se1hgDpJXXb1A8/2s9El1M/o",
	"sX1ibZiiwxrfLQRCvJerQ6HVM2dlAgODo1KYCx5Xzem9+GwalT8apshJKEvpGjqHSvDhOuBHObvLAz/C",
	"5DUP+G9URGI6zZCLpiP748ceBf8Wbw1b9zydEcUGGxNQXKntBRijF2DSwg0YPH43hGX68HFmLJl+mNrl",
	"RstKc2e3X1Af2Z0I+kJnLhKnn3Ts/jobFOFE+sC5a7kvDAL/qEg1D3vYCz+5/P2jzyyAIruYdWn4HKO1",
	"gR63APX3cXZ5+SndYnan5bXbR59hNtC0zOVnaGndP6R+3LPNP11H0UIMFPNHTeKgGe90v31rgHFcEs2M",
	"AjvCLi9shuxkjuHw3zuqttX6QutZa5zeR1WyF3UCrhYmP1P1S7W2ubmbnD+gSrpWkO7VAOTmNFyl+Qhy",
	"SQN3vJ3bzAqTHizmOw8yPK6mfeE9kxC4Hr4Ynxg7g3n50O+vX6EHLBsxnlXaskB1GrBQwFzfG/HYvYWb",
	"rGrQqiHn+swliLRXMWnXTZp1409dnnd9vprKuiM3ZK2gMuSnTJu4W08XtQAckr8duD7bjLyE+Oun3T+x",
	"4AskygfY2mC8h83Fb83D+Ijzu5wcLALhq9lFIMz6bxH4f1gEenw1lXXnFYEGgFNFYIuR/y0Cn14ETuMj",
	"q+bLC9vLfIox37fbLS9AHmorvfscvdtSiQjLSk6Zculb0jMwUkHA0YxzJLBNr8Xa7nB2cp/DDCAvDMQ3",
	"9YMF48a9kzELGvcWj6h5RyGA+lYnHdsJ9uIz5Lg/XpieYPHjbLpoaRRGG67W/txQymgfn2bGfjPYg6+g",
	"oSciF71c2j3U+6fQZMu1q1msmLd4M1jH4ISckStsy7MApTzOaDWWD7DImKe8/fpquCge/Wxc4S5iYcuA",
	"TBJsr1lia8Z/+BmUnc/bS1NmE2s7Uau+v7295UP5rPcA2QRlx3sRccJo/23RCcP7L+U+GbuPBBR+C1F0",
	"/uhB2qFnjLWnxRFaVSrop6bdrXrgZybIgKy+5t7uXZmmKZ+ohHaKaR3s6j70UhffUSYVwRniG6Nz6s8w",
	"yipDlGgs4kW7zdlyEYlQNdATqzhjYvVlH91tstTYBo6bNWQyAlqrN8SC8ZJO17vJIv3ic6cLwWNUyF9b",
	"7VyL1bT3fFKo/Umbb38mqsO0J9zqP375y7zzeJEybSJnJO3PRE2lK8S109AzoaBxyEAV28ovkoPHclxJ",
	"n/UOoBdAyLqQyz0NADUcTJ+qUCVfm+b9gsL5yD6/wIuXP35lAi+kR87KemaBGaXKhTUvJrkHrC5sIkCx",
	"hv3n6Lr/jEWKGVJY3BGFZElSurEp7c1TFs0TJVNu1jkMkGV5duxBly+SQjDwoMeYILW0f6Kr8ggjKMDb",
	"TvkbsY/cMERZ/xKl4A4gQhKUbgVnPOd3oMlwkYVuUz2la/kzC39+YdPlB7LhgtQvrD+B9RJomDTGnI6C",
	"8xsuRUNKx4k1dePmyhXXfKV5ySm6incdMhO1s9ZzAV+/wOsUpT+xlKs7Y/X5xRW7LijAippIAVaZIq/8",
	"1yNHZFbrocmxC/nXyMs01vwy2R6l2qOcmvZPww4Z/23dr95a6Fa4jYkSH7HL+kFaSx3hE3meZR0+ACET",
	"Z4MXESu8To1dE1RUCtt69I4TOMuW54H5pVLkKegnthsmMKEzHTyC2uM4p7s5y45iwUOF18VnW9oykv1Z",
	"8J3N/vS3vRG8WI6RzaoRXn4ijU3zw0Fpp/6zabZ4Y+bolJ4zyhsnsoYgODurGxWWVbCVl7jvxayg8YTa",
	"Cl7dbVvaFMSYsRpxcug5204DnH39bo5ed49JsupvoeOFrcvIljhmS7siDMEMoYc5BrqXn/lNksYUnvoR",
	"Mv+bdrK4C2XFS0CwIAh6yRH3qj8VaM0rlo0FpPpvFCxZCzL4IkLI0d579WMB3YX0F/GobEBoY2hKPEfS",
	"O03CEHnNyzPmgZmDrKX+ow9LmjzRzmFPbPwEnrqYwilLWkR9lhnlmIh0uPjs/3NMszAlIUazCHJWSG5E",
	"CktCzHTYFeJ/fNCtHyCWbSI+K7HMPo8hVjS88RK614F3N6PS/v9JxIh06ZuPGEvd56eJh2dPKx6cFdLn",
	"hSV0h1PEw5i+4F4s6z3xGb5KVsafax/nlilhGWV39WM6A0rB4ebvov5agOndviSHfeG/ZXPclwfk2vTz",
	"c5b0AEWfnwlmLLTfuZtfiWov0OV3x+JbgnO1/XM05q/1J3iuJac7woiEJ4th8eYp8TrjEB6TpEzaNLZA",
	"HsAvsOySmu3kmrobA65BRN1iZLkE6y1J78FQ2DocOMJYpBjCmCYSgzQJ161CInWrXwOM3ENo1NIo39vq",
	"9CBxXNu0RUMvg/FAy0lGYqI150oqgUtXtTB3ikVwGY8wDiGOMhdeS7yRtIuBfqmmedqq1RBk5TVDhZQM",
	"2yMupKL4ZFpKp+i0iP0C3swh5cFUgLq2swu4HAxjlDWiYwxhnIIXn5vGo4NWww3fqLPMMx2cu8mk58eq",
	"0ofNh2Mjd3XE9QB7wcW4FjQSBmNco9lOpyO11fp6FqQudUaPiYQ+e4pIqDumdR/A+U/oaCTUPHww1LhA",
	"/04aZR0esYAHd1PBpax7FkBbZv+pmMDdeV0xM99S3Qpa7388MaHD768EFSp4a8Jm6M9K9ZvpT4R4LGFp",
	"YhiiaQdzfL1L+Bn6o4pdOo/jn1CB8JRlLr0WboEWMbA9kgWbUi9R2tIliscAH7znEdtMMBoMaHToSDlL",
	"PAZgcx4grHhAAMAD9ikoONYHCswE2HiDi/mtVRxaJkbBcV9/PccK4SzzW3ghbGI5wogMqLuFwkMYY/eE",
	"7rTx2KnZiMUAPnjvDS3n++81WH9in7/XvK7PJE2vvgVd/P67ThMO9sVnv/fftKKGRoRMr2jwyX908dgT",
	"Suxh+i1VxTBKvFGN3r91taWsjWNoxdurUvAGwkmHyoasoNHqhLlJuJSif5wMeCIecsq+d7vNr+6fJgMO",
	"KEGIqXgmGQQzxG0z/3yvec5c7PZJtZHGZh15frLe9xTJth1ov2hpQQ+WuB/xQ5eIT3E9HaR+djnUqsij",
	"dQQwCvFNi1MnXlotJdN2+/1GLq9+L+pBqls8za+u9myak6jdTmI84B403/9FwntCcCGa6MWMV6I18E5m",
	"jyNSFRe/RtsPP32pyzRuQveuVEvwRW9Wu0aUoduhrXZT6N8/asqZ+J9hE3hhBzpCX15c5DzF+ZZLdfn3",
	"Z39/BlS2a/SfyrEsiXMXmHOtW+BGNT3WXcBMM1fHam08MK53pGvzktMNSfcpePr6M8I+BuerPTpevMha",
	"kvCoT2jW5lmkXrqta1SMfcdAt1OxqbYtCFM+qK5Xa3/WF4JLeWZ9lfbp1xBc1jHWn6ARoTW6Vp77xtjO",
	"9k4NTeyxTAA6P5HTm9/P6165gs6V7QuFvZZldpF2umd/HRekGKZ47S/uT9CO0aMNAQdwfwobUA+gMZSE",
	"1BAzPlknG+Xx4+P/BAAA///3QpFQIbsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
