// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x93XIbN9Loq6B4TlVuKMm72Ys9Ple27CTetWN9khNfpFwqcAYkEQ2BCYCRwnXp3b9C",
	"A5gBZoD5ITmyvbs3qVjEAA10o9H//XmR8V3JGWFKLp5/XpRY4B1RRMC/XmQZkfKKFzTb/09FxF7/MScy",
	"E7RUlLPF88V7VuwRZVlR5QRlnN0TIbH+TaIHqraIM4IwTINKmOd8sVxQ/eUfMOFywfCOLJ4vzKBbM2ix",
	"XMhsS3ZYL0hYtVs8/22xI7uVBmy5eODiTpY4I4tPy4Xal/p7qQRlm8Xj43LxYkOYevPqCqttF2D4EVWS",
	"CERzwhRdUyJqoEr9TQOTHntL88VyIcgfFRUkXzxXoiI+eGsudlgtni+qCkZ24XlJ1lyQd0RKvCFvXvWd",
	"pCCqEgztzFiJMkGwIjlawRRIbQkSZE0EYRnJ3bDUkZqPbu0os48pcF966Ewdpz9m+EB9Ajn+XC8rIblI",
	"HOcV3lBmwMpgHFoLvkMYlYLcU15JJIgsOZPJ4zOfBWfWheH1PWHqmkheiWwAt+6W6Csh7BeI5ufo2pyB",
	"rP96q9dJgVUPmozPANYP+5KMgZbojyRacxECPgpEgMEH8v8Ksl48X/yfi4btXJhf5UUHvAboscBqCAHg",
	"XvA6UHWP6p9kn2QgV2/QHdkPE/sd2R9P42/pjqrE1t/hP+mu2iFWacaI+BpRRXYSKe74SEkEKns4RKFn",
	"D45iZ+ZcPP/rs2fLxY4y86+/1LBRpsiGCACuZmnxk7I/D59UwKGOOa33Lyq1veR5ilj0z1zQf1m+wHNi",
	"T0qz2D2wV5gClYLf09wDuM0beE56YU3AdqOwSlIyrCz1CHSPi+pQ2GCGicDdVKsalBQ64SYi6Y0cxqw/",
	"+nj0/iKJSEH3y6gXXb/7x8Px0ckfKWDqAcMQ1bLMScEawywFkVWhWbt+FzXnrEFJUVYL1sNgY/dUkQ/8",
	"jrDBs4OhSOmxidOD3ybR+qMebB5+I+OW9LUQXFzbP+q/ZZwpwpT+X1yWBc2AX1z8LjWAn8c+Z8GssHDr",
	"PukBnhSiR9iPAbCrN/8kgMNS8JIIRQ3AViS8xSoijenf9MVUdAdYrBGTY0XO9F+72FkuyJ+llj+iU76H",
	"/8EFcu8eDB6xCquKAq8K4lDSWZXmYx/XAfJaLgq8IkV3tp+qHWZnguBcA1LvAEafx+eR6raSidN9i6VC",
	"fCWJuCe5ViGOPABB7vldYq1rcs+z5pTRw5YweAP0BrZYohUhDNkZDgdBZry0Ylr3Im6J2hJRr0olqE1n",
	"8E2OuGgYhv2bhsNpa3rogKrmlg/YSg8/WPGK5Vq6cRDBoTRb0BAGPKxNN8PHUa1+JxmQgIgCA69MKSjL",
	"aIkLhCu11YSaGSVNv9JUOjobQbmPPuf6bWG4agsGR90BspY+G2hOlsOneieGe8hLXhQkM8C3GQkIi8H/",
	"9LEzy44e67WwEBj+zcif6tYqSyPUMEAaznNq+Yp7hrAgCN9jChg6Hz4rADq69Ty/wkJRjSKmpNauiFTd",
	"/dsDlnEsgxiN85refNUVHiN3aIPMKTyv1jZqIKI72dhXaPYXwE252g/Q/sOW10YJfSxgIhnFo3dE4Rwr",
	"eDcb9F95OzOXMvH88BL/URH0j5v3PyM3FWiluCzP+AMzHElUTG/R/gGAQ/Ca/wlAJhhAc+I7Ldd3Jd/1",
	"Wl+ie4IehJZI9ChY+8XVm7M7sj8L+YBZFsO1kz5P1C/RLWcF2LfwmtzCdFHOqDcgRjBmsxaVKKeCZKrY",
	"I7P11R5hY+XiQv+jI99N4tMGmiRlvIK1YWV7vxvw3bNxED820/S/D+8fGGWbZnMxAI57FaoyT943kAlq",
	"ejQjJ949wMAA99V3L8o7FgGpWAKO3ufgyQg2lWQ9TyiCRoVBoO0DRcKxko25QP8h8o1Rl7rCJn5AK4KF",
	"PhI9Anhbw93RG+AwjTWCZFhLv/XRmcdb2WcBS2Mp5AorkLuzSghgxIIADnFxPk4UctrdJMFHA3VKuQfe",
	"4G9B7KnU1ldiw01LIqU9jb7d3phhr9k9KXhJjmJPbkk7RQxm33vQhTl0CfW7Hu6ppCtaULX3/EzTPEfL",
	"BRbZlt6TvJ9jZIHLQ2PQfOUhb8V5QTDzJasnFtZgai5ijq5B1hnM1Hvq3k/nh6r8PR6kEXq/VLV/K3bC",
	"H+iOSIV3JeJrQN6OS4UEyTQ/8txnh2nPZaNm3Ga8YhEAfq5t895g6VgiWOOi6kXb2r5cyC0W5Lag7A7u",
	"RlG8Xy+e/9Z/L/2zvdHfv9WfP35qS9mXlkPDGkiv0XB7La8aG2FA+JmjXf1WkIJuqGb1paD3WgIKPMFd",
	"0tDslKqCDFADjDk/iYh2kGQ29uHmRgRt43GpZQgNOpzRpuArXHRPZuIjHnsn277zLl0mJMKa4U0TDuNk",
	"1eHfPdKGR2i1ebeLVBGx6b0U/EHztN85ZeiX67e1rBKbsjlbQQefVidt6GWHdn1CASN4A78BOQNeFmJU",
	"g6RtZZRF+fqHy++///7/tS3KNUbbNrRJvPlUJuFReoSziSCMSiIk7E5PywXCHS3C7evkmoSNI8j79Qb0",
	"rpIKrQjiO6q0vL62YoIH3gkYU8RoOUxNKekVl/T2zmii42yUkmSCRGjvqsAUrEE15s3Ijo4Drx5n2Yir",
	"4oCrV+3Z5wZCHBKXBt9jhcVtlO3Vl8YMQnSHN0TzvwibG7wbK8p7VigFX9OCoBXlo97enMqywPtb45JL",
	"TdulOy037Eq1P0cfNPsm4p4ItCGMCKyIRBgJzHK+Q9vwytrlkF4uemO3mOUF6dtgtSpohsy4c/QR7EUG",
	"qKV5SgwsORH0nhhtFgQg/ZsD0Jn5HBiDxzSH/VNxJBUXBHEWWmMnGDrXuCo07XgGyTYQbxjVWnvb+ulZ",
	"CF6ZacBo3kxkTXHmaGcwhL7Xv8ktLQGmogaKkYfmKA4wdE5hsylDY5rNerbpE/BZ73wG+U6SvTo/wyhD",
	"yFhm7FkQOywT5mqmSkPuS0dpxtk1FDiqblT/EIm/tu0FNfEEmlhA2HauJFWPNTP06tf1hc+OUbR9DSDt",
	"5/LcZM5QYCL9zE7O4BEMFRb0fkcVjGkM7h2V5lDf2BStENXXcACYwbMaq+U1Ul7XCsS8gzmdope4ExCI",
	"5UdspcVwPTLFPB2hNQGTaE0LZUwvI4IXmjDU9NxenKubvCfcdbI9Oww0HW0WiUSafloObqH3hHpkTtCQ",
	"cyTpBqwEZpi+b5Z0yWrL+R38jlUliLRvB+PwfqwKzO7G68cf7XQ5Keg9EfuEjHjwLQB5vlG6PSrsXIFi",
	"b8yyhYsiPv6101seIWfbyFPvXoTbWfF8fwtqABcI/iFotkU7+2TbCEtg7uGFqseOJ7YfBCE/cLF7b2Hs",
	"UNqNElWmEZ8jgEKvgUq8LzjOo4RWQ9+n31jjJsx2PuiPP81OXMBvLZ+md5Hmbq1IwTRv22HapyjB7wjn",
	"uSBSIrXFyuB3h1W2NbJrlpFS6TtZR/QEFGpWGGN9TFnha2BaZviDwDn22egcbEocNHGXtz3mu4dkjGbX",
	"5G8mi/KqF7DjwIrXnm+SBS8APFj60/CpJAktrtc2HHFQIZVFtellqUW1CZRgpjdd0H8RiajSckfBH4jI",
	"sBxhjQBo7ZqxXXeCXVuu/WgAzI1x5O5wtqWMNLo4gRBW/U104/BzRO78gZIiPyvIPSnQPS5o7oRchWlh",
	"5Wth0OH/vta/BvJlH7f6tf7wFcwbEzctkxw0E5p9ev6iiCQC4CYVRr0V7/5rcjfIPpM0J0gJXq0KIrec",
	"aw4wjGabgOA2EMV0R8rpPhfGElKLOM3jTv5URNTSoRZJLG+3+UBYhCJwJELC/9k5gYdUo45o+zTxz0xj",
	"ucfta4UpSszG7fi4w3dGmTtGXINZGYM62MGS/Dcvsc/jNfzKxHLrETJ5DNb3cwKfo5HE3c2Z5j/s3PIT",
	"utO6HOQb8Km9ttwWgI+cQPLeT7zqPIPAgzjFmxntEJZNJXsr6w/hp61EDPCf64bt1I+nlembvDjgptN4",
	"nWM/E5mOmzJ+ds6OcbiJSasF1g1Xb2ymC2zD6dq5umF6sU8wDYoHSfiU9zm4Gt/AXW4R+CRvj/72TOPW",
	"+HnMpB4wzSo/EkYEzW4UVpXsCfuD3yMCPd2VBUHmZ2T2OLxpO1ts1//glI2y1R8XFBIN2YjB865Hvx0f",
	"0ejdXNl3b63lf0tLWZu8XN4ILgqb/DmG3Os539VT3lS7HRb7UakkiwDi+MHUKk/LiQK50emIQpM7fVBA",
	"4b+R1axdweKk4YwzqDY5KUhqyhu+VsgMODKTkeQ0tUitN+ZUzZAwGq8xMC0Z6UsYPzvPcbc0SutC+hQ8",
	"GAVvgTnhO+z4xjfwArtKCyIdaiOIyZe61WpX964VVMtdv1y/MbU0zFhICFwrImwdBn1I+u5IJCtwQK+r",
	"othPNloGoAxtJ+nBr9Q2bmO9stUiEA5qX/xy/Vbvh5eEuRDklYmsHKOVmhITIypYYCl5RiFcBspBgZ07",
	"AMQazkaEWbktuuVjZ3VDsMi2P9FY1mQr12BKTOY0rh/q4lt6Cgne2pUmS8t3lOVhES1zjZdt81xjl6tN",
	"dWbFT1H2WQsRI3lGr5J3iRlnNAutTD4/j4VDiggB/gBeVYHZHXha9aDwuQErazOhqZwDEzJalnHvLRfK",
	"FI0iD2ggkdQLbIgHMlwDr5sS2H6IrDpayDzcwnQaqm5dcSDWZafClUZ1+rInefzgpY2H2th9Hm7iTL2E",
	"700EXzmpMFlndn1GcoydFgZCPB4cU6CBnJYbtOUBU1VqRLkq9/LXBavimS9/xIvZGPQj+LW+mBNNL/Wx",
	"PbTp/FD8t0jawN5HvUkv7CTxrHn4vgEBrZ1lOCl9wH48ug7N2CTYlyYB1mYtTrNABCV0ojvW4tvrHabF",
	"W76hbGpQw+swloFDBhu9JwijeyLo2lYoqj2xnRCG/k2YUTG4fwFD/uFh6+b73EWta6nT5UQpjrKCYIGo",
	"OlkMu1tuRXlqnSPD2d0KB0ehuwnCIPTTFcy4JmWBM7IDW36qZsahseKxjTRB4QdGeKdslG4BsDhZS2UH",
	"eLcehvocUD5HloTlJI/Xhk1Q+Lgw4+H0YO6ygTX5Vcz9I5bhmTh2z5PcGyf8M3k4LkQ4IaF25h0rq6YP",
	"d0K86pAjvuPclFteFTla9Trl2+zOrpJmeN9U/KB/4+UJraL+vOUXjSv0ITkwttDg9cqkNiXxCoFJ8MBa",
	"z7/Lqwnq+xiT/nfSZUp10dz3JOoL9kTPoV5qvqdQzx48g+hlgdmdsfxIu5I+vbU+1SDcCRILTJZiVZZc",
	"qODeDj+ieulWFtfrXan2bm0tqQqicR+dOE0g1wTnUKM1yaKg5AC8bl7V2h6zNCSOYHGHsPT8Qd9JpCdC",
	"eqJoHYJR9eKisKS5Wsu3lLwFLxQqCNQ6ZA55kBppFu5Su+ApHDValR7jv9eQtrRYLnC+owwC2cASM0U+",
	"CBdoXHBWVvBXM5GgJlW+IyfoM93x+4kSw6FxoyHUB8aOhpNA/OhIKrfmpFFax5WgOyz2rUhqox36auD0",
	"gOlkeblj3DjTcypNBmf9otQ1NkHiFCTjAih/hbM7W1KN2W+CCO1BAboenQgLvKoLSpqINSvkemBEacM+",
	"P2PMg/bh6xW3GzF7ZHmm1rbqqRvIPiVI8KqBfPzD+eIby3w2McRrQQnLi/3hGqMN0gVqSKqLLfzYuVog",
	"ptBxQjehs0V/7SaoTnT4kZHwXpj6QFA8PKjpIHHz3kIg2BrTguTe1Al5e1wMuwdhOpC9dX4G1uWYaPNf",
	"iaDr/QgTV/xcf22bsVykrGG88LLEcwzGWMzALQTJ8lgoyLQ7o+xgQ5k9j9gpfPRdMF9F1dZjCoH1O4Qm",
	"TvY0aTSLJyoOFa3crAFcugyco0twtsT1SBBDVO6+5gVBWxDajTQTLft6Avn73SwS9zSXZ3+x4okUOtYT",
	"OmnaFqG0Wih4/Sh4EYhQyZqJ7QjB073dbYL7Bp7xnnDJ0+fxfW33rXfBIy7gF7gHbepPiqv16nPQ/ddP",
	"8abMQCWo2t9o6K1VGVyXLyrTTgW2Zfq/6T83a22VKk0jEsrWvC8M56cPH66gQlbGmRI4U7VO+oEILAuc",
	"3Vl7HmzFeBIWzW/G/EXZRk+yWC7uiTDVZxfPzv9y/gxSUUrCcEkXzxffnz87/x6yC9QWtnNhauPo/92Q",
	"qGFaVYJJW0LHFjyv65/bnBBXdNirgd5ERms02XZ6wTgqtYpv6phzgeCy6h1q2jJt8HItM1CpTJnhRauZ",
	"zF+fPTtZ/5hOIeNIC5l3mOENAfHe1ROCMbb6TXyBGuKLTu8boC/HP2GfaNdeQiMcb6SmUnsInx6Xi5LL",
	"lFwLtbzWVEh1lhVYWrxZxADuCAXnThpzQfX67iDAE5WKCNnFllcBaVHn6b7k+f5kmIrUdnsML7R1trRo",
	"5S/zQJDuOGQKqlsZ9KSkcmnLH1r7WIxGHpfuYl98do01HwfvuMZ8mwQ1RVAlYypNiPofiXJ49xubJtxR",
	"zZALv4Po46e5L3kaVTYj/qSoutnyh15EASfOtimHvL7NbYw0vrAlRAJA5dtGKQix4sWUnAAxp7/OkZiX",
	"Udf5CaiiDqcx4Q8npAoz8/QLfIFLemarwfVeZJ9pu9qbrqlom5zO0Zs1YtDM808qlUR7opYwksqGfaVu",
	"+4uS/pPsv/I7XxfGe0zV4sZ+94vTcwAfH8FSk1F/AZ0ejMUrKgVcQ5eyaSSAMMttUCiUAm0iALqIv4b1",
	"/x1w7wc6zId/c15e95MhzBs8Dwvkdh7Z9CDyUQ51XE0vIPSxXRO5/jTDjHHleoZDPzVbUM/EgVVibTXd",
	"iFAO2J9XKu/0VYs93r3nYLohnVpO3/NK1KfoY/LqDYJDGSOl18WrI81vgisbx2twaU0hXah15+ooRwVz",
	"d2NnlMyDWuVfRjQPC1ynaWZm6Txy0xv68O/6xWfTvvrRkEtBFEkzds3AHfxDV79DBq9g8gMZd9OnO8K2",
	"/5buL1o3zjwlW4U5x51ypbYX4Ey6AJdU+u28ISzXN5Mz44noxnu7RPMwSmPPKxeG2D3yVjT6TJcvEfM+",
	"6v799WRQxAslRC5g4IE0h/lHRarTEIm12S2e//YpkMQIyzXBmOWsXxJZb2tNO5XadukG6GCfJpzXf2Zb",
	"zDZENvM72tBcuktG0EuxTn/QY8KoR2DwXtBlSFJt9+9MNJXyMj+1gub32orQkstROSEzT1EQ3UACL2TX",
	"1pgeoCAO/91Qta1WFxkuihXO7pLS3WWd56zZzI9U/VStbAr0uuAPqJKu+Y3rTI/cnIayNC1Bym5EBrBz",
	"m1lh0slvQKvp/+Ny3BdeK/55Rf5ptGI8CMxLO//l+g16wBJCZQtKcpRXQp94nW0tjCnge8M12090k7wO",
	"LzKktp+5CPVwFZPd3mSzN5ESs9HvD5RRuXVUZdcbS7oDb2ct1zLkZ6bbwL62rGpBmJImH3lVQ0KegwV2",
	"qxs8MfOL1COIkLU58c5pzskKIbhnKiVxvinIZCYIX52cCcKs/2WC/7FM0FDVRNI9LRM0IBzLBANC/i8T",
	"fHomOJaSrLgvL6ymPkbb9xV7Swfgpg3yp8/Rhy2ViLC85JQplz0iPRWjaQeMBLbZfZh5+nPE0gsgWAv5",
	"Td1fdljvd/xlDr0fRHBeqeBgmua3kaMPWoMMWlWD0YnycuhHYyN14SaUZUXlEq063RiCGf+/n6XT+jxc",
	"mjKbvNUKOeoaYoNWiZPfsqZQ/avRr9lbuqNq9OhLCNYZPfwFvAVX0CfoCR7LVKPJmNEihtHTG5ezFj4d",
	"TYd4HmNhDrsr/dC0y1EP/MyYn20oj4tSl6YnG3gC9Yuf1VFK7UbMdfM+yqQiOEd8bdvUsg3CKK8MQpKm",
	"6MuwBsp8BulYtvkTv19hhasuYb3uHneIlvq0gdpOajEfAO2y04Z4JnM5ahXFSVF9h6Vf/M4pS4tkpu1F",
	"+zZ0yp821bzphpH8jKYs6O3aqzPRbqrE61dGuS5GIjhbI9RrtGiaXu29wz4p6egzauPVlndqVpxESp9b",
	"ZazGhUxlnd74sYq0nfiJFhVNe7b9j5/Clz6JT8wXSTWWS4wIq+rW3Vj6ZT0gqsoVIbHGBGgbYzBal5/A",
	"RcEfiM08Z5pXBxO7fNdUZNY8RDBXnNY3ypFmCd46/MHqcJkLJ30Nshs3EFHWZT0UVC4iJEHZVnDGC74B",
	"YYKLPMaDtLTpateehPa+sObwkqy5cOVkanVmTq4Yqfw7xBsdBmcIHm9Q6Wixxm5aW7jiEqQjJ2kq3uaN",
	"I1+0oBng18zKol0LnzhQpS7WGkkzsIiYQ9g2LnDUVKKMEMoYfuV1vB3mWf5g6/hOtbw9Rz9zdmZ+bdlD",
	"jAZkvK6l2qOCSjVsD7nyAf3aZax2dYAhVuIf7LxmiGCpA0wSL/LcZBBIw1/S+H+5R3YXS4TZvrFEeBCg",
	"Hd673oVe9pctSnOOLhNadB3vuNIPJGabWGDzizyfn4BOz9Re5LkP6hcSzkZQcF2S0cOnucsnJOAXeX4Q",
	"/U7lfRefbU7xQOTejt/byD1/21ZXTV+GtrohFS0KpH+VaxPzJ5WgmYLKNTt+j4u+/uqm2O6R18PsJXFD",
	"nkiI1FQ2KRDRb71uc3FPHIyo52zLTWVwMMeQnCA4P6vbAJRVtN6zuOtotVDwTG0FrzZbE/jvKqUxU/Sk",
	"XSYzxLWeM9T4cP7166idqnKjeODfYtcWW8Xf1qw4LdG8gzp1LcuZBJwdSS5g/DoD49eURCHPJFoninis",
	"iXF29updi0MdmDrk7wo6tr81lrpvxwbWQN2TVZSwOM+bX5RY9GQ0dVAG0nTamp6T9G9OVH660lMQlpe4",
	"dBhJQQ+DM7+A8LCu+GA7twZftdIcrBM+ndVk4NtRZcyyakuoQCtesXzIld7tlTpnelNvZ9aYm7DTfXgG",
	"tS+KAQ/TBojwjMb4oo1fLTq96YFtWl1PMjZ128/OaTFKVtZ+YttRpOnuGFqZ13sbw+sg1SS4xMVn/59D",
	"2pVJaZIJGKK8I5EWFSOnaY+H//EkDSWCLttM8KToMvs8FF1Jp9prqPEuERcop9L8/zHoSFSyPx065tI9",
	"jmMRz56WRThLDOnQ3jz+suNYxLDsQGw7tv6nBF17RaJseyhDkbaolJY7M8zQyvUlMr/WksPSHpjal6b0",
	"hmsC1SNSTDcdzuooA5g+7Esy7Qu/O/dhX06IMezGJc4phScbakejtQI6O70I1iLk9h1x12JLcKG2/xqu",
	"3IWkaUBd0HvCiGx6nnWyy02ZMQjpw9E08h+J+gmWnVMuHp1FemPANQdRl8CZLdz7ckuyO/TgdUfRKgeV",
	"qCo9HNnzMTgyRRAHTTBh0BmwoKDWIIzaA1uyqCr2tmpDFEeu5Pesru8+zNQWEGO9XnGupBK4dFk5pzaA",
	"QEEGnGW8stVMvMbcDWrcsTjcXHhF3QfihbpY+k7aAuHLoJjl0us3As+DrW8ek3B8NM0lkrS6sHwBh1Cf",
	"7GHynF1nl9NLHUAXZX3MKUIw/o+Lz01nj16V44av1Vle6x3Oqm5STxrxdiiU1Ejjh0ZM1HEuE9QMF1sw",
	"q27RG10wpt7ZgccZdJM6yXHOdScPiT159hSxJ+5a1jXr59ADBqNPTA/VHgNzxaRttIpwJrg07LlJYQiM",
	"2UvvLViaIIQlPBHTLE7XFTNtP+cq4BH0131ikmi1R42KWnDcNmfpxEFJMLU+fKdKmZIqWtwxQo5HKxYJ",
	"hlKaskkmHERefIZo/scLDGH/Y9ICmoQsG1LSlw8AQcHdpjStEBKYu1FgYNojErPg+w8aqvndEZ2y5JHi",
	"SbA9kkf7Qc0R4N+sYyImmMWURxVNpeo2ZYzwOTRSdsJkkHY12Kg0cGJN8DN89KXT+XE5VEEN7hhsvDmL",
	"mYqmReXyAHvDrgTPFLPDtafRaBrU1qgWhsdD1jkk3cIgux+00RpmK6kt5WT46HXnns+50Olw9sROBa8s",
	"e5dAmir08/oQvJMecbEvPvt17cel6jSsZHyejk8AB+fWPiHn7sfgjLk5g/gbIfw3CNLKNFQ2LqpNPPPG",
	"GzxURb7VRvBEmJxLPziMGTwRKdWtqJsnbhZvwVHM4MLKgyNKdaQEQBMghxnitmNdsddUJ4iNuYTYAoh9",
	"Cuq92eiWOm45rqu2mP7RIuJTZEy0oP2iJT47sKQ1l49t9D7NGzZJRm1Tr5WnR6SDwTjE18HSI9+2QBK1",
	"DW++kTeu246pF/MuNeD00TLtJY7CdxhOPuGtNN9/J6Hzr9cO4MTPptUJjyaRA0K8Z39qwzbNX+rBTWvd",
	"nWfXIn3m19eukiTr0F0Wdkf67ZPGnfEpGkKBVrPQGun5xUXBM1xsuVTP//7s788Az3aNzludcryZjeWU",
	"QS9C03PMOeA0lXXaiQqFoF2oqQFXF4FdF/zBlGq1OdyR6kLeCrC97vy/UvKgp3cdDmMuI+ejqsXwetKm",
	"a3BcVPHBa5mgvAhJXJupAhOEA9xUmk8tsYRMnKUNvYUCy9Ei5bX9w5/aFV2OnLsx8B1onw0tgd6K1hKY",
	"PC9/Wntuls+a+Y33zr7T/sQehScnb23Bzu/nBgWLNEGz/kJh1Gzs4Fi+RCSnyseMcd54icT1fLUdvTvV",
	"S6gdZov7+OEFaE1I3nRL68oMdm4betCd2bTF6ovvNFmfpB02EU7divx5/PT4vwEAAP//yND9CC/dAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
