// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package sqlcgen

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, principal_type, email, is_bot, deleted
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, principal_type, email, is_bot, deleted, created_at, updated_at
`

type CreateAccountParams struct {
	ID            string `json:"id"`
	PrincipalType string `json:"principal_type"`
	Email         string `json:"email"`
	IsBot         bool   `json:"is_bot"`
	Deleted       bool   `json:"deleted"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.PrincipalType,
		arg.Email,
		arg.IsBot,
		arg.Deleted,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.Email,
		&i.IsBot,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, principal_type, email, is_bot, deleted, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.Email,
		&i.IsBot,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, principal_type, email, is_bot, deleted, created_at, updated_at
FROM accounts
WHERE LOWER(email) = LOWER($1)
ORDER BY created_at ASC, id ASC
LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.Email,
		&i.IsBot,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
