// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"
)

const consumeEmailVerificationChallenge = `-- name: ConsumeEmailVerificationChallenge :execrows
UPDATE email_verification_challenges
SET consumed_at = $2
WHERE id = $1 AND consumed_at IS NULL
`

type ConsumeEmailVerificationChallengeParams struct {
	ID         string     `json:"id"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

func (q *Queries) ConsumeEmailVerificationChallenge(ctx context.Context, arg ConsumeEmailVerificationChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEmailVerificationChallenge, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (id, workspace_id, user_id, session_hash, provider, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, user_id, session_hash, provider, expires_at, revoked_at, created_at
`

type CreateAuthSessionParams struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	UserID      string    `json:"user_id"`
	SessionHash string    `json:"session_hash"`
	Provider    string    `json:"provider"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.SessionHash,
		arg.Provider,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.SessionHash,
		&i.Provider,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailVerificationChallenge = `-- name: CreateEmailVerificationChallenge :one
INSERT INTO email_verification_challenges (id, email, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, code_hash, expires_at, consumed_at, created_at
`

type CreateEmailVerificationChallengeParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CodeHash  string    `json:"code_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationChallenge(ctx context.Context, arg CreateEmailVerificationChallengeParams) (EmailVerificationChallenge, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationChallenge,
		arg.ID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i EmailVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePendingEmailVerificationChallenges = `-- name: DeletePendingEmailVerificationChallenges :exec
DELETE FROM email_verification_challenges
WHERE LOWER(email) = LOWER($1) AND consumed_at IS NULL
`

func (q *Queries) DeletePendingEmailVerificationChallenges(ctx context.Context, lower string) error {
	_, err := q.db.Exec(ctx, deletePendingEmailVerificationChallenges, lower)
	return err
}

const getAuthSessionByHash = `-- name: GetAuthSessionByHash :one
SELECT id, workspace_id, user_id, session_hash, provider, expires_at, revoked_at, created_at
FROM auth_sessions
WHERE session_hash = $1
`

func (q *Queries) GetAuthSessionByHash(ctx context.Context, sessionHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByHash, sessionHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.SessionHash,
		&i.Provider,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationChallenge = `-- name: GetEmailVerificationChallenge :one
SELECT id, email, code_hash, expires_at, consumed_at, created_at
FROM email_verification_challenges
WHERE LOWER(email) = LOWER($1) AND code_hash = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetEmailVerificationChallengeParams struct {
	Lower    string `json:"lower"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) GetEmailVerificationChallenge(ctx context.Context, arg GetEmailVerificationChallengeParams) (EmailVerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationChallenge, arg.Lower, arg.CodeHash)
	var i EmailVerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, workspace_id, user_id, provider, provider_subject, email, created_at, updated_at
FROM oauth_accounts
WHERE workspace_id = $1 AND provider = $2 AND provider_subject = $3
`

type GetOAuthAccountParams struct {
	WorkspaceID     string `json:"workspace_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.WorkspaceID, arg.Provider, arg.ProviderSubject)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthAccountsBySubject = `-- name: ListOAuthAccountsBySubject :many
SELECT id, workspace_id, user_id, provider, provider_subject, email, created_at, updated_at
FROM oauth_accounts
WHERE provider = $1 AND provider_subject = $2
ORDER BY created_at ASC, id ASC
`

type ListOAuthAccountsBySubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) ListOAuthAccountsBySubject(ctx context.Context, arg ListOAuthAccountsBySubjectParams) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, listOAuthAccountsBySubject, arg.Provider, arg.ProviderSubject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSubject,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSessionByHash = `-- name: RevokeAuthSessionByHash :exec
UPDATE auth_sessions
SET revoked_at = NOW()
WHERE session_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSessionByHash(ctx context.Context, sessionHash string) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionByHash, sessionHash)
	return err
}

const upsertOAuthAccount = `-- name: UpsertOAuthAccount :one
INSERT INTO oauth_accounts (id, workspace_id, user_id, provider, provider_subject, email)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id, provider, provider_subject) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    email = EXCLUDED.email,
    updated_at = NOW()
RETURNING id, workspace_id, user_id, provider, provider_subject, email, created_at, updated_at
`

type UpsertOAuthAccountParams struct {
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	UserID          string `json:"user_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
}

func (q *Queries) UpsertOAuthAccount(ctx context.Context, arg UpsertOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, upsertOAuthAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
