// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: authorization_audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthorizationAuditLog = `-- name: CreateAuthorizationAuditLog :one
INSERT INTO authorization_audit_log (
    id, workspace_id, actor_id, api_key_id, on_behalf_of, action, resource, resource_id, metadata
)
VALUES ($1, $2, NULLIF($3, ''), NULLIF($4, ''), NULLIF($5, ''), $6, $7, $8, $9)
RETURNING id, workspace_id, COALESCE(actor_id, ''), COALESCE(api_key_id, ''), COALESCE(on_behalf_of, ''), action, resource, resource_id, metadata, created_at
`

type CreateAuthorizationAuditLogParams struct {
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	Column3     interface{} `json:"column_3"`
	Column4     interface{} `json:"column_4"`
	Column5     interface{} `json:"column_5"`
	Action      string      `json:"action"`
	Resource    string      `json:"resource"`
	ResourceID  string      `json:"resource_id"`
	Metadata    []byte      `json:"metadata"`
}

type CreateAuthorizationAuditLogRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	ActorID     string             `json:"actor_id"`
	ApiKeyID    string             `json:"api_key_id"`
	OnBehalfOf  string             `json:"on_behalf_of"`
	Action      string             `json:"action"`
	Resource    string             `json:"resource"`
	ResourceID  string             `json:"resource_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthorizationAuditLog(ctx context.Context, arg CreateAuthorizationAuditLogParams) (CreateAuthorizationAuditLogRow, error) {
	row := q.db.QueryRow(ctx, createAuthorizationAuditLog,
		arg.ID,
		arg.WorkspaceID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Metadata,
	)
	var i CreateAuthorizationAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.ApiKeyID,
		&i.OnBehalfOf,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthorizationAuditLogs = `-- name: ListAuthorizationAuditLogs :many
SELECT id, workspace_id, COALESCE(actor_id, ''), COALESCE(api_key_id, ''), COALESCE(on_behalf_of, ''), action, resource, resource_id, metadata, created_at
FROM authorization_audit_log
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuthorizationAuditLogsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
}

type ListAuthorizationAuditLogsRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	ActorID     string             `json:"actor_id"`
	ApiKeyID    string             `json:"api_key_id"`
	OnBehalfOf  string             `json:"on_behalf_of"`
	Action      string             `json:"action"`
	Resource    string             `json:"resource"`
	ResourceID  string             `json:"resource_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuthorizationAuditLogs(ctx context.Context, arg ListAuthorizationAuditLogsParams) ([]ListAuthorizationAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationAuditLogs, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizationAuditLogsRow{}
	for rows.Next() {
		var i ListAuthorizationAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.ApiKeyID,
			&i.OnBehalfOf,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
