// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: conversations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :execrows
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveConversation = `-- name: ArchiveConversation :exec
UPDATE conversations SET is_archived = TRUE WHERE id = $1 AND is_archived = FALSE
`

func (q *Queries) ArchiveConversation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, archiveConversation, id)
	return err
}

const countConversationMembers = `-- name: CountConversationMembers :one
SELECT COUNT(*) FROM conversation_members WHERE conversation_id = $1
`

func (q *Queries) CountConversationMembers(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationMembers, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCanonicalDM = `-- name: CreateCanonicalDM :execrows
INSERT INTO canonical_dms (workspace_id, user_low_id, user_high_id, conversation_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type CreateCanonicalDMParams struct {
	WorkspaceID    string `json:"workspace_id"`
	UserLowID      string `json:"user_low_id"`
	UserHighID     string `json:"user_high_id"`
	ConversationID string `json:"conversation_id"`
}

func (q *Queries) CreateCanonicalDM(ctx context.Context, arg CreateCanonicalDMParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCanonicalDM,
		arg.WorkspaceID,
		arg.UserLowID,
		arg.UserHighID,
		arg.ConversationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    id, workspace_id, name, type, creator_id,
    topic_value, topic_creator, purpose_value, purpose_creator,
    last_message_ts, last_activity_ts
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, name, type, creator_id, is_archived,
       topic_value, topic_creator, topic_last_set,
       purpose_value, purpose_creator, purpose_last_set,
       num_members, last_message_ts, last_activity_ts, created_at, updated_at
`

type CreateConversationParams struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
}

type CreateConversationRow struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	IsArchived     bool        `json:"is_archived"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	TopicLastSet   *time.Time  `json:"topic_last_set"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	PurposeLastSet *time.Time  `json:"purpose_last_set"`
	NumMembers     int32       `json:"num_members"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Type,
		arg.CreatorID,
		arg.TopicValue,
		arg.TopicCreator,
		arg.PurposeValue,
		arg.PurposeCreator,
		arg.LastMessageTs,
		arg.LastActivityTs,
	)
	var i CreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.CreatorID,
		&i.IsArchived,
		&i.TopicValue,
		&i.TopicCreator,
		&i.TopicLastSet,
		&i.PurposeValue,
		&i.PurposeCreator,
		&i.PurposeLastSet,
		&i.NumMembers,
		&i.LastMessageTs,
		&i.LastActivityTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementConversationMemberCount = `-- name: DecrementConversationMemberCount :exec
UPDATE conversations
SET num_members = num_members - 1
WHERE id = $1
`

func (q *Queries) DecrementConversationMemberCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrementConversationMemberCount, id)
	return err
}

const deleteCanonicalDMByConversation = `-- name: DeleteCanonicalDMByConversation :execrows
DELETE FROM canonical_dms
WHERE conversation_id = $1
`

func (q *Queries) DeleteCanonicalDMByConversation(ctx context.Context, conversationID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCanonicalDMByConversation, conversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCanonicalDMConversation = `-- name: GetCanonicalDMConversation :one
SELECT c.id, c.workspace_id, c.name, c.type, c.creator_id, c.is_archived,
       c.topic_value, c.topic_creator, c.topic_last_set,
       c.purpose_value, c.purpose_creator, c.purpose_last_set,
       c.num_members, c.last_message_ts, c.last_activity_ts, c.created_at, c.updated_at
FROM canonical_dms d
JOIN conversations c ON c.id = d.conversation_id
WHERE d.workspace_id = $1
  AND d.user_low_id = $2
  AND d.user_high_id = $3
`

type GetCanonicalDMConversationParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserLowID   string `json:"user_low_id"`
	UserHighID  string `json:"user_high_id"`
}

type GetCanonicalDMConversationRow struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	IsArchived     bool        `json:"is_archived"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	TopicLastSet   *time.Time  `json:"topic_last_set"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	PurposeLastSet *time.Time  `json:"purpose_last_set"`
	NumMembers     int32       `json:"num_members"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) GetCanonicalDMConversation(ctx context.Context, arg GetCanonicalDMConversationParams) (GetCanonicalDMConversationRow, error) {
	row := q.db.QueryRow(ctx, getCanonicalDMConversation, arg.WorkspaceID, arg.UserLowID, arg.UserHighID)
	var i GetCanonicalDMConversationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.CreatorID,
		&i.IsArchived,
		&i.TopicValue,
		&i.TopicCreator,
		&i.TopicLastSet,
		&i.PurposeValue,
		&i.PurposeCreator,
		&i.PurposeLastSet,
		&i.NumMembers,
		&i.LastMessageTs,
		&i.LastActivityTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, workspace_id, name, type, creator_id, is_archived,
       topic_value, topic_creator, topic_last_set,
       purpose_value, purpose_creator, purpose_last_set,
       num_members, last_message_ts, last_activity_ts, created_at, updated_at
FROM conversations WHERE id = $1
`

type GetConversationRow struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	IsArchived     bool        `json:"is_archived"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	TopicLastSet   *time.Time  `json:"topic_last_set"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	PurposeLastSet *time.Time  `json:"purpose_last_set"`
	NumMembers     int32       `json:"num_members"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) GetConversation(ctx context.Context, id string) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i GetConversationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.CreatorID,
		&i.IsArchived,
		&i.TopicValue,
		&i.TopicCreator,
		&i.TopicLastSet,
		&i.PurposeValue,
		&i.PurposeCreator,
		&i.PurposeLastSet,
		&i.NumMembers,
		&i.LastMessageTs,
		&i.LastActivityTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementConversationMemberCount = `-- name: IncrementConversationMemberCount :exec
UPDATE conversations
SET num_members = num_members + 1
WHERE id = $1
`

func (q *Queries) IncrementConversationMemberCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementConversationMemberCount, id)
	return err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(SELECT 1 FROM conversation_members WHERE conversation_id = $1 AND user_id = $2)
`

type IsConversationMemberParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT conversation_id, user_id, joined_at
FROM conversation_members
WHERE conversation_id = $1 AND user_id >= $2
ORDER BY user_id ASC
LIMIT $3
`

type ListConversationMembersParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListConversationMembers(ctx context.Context, arg ListConversationMembersParams) ([]ConversationMember, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, arg.ConversationID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMember{}
	for rows.Next() {
		var i ConversationMember
		if err := rows.Scan(&i.ConversationID, &i.UserID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleConversations = `-- name: ListVisibleConversations :many
SELECT c.id, c.workspace_id, c.name, c.type, c.creator_id, c.is_archived,
       c.topic_value, c.topic_creator, c.topic_last_set,
       c.purpose_value, c.purpose_creator, c.purpose_last_set,
       c.num_members, c.last_message_ts, c.last_activity_ts,
       cr.last_read_ts,
       CASE
           WHEN $1 = '' THEN NULL::boolean
           WHEN c.last_message_ts IS NULL THEN FALSE
           WHEN cr.last_read_ts IS NULL THEN TRUE
           ELSE cr.last_read_ts < c.last_message_ts
       END AS has_unread,
       c.created_at, c.updated_at
FROM conversations c
LEFT JOIN conversation_members cm
  ON cm.conversation_id = c.id AND cm.user_id = $1
LEFT JOIN conversation_reads cr
  ON cr.conversation_id = c.id AND cr.user_id = $1
WHERE c.workspace_id = $2
  AND ($3::bool = FALSE OR c.is_archived = FALSE)
  AND (cardinality($4::text[]) = 0 OR c.type = ANY($4::text[]))
  AND (
    $5 = ''
    OR (COALESCE(c.last_activity_ts, ''), c.id) < ($5, $6)
  )
  AND (
    $1 = ''
    OR
    c.type = 'public_channel'
    OR cm.user_id IS NOT NULL
  )
ORDER BY COALESCE(c.last_activity_ts, '') DESC, c.id DESC
LIMIT $7
`

type ListVisibleConversationsParams struct {
	UserID          interface{} `json:"user_id"`
	WorkspaceID     string      `json:"workspace_id"`
	ExcludeArchived bool        `json:"exclude_archived"`
	Types           []string    `json:"types"`
	CursorActivity  interface{} `json:"cursor_activity"`
	CursorID        pgtype.Text `json:"cursor_id"`
	LimitCount      int32       `json:"limit_count"`
}

type ListVisibleConversationsRow struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	IsArchived     bool        `json:"is_archived"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	TopicLastSet   *time.Time  `json:"topic_last_set"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	PurposeLastSet *time.Time  `json:"purpose_last_set"`
	NumMembers     int32       `json:"num_members"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
	LastReadTs     pgtype.Text `json:"last_read_ts"`
	HasUnread      interface{} `json:"has_unread"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) ListVisibleConversations(ctx context.Context, arg ListVisibleConversationsParams) ([]ListVisibleConversationsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleConversations,
		arg.UserID,
		arg.WorkspaceID,
		arg.ExcludeArchived,
		arg.Types,
		arg.CursorActivity,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleConversationsRow{}
	for rows.Next() {
		var i ListVisibleConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.CreatorID,
			&i.IsArchived,
			&i.TopicValue,
			&i.TopicCreator,
			&i.TopicLastSet,
			&i.PurposeValue,
			&i.PurposeCreator,
			&i.PurposeLastSet,
			&i.NumMembers,
			&i.LastMessageTs,
			&i.LastActivityTs,
			&i.LastReadTs,
			&i.HasUnread,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversationForUpdate = `-- name: LockConversationForUpdate :one
SELECT id FROM conversations WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockConversationForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockConversationForUpdate, id)
	err := row.Scan(&id)
	return id, err
}

const removeConversationMember = `-- name: RemoveConversationMember :execrows
DELETE FROM conversation_members WHERE conversation_id = $1 AND user_id = $2
`

type RemoveConversationMemberParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setConversationPurpose = `-- name: SetConversationPurpose :one
UPDATE conversations SET purpose_value = $2, purpose_creator = $3, purpose_last_set = NOW()
WHERE id = $1
RETURNING id, workspace_id, name, type, creator_id, is_archived,
          topic_value, topic_creator, topic_last_set,
          purpose_value, purpose_creator, purpose_last_set,
          num_members, last_message_ts, last_activity_ts, created_at, updated_at
`

type SetConversationPurposeParams struct {
	ID             string `json:"id"`
	PurposeValue   string `json:"purpose_value"`
	PurposeCreator string `json:"purpose_creator"`
}

type SetConversationPurposeRow struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	IsArchived     bool        `json:"is_archived"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	TopicLastSet   *time.Time  `json:"topic_last_set"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	PurposeLastSet *time.Time  `json:"purpose_last_set"`
	NumMembers     int32       `json:"num_members"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) SetConversationPurpose(ctx context.Context, arg SetConversationPurposeParams) (SetConversationPurposeRow, error) {
	row := q.db.QueryRow(ctx, setConversationPurpose, arg.ID, arg.PurposeValue, arg.PurposeCreator)
	var i SetConversationPurposeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.CreatorID,
		&i.IsArchived,
		&i.TopicValue,
		&i.TopicCreator,
		&i.TopicLastSet,
		&i.PurposeValue,
		&i.PurposeCreator,
		&i.PurposeLastSet,
		&i.NumMembers,
		&i.LastMessageTs,
		&i.LastActivityTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setConversationTopic = `-- name: SetConversationTopic :one
UPDATE conversations SET topic_value = $2, topic_creator = $3, topic_last_set = NOW()
WHERE id = $1
RETURNING id, workspace_id, name, type, creator_id, is_archived,
          topic_value, topic_creator, topic_last_set,
          purpose_value, purpose_creator, purpose_last_set,
          num_members, last_message_ts, last_activity_ts, created_at, updated_at
`

type SetConversationTopicParams struct {
	ID           string `json:"id"`
	TopicValue   string `json:"topic_value"`
	TopicCreator string `json:"topic_creator"`
}

type SetConversationTopicRow struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	IsArchived     bool        `json:"is_archived"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	TopicLastSet   *time.Time  `json:"topic_last_set"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	PurposeLastSet *time.Time  `json:"purpose_last_set"`
	NumMembers     int32       `json:"num_members"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) SetConversationTopic(ctx context.Context, arg SetConversationTopicParams) (SetConversationTopicRow, error) {
	row := q.db.QueryRow(ctx, setConversationTopic, arg.ID, arg.TopicValue, arg.TopicCreator)
	var i SetConversationTopicRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.CreatorID,
		&i.IsArchived,
		&i.TopicValue,
		&i.TopicCreator,
		&i.TopicLastSet,
		&i.PurposeValue,
		&i.PurposeCreator,
		&i.PurposeLastSet,
		&i.NumMembers,
		&i.LastMessageTs,
		&i.LastActivityTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchiveConversation = `-- name: UnarchiveConversation :exec
UPDATE conversations SET is_archived = FALSE WHERE id = $1 AND is_archived = TRUE
`

func (q *Queries) UnarchiveConversation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unarchiveConversation, id)
	return err
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations SET name = $2, is_archived = $3
WHERE id = $1
RETURNING id, workspace_id, name, type, creator_id, is_archived,
          topic_value, topic_creator, topic_last_set,
          purpose_value, purpose_creator, purpose_last_set,
          num_members, last_message_ts, last_activity_ts, created_at, updated_at
`

type UpdateConversationParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	IsArchived bool   `json:"is_archived"`
}

type UpdateConversationRow struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CreatorID      string      `json:"creator_id"`
	IsArchived     bool        `json:"is_archived"`
	TopicValue     string      `json:"topic_value"`
	TopicCreator   string      `json:"topic_creator"`
	TopicLastSet   *time.Time  `json:"topic_last_set"`
	PurposeValue   string      `json:"purpose_value"`
	PurposeCreator string      `json:"purpose_creator"`
	PurposeLastSet *time.Time  `json:"purpose_last_set"`
	NumMembers     int32       `json:"num_members"`
	LastMessageTs  pgtype.Text `json:"last_message_ts"`
	LastActivityTs pgtype.Text `json:"last_activity_ts"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (UpdateConversationRow, error) {
	row := q.db.QueryRow(ctx, updateConversation, arg.ID, arg.Name, arg.IsArchived)
	var i UpdateConversationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.CreatorID,
		&i.IsArchived,
		&i.TopicValue,
		&i.TopicCreator,
		&i.TopicLastSet,
		&i.PurposeValue,
		&i.PurposeCreator,
		&i.PurposeLastSet,
		&i.NumMembers,
		&i.LastMessageTs,
		&i.LastActivityTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversationLastActivity = `-- name: UpdateConversationLastActivity :exec
UPDATE conversations
SET last_activity_ts = CASE
        WHEN last_activity_ts IS NULL OR last_activity_ts < $1 THEN $1
        ELSE last_activity_ts
    END
WHERE id = $2
`

type UpdateConversationLastActivityParams struct {
	Ts pgtype.Text `json:"ts"`
	ID string      `json:"id"`
}

func (q *Queries) UpdateConversationLastActivity(ctx context.Context, arg UpdateConversationLastActivityParams) error {
	_, err := q.db.Exec(ctx, updateConversationLastActivity, arg.Ts, arg.ID)
	return err
}

const updateConversationLastMessageAndActivity = `-- name: UpdateConversationLastMessageAndActivity :exec
UPDATE conversations
SET last_message_ts = CASE
        WHEN last_message_ts IS NULL OR last_message_ts < $1 THEN $1
        ELSE last_message_ts
    END,
    last_activity_ts = CASE
        WHEN last_activity_ts IS NULL OR last_activity_ts < $1 THEN $1
        ELSE last_activity_ts
    END
WHERE id = $2
`

type UpdateConversationLastMessageAndActivityParams struct {
	Ts pgtype.Text `json:"ts"`
	ID string      `json:"id"`
}

func (q *Queries) UpdateConversationLastMessageAndActivity(ctx context.Context, arg UpdateConversationLastMessageAndActivityParams) error {
	_, err := q.db.Exec(ctx, updateConversationLastMessageAndActivity, arg.Ts, arg.ID)
	return err
}
