// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: event_subscriptions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEventSubscription = `-- name: CreateEventSubscription :one
INSERT INTO event_subscriptions (id, workspace_id, url, event_type, resource_type, resource_id, encrypted_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, url, event_type, resource_type, resource_id, encrypted_secret, enabled, created_at, updated_at
`

type CreateEventSubscriptionParams struct {
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	Url             string `json:"url"`
	EventType       string `json:"event_type"`
	ResourceType    string `json:"resource_type"`
	ResourceID      string `json:"resource_id"`
	EncryptedSecret string `json:"encrypted_secret"`
}

type CreateEventSubscriptionRow struct {
	ID              string    `json:"id"`
	WorkspaceID     string    `json:"workspace_id"`
	Url             string    `json:"url"`
	EventType       string    `json:"event_type"`
	ResourceType    string    `json:"resource_type"`
	ResourceID      string    `json:"resource_id"`
	EncryptedSecret string    `json:"encrypted_secret"`
	Enabled         bool      `json:"enabled"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) CreateEventSubscription(ctx context.Context, arg CreateEventSubscriptionParams) (CreateEventSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createEventSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.Url,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
		arg.EncryptedSecret,
	)
	var i CreateEventSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.EncryptedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventSubscription = `-- name: DeleteEventSubscription :exec
DELETE FROM event_subscriptions WHERE id = $1
`

func (q *Queries) DeleteEventSubscription(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEventSubscription, id)
	return err
}

const getEventSubscription = `-- name: GetEventSubscription :one
SELECT id, workspace_id, url, event_type, resource_type, resource_id, encrypted_secret, enabled, created_at, updated_at
FROM event_subscriptions WHERE id = $1
`

type GetEventSubscriptionRow struct {
	ID              string    `json:"id"`
	WorkspaceID     string    `json:"workspace_id"`
	Url             string    `json:"url"`
	EventType       string    `json:"event_type"`
	ResourceType    string    `json:"resource_type"`
	ResourceID      string    `json:"resource_id"`
	EncryptedSecret string    `json:"encrypted_secret"`
	Enabled         bool      `json:"enabled"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetEventSubscription(ctx context.Context, id string) (GetEventSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getEventSubscription, id)
	var i GetEventSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.EncryptedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventSubscriptions = `-- name: ListEventSubscriptions :many
SELECT id, workspace_id, url, event_type, resource_type, resource_id, encrypted_secret, enabled, created_at, updated_at
FROM event_subscriptions WHERE workspace_id = $1
ORDER BY created_at ASC
`

type ListEventSubscriptionsRow struct {
	ID              string    `json:"id"`
	WorkspaceID     string    `json:"workspace_id"`
	Url             string    `json:"url"`
	EventType       string    `json:"event_type"`
	ResourceType    string    `json:"resource_type"`
	ResourceID      string    `json:"resource_id"`
	EncryptedSecret string    `json:"encrypted_secret"`
	Enabled         bool      `json:"enabled"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListEventSubscriptions(ctx context.Context, workspaceID string) ([]ListEventSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listEventSubscriptions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventSubscriptionsRow{}
	for rows.Next() {
		var i ListEventSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.EncryptedSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSubscriptionsByWorkspaceAndEvent = `-- name: ListEventSubscriptionsByWorkspaceAndEvent :many
SELECT id, workspace_id, url, event_type, resource_type, resource_id, encrypted_secret, enabled, created_at, updated_at
FROM event_subscriptions
WHERE workspace_id = $1
  AND enabled = TRUE
  AND (event_type = '' OR event_type = $2)
  AND ($3::TEXT IS NULL OR resource_type = '' OR resource_type = $3)
  AND ($4::TEXT IS NULL OR resource_id = '' OR resource_id = $4)
ORDER BY created_at ASC
`

type ListEventSubscriptionsByWorkspaceAndEventParams struct {
	WorkspaceID  string      `json:"workspace_id"`
	EventType    string      `json:"event_type"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
}

type ListEventSubscriptionsByWorkspaceAndEventRow struct {
	ID              string    `json:"id"`
	WorkspaceID     string    `json:"workspace_id"`
	Url             string    `json:"url"`
	EventType       string    `json:"event_type"`
	ResourceType    string    `json:"resource_type"`
	ResourceID      string    `json:"resource_id"`
	EncryptedSecret string    `json:"encrypted_secret"`
	Enabled         bool      `json:"enabled"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListEventSubscriptionsByWorkspaceAndEvent(ctx context.Context, arg ListEventSubscriptionsByWorkspaceAndEventParams) ([]ListEventSubscriptionsByWorkspaceAndEventRow, error) {
	rows, err := q.db.Query(ctx, listEventSubscriptionsByWorkspaceAndEvent,
		arg.WorkspaceID,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventSubscriptionsByWorkspaceAndEventRow{}
	for rows.Next() {
		var i ListEventSubscriptionsByWorkspaceAndEventRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.EncryptedSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventSubscription = `-- name: UpdateEventSubscription :one
UPDATE event_subscriptions
SET url = $2, event_type = $3, resource_type = $4, resource_id = $5, enabled = $6
WHERE id = $1
RETURNING id, workspace_id, url, event_type, resource_type, resource_id, encrypted_secret, enabled, created_at, updated_at
`

type UpdateEventSubscriptionParams struct {
	ID           string `json:"id"`
	Url          string `json:"url"`
	EventType    string `json:"event_type"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	Enabled      bool   `json:"enabled"`
}

type UpdateEventSubscriptionRow struct {
	ID              string    `json:"id"`
	WorkspaceID     string    `json:"workspace_id"`
	Url             string    `json:"url"`
	EventType       string    `json:"event_type"`
	ResourceType    string    `json:"resource_type"`
	ResourceID      string    `json:"resource_id"`
	EncryptedSecret string    `json:"encrypted_secret"`
	Enabled         bool      `json:"enabled"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) UpdateEventSubscription(ctx context.Context, arg UpdateEventSubscriptionParams) (UpdateEventSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, updateEventSubscription,
		arg.ID,
		arg.Url,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
		arg.Enabled,
	)
	var i UpdateEventSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.EncryptedSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
