// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: internal_events.sql

package sqlcgen

import (
	"context"
	"time"
)

const getInternalEventsByAggregate = `-- name: GetInternalEventsByAggregate :many
SELECT id, event_type, aggregate_type, aggregate_id, workspace_id, actor_id, shard_key, shard_id, payload, metadata, created_at
FROM internal_events
WHERE aggregate_type = $1 AND aggregate_id = $2
ORDER BY id ASC
`

type GetInternalEventsByAggregateParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
}

type GetInternalEventsByAggregateRow struct {
	ID            int64     `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	WorkspaceID   string    `json:"workspace_id"`
	ActorID       string    `json:"actor_id"`
	ShardKey      string    `json:"shard_key"`
	ShardID       int32     `json:"shard_id"`
	Payload       []byte    `json:"payload"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) GetInternalEventsByAggregate(ctx context.Context, arg GetInternalEventsByAggregateParams) ([]GetInternalEventsByAggregateRow, error) {
	rows, err := q.db.Query(ctx, getInternalEventsByAggregate, arg.AggregateType, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInternalEventsByAggregateRow{}
	for rows.Next() {
		var i GetInternalEventsByAggregateRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.ShardKey,
			&i.ShardID,
			&i.Payload,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInternalEventsByAggregateType = `-- name: GetInternalEventsByAggregateType :many
SELECT id, event_type, aggregate_type, aggregate_id, workspace_id, actor_id, shard_key, shard_id, payload, metadata, created_at
FROM internal_events
WHERE aggregate_type = $1
ORDER BY id ASC
`

type GetInternalEventsByAggregateTypeRow struct {
	ID            int64     `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	WorkspaceID   string    `json:"workspace_id"`
	ActorID       string    `json:"actor_id"`
	ShardKey      string    `json:"shard_key"`
	ShardID       int32     `json:"shard_id"`
	Payload       []byte    `json:"payload"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) GetInternalEventsByAggregateType(ctx context.Context, aggregateType string) ([]GetInternalEventsByAggregateTypeRow, error) {
	rows, err := q.db.Query(ctx, getInternalEventsByAggregateType, aggregateType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInternalEventsByAggregateTypeRow{}
	for rows.Next() {
		var i GetInternalEventsByAggregateTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.ShardKey,
			&i.ShardID,
			&i.Payload,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInternalEventsSince = `-- name: GetInternalEventsSince :many
SELECT id, event_type, aggregate_type, aggregate_id, workspace_id, actor_id, shard_key, shard_id, payload, metadata, created_at
FROM internal_events
WHERE id > $1
ORDER BY id ASC
LIMIT $2
`

type GetInternalEventsSinceParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

type GetInternalEventsSinceRow struct {
	ID            int64     `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	WorkspaceID   string    `json:"workspace_id"`
	ActorID       string    `json:"actor_id"`
	ShardKey      string    `json:"shard_key"`
	ShardID       int32     `json:"shard_id"`
	Payload       []byte    `json:"payload"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) GetInternalEventsSince(ctx context.Context, arg GetInternalEventsSinceParams) ([]GetInternalEventsSinceRow, error) {
	rows, err := q.db.Query(ctx, getInternalEventsSince, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInternalEventsSinceRow{}
	for rows.Next() {
		var i GetInternalEventsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.ShardKey,
			&i.ShardID,
			&i.Payload,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInternalEventsSinceByShard = `-- name: GetInternalEventsSinceByShard :many
SELECT id, event_type, aggregate_type, aggregate_id, workspace_id, actor_id, shard_key, shard_id, payload, metadata, created_at
FROM internal_events
WHERE shard_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type GetInternalEventsSinceByShardParams struct {
	ShardID int32 `json:"shard_id"`
	ID      int64 `json:"id"`
	Limit   int32 `json:"limit"`
}

type GetInternalEventsSinceByShardRow struct {
	ID            int64     `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	WorkspaceID   string    `json:"workspace_id"`
	ActorID       string    `json:"actor_id"`
	ShardKey      string    `json:"shard_key"`
	ShardID       int32     `json:"shard_id"`
	Payload       []byte    `json:"payload"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) GetInternalEventsSinceByShard(ctx context.Context, arg GetInternalEventsSinceByShardParams) ([]GetInternalEventsSinceByShardRow, error) {
	rows, err := q.db.Query(ctx, getInternalEventsSinceByShard, arg.ShardID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInternalEventsSinceByShardRow{}
	for rows.Next() {
		var i GetInternalEventsSinceByShardRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.ShardKey,
			&i.ShardID,
			&i.Payload,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInternalEvent = `-- name: InsertInternalEvent :one
INSERT INTO internal_events (event_type, aggregate_type, aggregate_id, workspace_id, actor_id, shard_key, shard_id, payload, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, event_type, aggregate_type, aggregate_id, workspace_id, actor_id, shard_key, shard_id, payload, metadata, created_at
`

type InsertInternalEventParams struct {
	EventType     string `json:"event_type"`
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	WorkspaceID   string `json:"workspace_id"`
	ActorID       string `json:"actor_id"`
	ShardKey      string `json:"shard_key"`
	ShardID       int32  `json:"shard_id"`
	Payload       []byte `json:"payload"`
	Metadata      []byte `json:"metadata"`
}

type InsertInternalEventRow struct {
	ID            int64     `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	WorkspaceID   string    `json:"workspace_id"`
	ActorID       string    `json:"actor_id"`
	ShardKey      string    `json:"shard_key"`
	ShardID       int32     `json:"shard_id"`
	Payload       []byte    `json:"payload"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertInternalEvent(ctx context.Context, arg InsertInternalEventParams) (InsertInternalEventRow, error) {
	row := q.db.QueryRow(ctx, insertInternalEvent,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.WorkspaceID,
		arg.ActorID,
		arg.ShardKey,
		arg.ShardID,
		arg.Payload,
		arg.Metadata,
	)
	var i InsertInternalEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.ShardKey,
		&i.ShardID,
		&i.Payload,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
