// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspaces.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    id, name, domain, email_domain, description,
    icon_image_original, icon_image_34, icon_image_44,
    discoverability, default_channels, preferences, profile_fields,
    billing_plan, billing_status, billing_email
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, name, domain, email_domain, description,
          icon_image_original, icon_image_34, icon_image_44,
          discoverability, default_channels, preferences, profile_fields,
          billing_plan, billing_status, billing_email, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID                string   `json:"id"`
	Name              string   `json:"name"`
	Domain            string   `json:"domain"`
	EmailDomain       string   `json:"email_domain"`
	Description       string   `json:"description"`
	IconImageOriginal string   `json:"icon_image_original"`
	IconImage34       string   `json:"icon_image_34"`
	IconImage44       string   `json:"icon_image_44"`
	Discoverability   string   `json:"discoverability"`
	DefaultChannels   []string `json:"default_channels"`
	Preferences       []byte   `json:"preferences"`
	ProfileFields     []byte   `json:"profile_fields"`
	BillingPlan       string   `json:"billing_plan"`
	BillingStatus     string   `json:"billing_status"`
	BillingEmail      string   `json:"billing_email"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.EmailDomain,
		arg.Description,
		arg.IconImageOriginal,
		arg.IconImage34,
		arg.IconImage44,
		arg.Discoverability,
		arg.DefaultChannels,
		arg.Preferences,
		arg.ProfileFields,
		arg.BillingPlan,
		arg.BillingStatus,
		arg.BillingEmail,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.EmailDomain,
		&i.Description,
		&i.IconImageOriginal,
		&i.IconImage34,
		&i.IconImage44,
		&i.Discoverability,
		&i.DefaultChannels,
		&i.Preferences,
		&i.ProfileFields,
		&i.BillingPlan,
		&i.BillingStatus,
		&i.BillingEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disconnectWorkspaceExternalWorkspace = `-- name: DisconnectWorkspaceExternalWorkspace :execrows
UPDATE workspace_external_workspaces
SET connected = FALSE, disconnected_at = NOW()
WHERE workspace_id = $1 AND external_workspace_id = $2 AND connected = TRUE
`

type DisconnectWorkspaceExternalWorkspaceParams struct {
	WorkspaceID         string `json:"workspace_id"`
	ExternalWorkspaceID string `json:"external_workspace_id"`
}

func (q *Queries) DisconnectWorkspaceExternalWorkspace(ctx context.Context, arg DisconnectWorkspaceExternalWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, disconnectWorkspaceExternalWorkspace, arg.WorkspaceID, arg.ExternalWorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, domain, email_domain, description,
       icon_image_original, icon_image_34, icon_image_44,
       discoverability, default_channels, preferences, profile_fields,
       billing_plan, billing_status, billing_email, created_at, updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.EmailDomain,
		&i.Description,
		&i.IconImageOriginal,
		&i.IconImage34,
		&i.IconImage44,
		&i.Discoverability,
		&i.DefaultChannels,
		&i.Preferences,
		&i.ProfileFields,
		&i.BillingPlan,
		&i.BillingStatus,
		&i.BillingEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceAccessLogs = `-- name: ListWorkspaceAccessLogs :many
SELECT se.actor_id,
       COALESCE(NULLIF(u.name, ''), se.actor_id) AS username,
       se.event_type,
       MIN(se.created_at) AS date_first,
       MAX(se.created_at) AS date_last
FROM internal_events se
LEFT JOIN users u ON u.id = se.actor_id
WHERE se.workspace_id = $1
  AND se.actor_id <> ''
  AND se.aggregate_type IN ('token', 'api_key')
GROUP BY se.actor_id, COALESCE(NULLIF(u.name, ''), se.actor_id), se.event_type
ORDER BY MAX(se.created_at) DESC
LIMIT $2
`

type ListWorkspaceAccessLogsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
}

type ListWorkspaceAccessLogsRow struct {
	ActorID   string      `json:"actor_id"`
	Username  string      `json:"username"`
	EventType string      `json:"event_type"`
	DateFirst interface{} `json:"date_first"`
	DateLast  interface{} `json:"date_last"`
}

func (q *Queries) ListWorkspaceAccessLogs(ctx context.Context, arg ListWorkspaceAccessLogsParams) ([]ListWorkspaceAccessLogsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceAccessLogs, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceAccessLogsRow{}
	for rows.Next() {
		var i ListWorkspaceAccessLogsRow
		if err := rows.Scan(
			&i.ActorID,
			&i.Username,
			&i.EventType,
			&i.DateFirst,
			&i.DateLast,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceAdmins = `-- name: ListWorkspaceAdmins :many
SELECT id, workspace_id, name, real_name, display_name, email,
       principal_type, owner_id, is_bot, account_type,
       deleted, profile, created_at, updated_at
FROM users
WHERE workspace_id = $1 AND deleted = FALSE AND account_type IN ('primary_admin', 'admin')
ORDER BY name ASC, id ASC
`

type ListWorkspaceAdminsRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Name          string    `json:"name"`
	RealName      string    `json:"real_name"`
	DisplayName   string    `json:"display_name"`
	Email         string    `json:"email"`
	PrincipalType string    `json:"principal_type"`
	OwnerID       string    `json:"owner_id"`
	IsBot         bool      `json:"is_bot"`
	AccountType   string    `json:"account_type"`
	Deleted       bool      `json:"deleted"`
	Profile       []byte    `json:"profile"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListWorkspaceAdmins(ctx context.Context, workspaceID string) ([]ListWorkspaceAdminsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceAdmins, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceAdminsRow{}
	for rows.Next() {
		var i ListWorkspaceAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.RealName,
			&i.DisplayName,
			&i.Email,
			&i.PrincipalType,
			&i.OwnerID,
			&i.IsBot,
			&i.AccountType,
			&i.Deleted,
			&i.Profile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceBillableInfo = `-- name: ListWorkspaceBillableInfo :many
SELECT id, (NOT is_bot AND NOT deleted) AS billing_active
FROM users
WHERE workspace_id = $1
ORDER BY id ASC
`

type ListWorkspaceBillableInfoRow struct {
	ID            string      `json:"id"`
	BillingActive pgtype.Bool `json:"billing_active"`
}

func (q *Queries) ListWorkspaceBillableInfo(ctx context.Context, workspaceID string) ([]ListWorkspaceBillableInfoRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceBillableInfo, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceBillableInfoRow{}
	for rows.Next() {
		var i ListWorkspaceBillableInfoRow
		if err := rows.Scan(&i.ID, &i.BillingActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceExternalWorkspaces = `-- name: ListWorkspaceExternalWorkspaces :many
SELECT id, external_workspace_id, external_workspace_name, connection_type,
       connected, created_at, disconnected_at
FROM workspace_external_workspaces
WHERE workspace_id = $1
ORDER BY created_at ASC, id ASC
`

type ListWorkspaceExternalWorkspacesRow struct {
	ID                    string     `json:"id"`
	ExternalWorkspaceID   string     `json:"external_workspace_id"`
	ExternalWorkspaceName string     `json:"external_workspace_name"`
	ConnectionType        string     `json:"connection_type"`
	Connected             bool       `json:"connected"`
	CreatedAt             time.Time  `json:"created_at"`
	DisconnectedAt        *time.Time `json:"disconnected_at"`
}

func (q *Queries) ListWorkspaceExternalWorkspaces(ctx context.Context, workspaceID string) ([]ListWorkspaceExternalWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceExternalWorkspaces, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceExternalWorkspacesRow{}
	for rows.Next() {
		var i ListWorkspaceExternalWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalWorkspaceID,
			&i.ExternalWorkspaceName,
			&i.ConnectionType,
			&i.Connected,
			&i.CreatedAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceIntegrationLogs = `-- name: ListWorkspaceIntegrationLogs :many
SELECT se.aggregate_id,
       CASE
           WHEN se.aggregate_type = 'event_subscription' THEN 'webhook'
           ELSE se.aggregate_type
       END AS app_type,
       CASE
           WHEN se.aggregate_type = 'event_subscription' THEN 'event_subscription'
           ELSE se.aggregate_type
       END AS app_name,
       se.actor_id,
       COALESCE(NULLIF(u.name, ''), se.actor_id) AS user_name,
       se.event_type,
       se.created_at
FROM internal_events se
LEFT JOIN users u ON u.id = se.actor_id
WHERE se.workspace_id = $1
  AND se.aggregate_type IN ('api_key', 'event_subscription')
ORDER BY se.created_at DESC
LIMIT $2
`

type ListWorkspaceIntegrationLogsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
}

type ListWorkspaceIntegrationLogsRow struct {
	AggregateID string      `json:"aggregate_id"`
	AppType     interface{} `json:"app_type"`
	AppName     interface{} `json:"app_name"`
	ActorID     string      `json:"actor_id"`
	UserName    string      `json:"user_name"`
	EventType   string      `json:"event_type"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListWorkspaceIntegrationLogs(ctx context.Context, arg ListWorkspaceIntegrationLogsParams) ([]ListWorkspaceIntegrationLogsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceIntegrationLogs, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceIntegrationLogsRow{}
	for rows.Next() {
		var i ListWorkspaceIntegrationLogsRow
		if err := rows.Scan(
			&i.AggregateID,
			&i.AppType,
			&i.AppName,
			&i.ActorID,
			&i.UserName,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceOwners = `-- name: ListWorkspaceOwners :many
SELECT id, workspace_id, name, real_name, display_name, email,
       principal_type, owner_id, is_bot, account_type,
       deleted, profile, created_at, updated_at
FROM users
WHERE workspace_id = $1 AND deleted = FALSE AND account_type = 'primary_admin'
ORDER BY name ASC, id ASC
`

type ListWorkspaceOwnersRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Name          string    `json:"name"`
	RealName      string    `json:"real_name"`
	DisplayName   string    `json:"display_name"`
	Email         string    `json:"email"`
	PrincipalType string    `json:"principal_type"`
	OwnerID       string    `json:"owner_id"`
	IsBot         bool      `json:"is_bot"`
	AccountType   string    `json:"account_type"`
	Deleted       bool      `json:"deleted"`
	Profile       []byte    `json:"profile"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListWorkspaceOwners(ctx context.Context, workspaceID string) ([]ListWorkspaceOwnersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceOwners, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceOwnersRow{}
	for rows.Next() {
		var i ListWorkspaceOwnersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.RealName,
			&i.DisplayName,
			&i.Email,
			&i.PrincipalType,
			&i.OwnerID,
			&i.IsBot,
			&i.AccountType,
			&i.Deleted,
			&i.Profile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, domain, email_domain, description,
       icon_image_original, icon_image_34, icon_image_44,
       discoverability, default_channels, preferences, profile_fields,
       billing_plan, billing_status, billing_email, created_at, updated_at
FROM workspaces
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.EmailDomain,
			&i.Description,
			&i.IconImageOriginal,
			&i.IconImage34,
			&i.IconImage44,
			&i.Discoverability,
			&i.DefaultChannels,
			&i.Preferences,
			&i.ProfileFields,
			&i.BillingPlan,
			&i.BillingStatus,
			&i.BillingEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = $2,
    domain = $3,
    email_domain = $4,
    description = $5,
    icon_image_original = $6,
    icon_image_34 = $7,
    icon_image_44 = $8,
    discoverability = $9,
    default_channels = $10,
    preferences = $11,
    profile_fields = $12,
    billing_plan = $13,
    billing_status = $14,
    billing_email = $15
WHERE id = $1
RETURNING id, name, domain, email_domain, description,
          icon_image_original, icon_image_34, icon_image_44,
          discoverability, default_channels, preferences, profile_fields,
          billing_plan, billing_status, billing_email, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID                string   `json:"id"`
	Name              string   `json:"name"`
	Domain            string   `json:"domain"`
	EmailDomain       string   `json:"email_domain"`
	Description       string   `json:"description"`
	IconImageOriginal string   `json:"icon_image_original"`
	IconImage34       string   `json:"icon_image_34"`
	IconImage44       string   `json:"icon_image_44"`
	Discoverability   string   `json:"discoverability"`
	DefaultChannels   []string `json:"default_channels"`
	Preferences       []byte   `json:"preferences"`
	ProfileFields     []byte   `json:"profile_fields"`
	BillingPlan       string   `json:"billing_plan"`
	BillingStatus     string   `json:"billing_status"`
	BillingEmail      string   `json:"billing_email"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.EmailDomain,
		arg.Description,
		arg.IconImageOriginal,
		arg.IconImage34,
		arg.IconImage44,
		arg.Discoverability,
		arg.DefaultChannels,
		arg.Preferences,
		arg.ProfileFields,
		arg.BillingPlan,
		arg.BillingStatus,
		arg.BillingEmail,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.EmailDomain,
		&i.Description,
		&i.IconImageOriginal,
		&i.IconImage34,
		&i.IconImage44,
		&i.Discoverability,
		&i.DefaultChannels,
		&i.Preferences,
		&i.ProfileFields,
		&i.BillingPlan,
		&i.BillingStatus,
		&i.BillingEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
