// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace_invites.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceInvite = `-- name: CreateWorkspaceInvite :one
INSERT INTO workspace_invites (id, workspace_id, email, invited_by, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, email, invited_by, accepted_by_user_id, expires_at, accepted_at, created_at, updated_at
`

type CreateWorkspaceInviteParams struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	Email       string    `json:"email"`
	InvitedBy   string    `json:"invited_by"`
	TokenHash   string    `json:"token_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type CreateWorkspaceInviteRow struct {
	ID               string      `json:"id"`
	WorkspaceID      string      `json:"workspace_id"`
	Email            string      `json:"email"`
	InvitedBy        string      `json:"invited_by"`
	AcceptedByUserID pgtype.Text `json:"accepted_by_user_id"`
	ExpiresAt        time.Time   `json:"expires_at"`
	AcceptedAt       *time.Time  `json:"accepted_at"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) CreateWorkspaceInvite(ctx context.Context, arg CreateWorkspaceInviteParams) (CreateWorkspaceInviteRow, error) {
	row := q.db.QueryRow(ctx, createWorkspaceInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.InvitedBy,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreateWorkspaceInviteRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.InvitedBy,
		&i.AcceptedByUserID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceInviteByTokenHash = `-- name: GetWorkspaceInviteByTokenHash :one
SELECT id, workspace_id, email, invited_by, accepted_by_user_id, expires_at, accepted_at, created_at, updated_at
FROM workspace_invites
WHERE token_hash = $1
`

type GetWorkspaceInviteByTokenHashRow struct {
	ID               string      `json:"id"`
	WorkspaceID      string      `json:"workspace_id"`
	Email            string      `json:"email"`
	InvitedBy        string      `json:"invited_by"`
	AcceptedByUserID pgtype.Text `json:"accepted_by_user_id"`
	ExpiresAt        time.Time   `json:"expires_at"`
	AcceptedAt       *time.Time  `json:"accepted_at"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) GetWorkspaceInviteByTokenHash(ctx context.Context, tokenHash string) (GetWorkspaceInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInviteByTokenHash, tokenHash)
	var i GetWorkspaceInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.InvitedBy,
		&i.AcceptedByUserID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceInviteAccepted = `-- name: MarkWorkspaceInviteAccepted :execrows
UPDATE workspace_invites
SET accepted_by_user_id = $2,
    accepted_at = $3
WHERE id = $1
`

type MarkWorkspaceInviteAcceptedParams struct {
	ID               string      `json:"id"`
	AcceptedByUserID pgtype.Text `json:"accepted_by_user_id"`
	AcceptedAt       *time.Time  `json:"accepted_at"`
}

func (q *Queries) MarkWorkspaceInviteAccepted(ctx context.Context, arg MarkWorkspaceInviteAcceptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkspaceInviteAccepted, arg.ID, arg.AcceptedByUserID, arg.AcceptedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
