/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack API
 * Canonical HTTP API for Teraslack.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseResponse,
  CreateEventSubscriptionRequest,
  EventSubscription,
  EventSubscriptionUpdateRequest,
  EventSubscriptionsCollection,
  ListEventSubscriptionsParams,
  NoContentResponse
} from '../model';

import { orvalFetch } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type listEventSubscriptionsResponse200 = {
  data: EventSubscriptionsCollection
  status: 200
}

export type listEventSubscriptionsResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type listEventSubscriptionsResponseSuccess = (listEventSubscriptionsResponse200) & {
  headers: Headers;
};
export type listEventSubscriptionsResponseError = (listEventSubscriptionsResponseDefault) & {
  headers: Headers;
};

export type listEventSubscriptionsResponse = (listEventSubscriptionsResponseSuccess | listEventSubscriptionsResponseError)

export const getListEventSubscriptionsUrl = (params?: ListEventSubscriptionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/event-subscriptions?${stringifiedParams}` : `/event-subscriptions`
}

export const listEventSubscriptions = async (params?: ListEventSubscriptionsParams, options?: RequestInit): Promise<listEventSubscriptionsResponse> => {

  return orvalFetch<listEventSubscriptionsResponse>(getListEventSubscriptionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEventSubscriptionsQueryKey = (params?: ListEventSubscriptionsParams,) => {
    return [
    `/event-subscriptions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEventSubscriptionsQueryOptions = <TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: ListEventSubscriptionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEventSubscriptionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEventSubscriptions>>> = ({ signal }) => listEventSubscriptions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEventSubscriptionsQueryResult = NonNullable<Awaited<ReturnType<typeof listEventSubscriptions>>>
export type ListEventSubscriptionsQueryError = ErrorType<ApiErrorResponseResponse>


export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  ListEventSubscriptionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof listEventSubscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListEventSubscriptionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof listEventSubscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListEventSubscriptionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: ListEventSubscriptionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEventSubscriptionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type createEventSubscriptionResponse201 = {
  data: EventSubscription
  status: 201
}

export type createEventSubscriptionResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 201>
}

export type createEventSubscriptionResponseSuccess = (createEventSubscriptionResponse201) & {
  headers: Headers;
};
export type createEventSubscriptionResponseError = (createEventSubscriptionResponseDefault) & {
  headers: Headers;
};

export type createEventSubscriptionResponse = (createEventSubscriptionResponseSuccess | createEventSubscriptionResponseError)

export const getCreateEventSubscriptionUrl = () => {




  return `/event-subscriptions`
}

export const createEventSubscription = async (createEventSubscriptionRequest: CreateEventSubscriptionRequest, options?: RequestInit): Promise<createEventSubscriptionResponse> => {

  return orvalFetch<createEventSubscriptionResponse>(getCreateEventSubscriptionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventSubscriptionRequest,)
  }
);}




export const getCreateEventSubscriptionMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEventSubscription>>, TError,{data: BodyType<CreateEventSubscriptionRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createEventSubscription>>, TError,{data: BodyType<CreateEventSubscriptionRequest>}, TContext> => {

const mutationKey = ['createEventSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEventSubscription>>, {data: BodyType<CreateEventSubscriptionRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createEventSubscription(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateEventSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof createEventSubscription>>>
    export type CreateEventSubscriptionMutationBody = BodyType<CreateEventSubscriptionRequest>
    export type CreateEventSubscriptionMutationError = ErrorType<ApiErrorResponseResponse>

    export const useCreateEventSubscription = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEventSubscription>>, TError,{data: BodyType<CreateEventSubscriptionRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEventSubscription>>,
        TError,
        {data: BodyType<CreateEventSubscriptionRequest>},
        TContext
      > => {
      return useMutation(getCreateEventSubscriptionMutationOptions(options), queryClient);
    }
    export type getEventSubscriptionResponse200 = {
  data: EventSubscription
  status: 200
}

export type getEventSubscriptionResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getEventSubscriptionResponseSuccess = (getEventSubscriptionResponse200) & {
  headers: Headers;
};
export type getEventSubscriptionResponseError = (getEventSubscriptionResponseDefault) & {
  headers: Headers;
};

export type getEventSubscriptionResponse = (getEventSubscriptionResponseSuccess | getEventSubscriptionResponseError)

export const getGetEventSubscriptionUrl = (id: string,) => {




  return `/event-subscriptions/${id}`
}

export const getEventSubscription = async (id: string, options?: RequestInit): Promise<getEventSubscriptionResponse> => {

  return orvalFetch<getEventSubscriptionResponse>(getGetEventSubscriptionUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetEventSubscriptionQueryKey = (id: string,) => {
    return [
    `/event-subscriptions/${id}`
    ] as const;
    }


export const getGetEventSubscriptionQueryOptions = <TData = Awaited<ReturnType<typeof getEventSubscription>>, TError = ErrorType<ApiErrorResponseResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscription>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventSubscriptionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventSubscription>>> = ({ signal }) => getEventSubscription(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventSubscription>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventSubscriptionQueryResult = NonNullable<Awaited<ReturnType<typeof getEventSubscription>>>
export type GetEventSubscriptionQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetEventSubscription<TData = Awaited<ReturnType<typeof getEventSubscription>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscription>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventSubscription>>,
          TError,
          Awaited<ReturnType<typeof getEventSubscription>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventSubscription<TData = Awaited<ReturnType<typeof getEventSubscription>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscription>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventSubscription>>,
          TError,
          Awaited<ReturnType<typeof getEventSubscription>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventSubscription<TData = Awaited<ReturnType<typeof getEventSubscription>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscription>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEventSubscription<TData = Awaited<ReturnType<typeof getEventSubscription>>, TError = ErrorType<ApiErrorResponseResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscription>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventSubscriptionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type updateEventSubscriptionResponse200 = {
  data: EventSubscription
  status: 200
}

export type updateEventSubscriptionResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateEventSubscriptionResponseSuccess = (updateEventSubscriptionResponse200) & {
  headers: Headers;
};
export type updateEventSubscriptionResponseError = (updateEventSubscriptionResponseDefault) & {
  headers: Headers;
};

export type updateEventSubscriptionResponse = (updateEventSubscriptionResponseSuccess | updateEventSubscriptionResponseError)

export const getUpdateEventSubscriptionUrl = (id: string,) => {




  return `/event-subscriptions/${id}`
}

export const updateEventSubscription = async (id: string,
    eventSubscriptionUpdateRequest: EventSubscriptionUpdateRequest, options?: RequestInit): Promise<updateEventSubscriptionResponse> => {

  return orvalFetch<updateEventSubscriptionResponse>(getUpdateEventSubscriptionUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      eventSubscriptionUpdateRequest,)
  }
);}




export const getUpdateEventSubscriptionMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEventSubscription>>, TError,{id: string;data: BodyType<EventSubscriptionUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateEventSubscription>>, TError,{id: string;data: BodyType<EventSubscriptionUpdateRequest>}, TContext> => {

const mutationKey = ['updateEventSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEventSubscription>>, {id: string;data: BodyType<EventSubscriptionUpdateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateEventSubscription(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateEventSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof updateEventSubscription>>>
    export type UpdateEventSubscriptionMutationBody = BodyType<EventSubscriptionUpdateRequest>
    export type UpdateEventSubscriptionMutationError = ErrorType<ApiErrorResponseResponse>

    export const useUpdateEventSubscription = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEventSubscription>>, TError,{id: string;data: BodyType<EventSubscriptionUpdateRequest>}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEventSubscription>>,
        TError,
        {id: string;data: BodyType<EventSubscriptionUpdateRequest>},
        TContext
      > => {
      return useMutation(getUpdateEventSubscriptionMutationOptions(options), queryClient);
    }
    export type deleteEventSubscriptionResponse204 = {
  data: NoContentResponse
  status: 204
}

export type deleteEventSubscriptionResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteEventSubscriptionResponseSuccess = (deleteEventSubscriptionResponse204) & {
  headers: Headers;
};
export type deleteEventSubscriptionResponseError = (deleteEventSubscriptionResponseDefault) & {
  headers: Headers;
};

export type deleteEventSubscriptionResponse = (deleteEventSubscriptionResponseSuccess | deleteEventSubscriptionResponseError)

export const getDeleteEventSubscriptionUrl = (id: string,) => {




  return `/event-subscriptions/${id}`
}

export const deleteEventSubscription = async (id: string, options?: RequestInit): Promise<deleteEventSubscriptionResponse> => {

  return orvalFetch<deleteEventSubscriptionResponse>(getDeleteEventSubscriptionUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteEventSubscriptionMutationOptions = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEventSubscription>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEventSubscription>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteEventSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEventSubscription>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteEventSubscription(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteEventSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEventSubscription>>>

    export type DeleteEventSubscriptionMutationError = ErrorType<ApiErrorResponseResponse>

    export const useDeleteEventSubscription = <TError = ErrorType<ApiErrorResponseResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEventSubscription>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEventSubscription>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteEventSubscriptionMutationOptions(options), queryClient);
    }
