package handler

import "net/http"

func (s *Server) registerOpenAPIRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /auth/email/start", s.handleStartEmailLogin)
	mux.HandleFunc("POST /auth/email/verify", s.handleVerifyEmailLogin)
	mux.HandleFunc("POST /auth/oauth/google/start", s.handleStartGoogleOAuth)
	mux.HandleFunc("GET /auth/oauth/google/callback", s.handleGoogleOAuthCallback)
	mux.HandleFunc("POST /auth/oauth/github/start", s.handleStartGitHubOAuth)
	mux.HandleFunc("GET /auth/oauth/github/callback", s.handleGitHubOAuthCallback)
	mux.HandleFunc("DELETE /auth/sessions/current", s.requireAuth(s.handleDeleteCurrentSession))
	mux.HandleFunc("GET /me", s.requireAuth(s.handleGetMe))
	mux.HandleFunc("PATCH /me/profile", s.requireAuth(s.handlePatchMeProfile))
	mux.HandleFunc("GET /agents", s.requireAuth(s.handleListAgents))
	mux.HandleFunc("POST /agents", s.requireAuth(s.handleCreateAgent))
	mux.HandleFunc("GET /agents/{agent_id}", s.requireAuth(s.handleGetAgent))
	mux.HandleFunc("PATCH /agents/{agent_id}", s.requireAuth(s.handlePatchAgent))
	mux.HandleFunc("GET /agents/{agent_id}/api-key", s.requireAuth(s.handleGetAgentAPIKey))
	mux.HandleFunc("POST /agents/{agent_id}/api-key/rotate", s.requireAuth(s.handleRotateAgentAPIKey))
	mux.HandleFunc("GET /api-keys", s.requireAuth(s.handleListAPIKeys))
	mux.HandleFunc("POST /api-keys", s.requireAuth(s.handleCreateAPIKey))
	mux.HandleFunc("DELETE /api-keys/{key_id}", s.requireAuth(s.handleDeleteAPIKey))
	mux.HandleFunc("POST /search", s.requireAuth(s.handleSearch))
	mux.HandleFunc("GET /workspaces", s.requireAuth(s.handleListWorkspaces))
	mux.HandleFunc("POST /workspaces", s.requireAuth(s.handleCreateWorkspace))
	mux.HandleFunc("GET /workspaces/{workspace_id}", s.requireAuth(s.handleGetWorkspace))
	mux.HandleFunc("PATCH /workspaces/{workspace_id}", s.requireAuth(s.handlePatchWorkspace))
	mux.HandleFunc("GET /workspaces/{workspace_id}/members", s.requireAuth(s.handleListWorkspaceMembers))
	mux.HandleFunc("POST /workspaces/{workspace_id}/invites", s.requireAuth(s.handleCreateWorkspaceInvite))
	mux.HandleFunc("POST /workspace-invites/{token}/accept", s.requireAuth(s.handleAcceptWorkspaceInvite))
	mux.HandleFunc("PATCH /workspaces/{workspace_id}/members/{user_id}", s.requireAuth(s.handlePatchWorkspaceMember))
	mux.HandleFunc("GET /conversations", s.requireAuth(s.handleListConversations))
	mux.HandleFunc("POST /conversations", s.requireAuth(s.handleCreateConversation))
	mux.HandleFunc("GET /conversations/{conversation_id}", s.requireAuth(s.handleGetConversation))
	mux.HandleFunc("PATCH /conversations/{conversation_id}", s.requireAuth(s.handlePatchConversation))
	mux.HandleFunc("GET /conversations/{conversation_id}/share-link", s.requireAuth(s.handleGetConversationShareLink))
	mux.HandleFunc("POST /conversations/{conversation_id}/share-link/rotate", s.requireAuth(s.handleRotateConversationShareLink))
	mux.HandleFunc("POST /conversations/join", s.requireAuth(s.handleJoinConversation))
	mux.HandleFunc("GET /conversations/{conversation_id}/participants", s.requireAuth(s.handleListConversationParticipants))
	mux.HandleFunc("POST /conversations/{conversation_id}/participants", s.requireAuth(s.handleAddConversationParticipants))
	mux.HandleFunc("DELETE /conversations/{conversation_id}/participants/{user_id}", s.requireAuth(s.handleDeleteConversationParticipant))
	mux.HandleFunc("GET /conversations/{conversation_id}/messages", s.requireAuth(s.handleListMessages))
	mux.HandleFunc("POST /conversations/{conversation_id}/messages", s.requireAuth(s.handleCreateMessage))
	mux.HandleFunc("PATCH /messages/{message_id}", s.requireAuth(s.handlePatchMessage))
	mux.HandleFunc("DELETE /messages/{message_id}", s.requireAuth(s.handleDeleteMessage))
	mux.HandleFunc("PUT /conversations/{conversation_id}/read-state", s.requireAuth(s.handlePutReadState))
	mux.HandleFunc("GET /events", s.requireAuth(s.handleListEvents))
	mux.HandleFunc("GET /event-subscriptions", s.requireAuth(s.handleListEventSubscriptions))
	mux.HandleFunc("POST /event-subscriptions", s.requireAuth(s.handleCreateEventSubscription))
	mux.HandleFunc("PATCH /event-subscriptions/{subscription_id}", s.requireAuth(s.handlePatchEventSubscription))
	mux.HandleFunc("DELETE /event-subscriptions/{subscription_id}", s.requireAuth(s.handleDeleteEventSubscription))
}
