/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Teraslack Messaging API
 * Canonical HTTP API contract for the Teraslack server.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiErrorResponseResponse,
  DashboardAuditResponse,
  DashboardDataActivityResponse,
  DashboardOverview,
  DashboardTrafficResponse,
  DashboardWebhooksResponse,
  GetDashboardAuditParams,
  GetDashboardDataActivityParams,
  GetDashboardOverviewParams,
  GetDashboardTrafficParams,
  GetDashboardWebhooksParams
} from '../model';

import { orvalFetch } from '../../orval-mutator';
import type { ErrorType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


/**
 * Returns the top-level key, traffic, webhook, and data summaries for the caller. Workspace-scoped API keys are restricted to their bound workspace.
 * @summary Get dashboard overview
 */
export type getDashboardOverviewResponse200 = {
  data: DashboardOverview
  status: 200
}

export type getDashboardOverviewResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDashboardOverviewResponseSuccess = (getDashboardOverviewResponse200) & {
  headers: Headers;
};
export type getDashboardOverviewResponseError = (getDashboardOverviewResponseDefault) & {
  headers: Headers;
};

export type getDashboardOverviewResponse = (getDashboardOverviewResponseSuccess | getDashboardOverviewResponseError)

export const getGetDashboardOverviewUrl = (params?: GetDashboardOverviewParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/dashboard/overview?${stringifiedParams}` : `/dashboard/overview`
}

export const getDashboardOverview = async (params?: GetDashboardOverviewParams, options?: RequestInit): Promise<getDashboardOverviewResponse> => {

  return orvalFetch<getDashboardOverviewResponse>(getGetDashboardOverviewUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardOverviewQueryKey = (params?: GetDashboardOverviewParams,) => {
    return [
    `/dashboard/overview`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDashboardOverviewQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardOverview>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: GetDashboardOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardOverview>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardOverviewQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardOverview>>> = ({ signal }) => getDashboardOverview(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardOverview>>>
export type GetDashboardOverviewQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetDashboardOverview<TData = Awaited<ReturnType<typeof getDashboardOverview>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  GetDashboardOverviewParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardOverview>>,
          TError,
          Awaited<ReturnType<typeof getDashboardOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardOverview<TData = Awaited<ReturnType<typeof getDashboardOverview>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardOverview>>,
          TError,
          Awaited<ReturnType<typeof getDashboardOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardOverview<TData = Awaited<ReturnType<typeof getDashboardOverview>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardOverview>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard overview
 */

export function useGetDashboardOverview<TData = Awaited<ReturnType<typeof getDashboardOverview>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardOverview>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardOverviewQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns recent request volume, latency, status code, endpoint, and API key breakdowns for the caller.
 * @summary Get dashboard traffic analytics
 */
export type getDashboardTrafficResponse200 = {
  data: DashboardTrafficResponse
  status: 200
}

export type getDashboardTrafficResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDashboardTrafficResponseSuccess = (getDashboardTrafficResponse200) & {
  headers: Headers;
};
export type getDashboardTrafficResponseError = (getDashboardTrafficResponseDefault) & {
  headers: Headers;
};

export type getDashboardTrafficResponse = (getDashboardTrafficResponseSuccess | getDashboardTrafficResponseError)

export const getGetDashboardTrafficUrl = (params?: GetDashboardTrafficParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/dashboard/traffic?${stringifiedParams}` : `/dashboard/traffic`
}

export const getDashboardTraffic = async (params?: GetDashboardTrafficParams, options?: RequestInit): Promise<getDashboardTrafficResponse> => {

  return orvalFetch<getDashboardTrafficResponse>(getGetDashboardTrafficUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardTrafficQueryKey = (params?: GetDashboardTrafficParams,) => {
    return [
    `/dashboard/traffic`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDashboardTrafficQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardTraffic>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: GetDashboardTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardTraffic>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardTrafficQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardTraffic>>> = ({ signal }) => getDashboardTraffic(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardTraffic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardTrafficQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardTraffic>>>
export type GetDashboardTrafficQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetDashboardTraffic<TData = Awaited<ReturnType<typeof getDashboardTraffic>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  GetDashboardTrafficParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardTraffic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTraffic>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTraffic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardTraffic<TData = Awaited<ReturnType<typeof getDashboardTraffic>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardTraffic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTraffic>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTraffic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardTraffic<TData = Awaited<ReturnType<typeof getDashboardTraffic>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardTraffic>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard traffic analytics
 */

export function useGetDashboardTraffic<TData = Awaited<ReturnType<typeof getDashboardTraffic>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardTraffic>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardTrafficQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns webhook subscription inventory plus recent delivery outcomes for the caller.
 * @summary Get dashboard webhook health
 */
export type getDashboardWebhooksResponse200 = {
  data: DashboardWebhooksResponse
  status: 200
}

export type getDashboardWebhooksResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDashboardWebhooksResponseSuccess = (getDashboardWebhooksResponse200) & {
  headers: Headers;
};
export type getDashboardWebhooksResponseError = (getDashboardWebhooksResponseDefault) & {
  headers: Headers;
};

export type getDashboardWebhooksResponse = (getDashboardWebhooksResponseSuccess | getDashboardWebhooksResponseError)

export const getGetDashboardWebhooksUrl = (params?: GetDashboardWebhooksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/dashboard/webhooks?${stringifiedParams}` : `/dashboard/webhooks`
}

export const getDashboardWebhooks = async (params?: GetDashboardWebhooksParams, options?: RequestInit): Promise<getDashboardWebhooksResponse> => {

  return orvalFetch<getDashboardWebhooksResponse>(getGetDashboardWebhooksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardWebhooksQueryKey = (params?: GetDashboardWebhooksParams,) => {
    return [
    `/dashboard/webhooks`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDashboardWebhooksQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardWebhooks>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: GetDashboardWebhooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardWebhooks>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardWebhooksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardWebhooks>>> = ({ signal }) => getDashboardWebhooks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardWebhooks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardWebhooksQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardWebhooks>>>
export type GetDashboardWebhooksQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetDashboardWebhooks<TData = Awaited<ReturnType<typeof getDashboardWebhooks>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  GetDashboardWebhooksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardWebhooks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardWebhooks>>,
          TError,
          Awaited<ReturnType<typeof getDashboardWebhooks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardWebhooks<TData = Awaited<ReturnType<typeof getDashboardWebhooks>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardWebhooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardWebhooks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardWebhooks>>,
          TError,
          Awaited<ReturnType<typeof getDashboardWebhooks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardWebhooks<TData = Awaited<ReturnType<typeof getDashboardWebhooks>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardWebhooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardWebhooks>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard webhook health
 */

export function useGetDashboardWebhooks<TData = Awaited<ReturnType<typeof getDashboardWebhooks>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardWebhooksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardWebhooks>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardWebhooksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns conversation, message, event, and room mix activity summaries for accessible conversations.
 * @summary Get dashboard data activity
 */
export type getDashboardDataActivityResponse200 = {
  data: DashboardDataActivityResponse
  status: 200
}

export type getDashboardDataActivityResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDashboardDataActivityResponseSuccess = (getDashboardDataActivityResponse200) & {
  headers: Headers;
};
export type getDashboardDataActivityResponseError = (getDashboardDataActivityResponseDefault) & {
  headers: Headers;
};

export type getDashboardDataActivityResponse = (getDashboardDataActivityResponseSuccess | getDashboardDataActivityResponseError)

export const getGetDashboardDataActivityUrl = (params?: GetDashboardDataActivityParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/dashboard/data-activity?${stringifiedParams}` : `/dashboard/data-activity`
}

export const getDashboardDataActivity = async (params?: GetDashboardDataActivityParams, options?: RequestInit): Promise<getDashboardDataActivityResponse> => {

  return orvalFetch<getDashboardDataActivityResponse>(getGetDashboardDataActivityUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardDataActivityQueryKey = (params?: GetDashboardDataActivityParams,) => {
    return [
    `/dashboard/data-activity`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDashboardDataActivityQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardDataActivity>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: GetDashboardDataActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardDataActivity>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardDataActivityQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardDataActivity>>> = ({ signal }) => getDashboardDataActivity(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardDataActivity>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardDataActivityQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardDataActivity>>>
export type GetDashboardDataActivityQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetDashboardDataActivity<TData = Awaited<ReturnType<typeof getDashboardDataActivity>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  GetDashboardDataActivityParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardDataActivity>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardDataActivity>>,
          TError,
          Awaited<ReturnType<typeof getDashboardDataActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardDataActivity<TData = Awaited<ReturnType<typeof getDashboardDataActivity>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardDataActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardDataActivity>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardDataActivity>>,
          TError,
          Awaited<ReturnType<typeof getDashboardDataActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardDataActivity<TData = Awaited<ReturnType<typeof getDashboardDataActivity>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardDataActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardDataActivity>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard data activity
 */

export function useGetDashboardDataActivity<TData = Awaited<ReturnType<typeof getDashboardDataActivity>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardDataActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardDataActivity>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardDataActivityQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns recent internal lifecycle events initiated by the caller, optionally filtered to one workspace.
 * @summary Get dashboard audit trail
 */
export type getDashboardAuditResponse200 = {
  data: DashboardAuditResponse
  status: 200
}

export type getDashboardAuditResponseDefault = {
  data: ApiErrorResponseResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDashboardAuditResponseSuccess = (getDashboardAuditResponse200) & {
  headers: Headers;
};
export type getDashboardAuditResponseError = (getDashboardAuditResponseDefault) & {
  headers: Headers;
};

export type getDashboardAuditResponse = (getDashboardAuditResponseSuccess | getDashboardAuditResponseError)

export const getGetDashboardAuditUrl = (params?: GetDashboardAuditParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/dashboard/audit?${stringifiedParams}` : `/dashboard/audit`
}

export const getDashboardAudit = async (params?: GetDashboardAuditParams, options?: RequestInit): Promise<getDashboardAuditResponse> => {

  return orvalFetch<getDashboardAuditResponse>(getGetDashboardAuditUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardAuditQueryKey = (params?: GetDashboardAuditParams,) => {
    return [
    `/dashboard/audit`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDashboardAuditQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardAudit>>, TError = ErrorType<ApiErrorResponseResponse>>(params?: GetDashboardAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAudit>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardAuditQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardAudit>>> = ({ signal }) => getDashboardAudit(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardAudit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardAuditQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardAudit>>>
export type GetDashboardAuditQueryError = ErrorType<ApiErrorResponseResponse>


export function useGetDashboardAudit<TData = Awaited<ReturnType<typeof getDashboardAudit>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params: undefined |  GetDashboardAuditParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAudit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardAudit>>,
          TError,
          Awaited<ReturnType<typeof getDashboardAudit>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardAudit<TData = Awaited<ReturnType<typeof getDashboardAudit>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAudit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardAudit>>,
          TError,
          Awaited<ReturnType<typeof getDashboardAudit>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardAudit<TData = Awaited<ReturnType<typeof getDashboardAudit>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAudit>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard audit trail
 */

export function useGetDashboardAudit<TData = Awaited<ReturnType<typeof getDashboardAudit>>, TError = ErrorType<ApiErrorResponseResponse>>(
 params?: GetDashboardAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAudit>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardAuditQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




